import { mutation, query, type QueryCtx } from "./_generated/server";
import { paginationOptsValidator } from "convex/server";
import { ConvexError, v } from "convex/values";
import { requirePermission, logAction, type AuthUser } from "./lib/auth";
import { DEFAULT_CHART, GENERAL_LEDGER_CHART_VERSION } from "./lib/generalLedgerTemplate";
import { assertIsoDate, fingerprint, normalizeRequestId, normalizeText, periodKeyOf } from "./lib/generalLedgerRules";
import { postJournal } from "./lib/generalLedger";
import type { Id } from "./_generated/dataModel";

const lineValidator=v.object({accountId:v.id("chartOfAccounts"),debit:v.number(),credit:v.number(),description:v.optional(v.string())});
function scopedBranch(user:AuthUser,requested?:Id<"branches">){ if(user.role==="admin"||user.role==="accountant"){if(!requested&&!user.branchId) throw new ConvexError("اختر الفرع"); return requested??user.branchId!;} if(!user.branchId) throw new ConvexError("المستخدم غير مربوط بفرع"); return user.branchId; }

export const initialize=mutation({args:{cutoverDate:v.string(),requestId:v.string()},handler:async(ctx,args)=>{
 const user=await requirePermission(ctx,"initialize_general_ledger"),requestId=normalizeRequestId(args.requestId),cutoverDate=assertIsoDate(args.cutoverDate),fp=fingerprint({cutoverDate,chartVersion:GENERAL_LEDGER_CHART_VERSION});
 const prior=await ctx.db.query("generalLedgerSettings").withIndex("by_request",q=>q.eq("initializationRequestId",requestId)).unique();
 if(prior){if(prior.initializationFingerprint!==fp)throw new ConvexError("معرف الطلب مستخدم بتهيئة مختلفة");return {_id:prior._id,status:prior.status,chartVersion:prior.chartVersion};}
 const current=await ctx.db.query("generalLedgerSettings").first(); if(current)throw new ConvexError("تمت تهيئة الأستاذ العام بالفعل");
 const ids=new Map<string,Id<"chartOfAccounts">>(); const now=Date.now();
 for(const item of DEFAULT_CHART){const parentId=item.parentCode?ids.get(item.parentCode):undefined;if(item.parentCode&&!parentId)throw new ConvexError("قالب الدليل غير مرتب");const id=await ctx.db.insert("chartOfAccounts",{code:item.code,normalizedCode:item.code,nameAr:item.nameAr,parentId,accountClass:item.accountClass,normalSide:item.normalSide,isContra:item.isContra??false,isPosting:item.isPosting,isSystem:true,systemKey:item.systemKey,isActive:true,createdAt:now,createdBy:user.userId});ids.set(item.code,id);}
 const id=await ctx.db.insert("generalLedgerSettings",{baseCurrency:"EGP",chartVersion:GENERAL_LEDGER_CHART_VERSION,status:"foundation_ready",operationalPostingEnabled:false,cutoverDate,initializedAt:now,initializedBy:user.userId,initializationRequestId:requestId,initializationFingerprint:fp});
 await logAction(ctx,user,{action:"initialize",module:"general_ledger",recordId:String(id),details:"Foundation only; operational posting disabled"}); return {_id:id,status:"foundation_ready" as const,chartVersion:GENERAL_LEDGER_CHART_VERSION};
}});
export const status=query({args:{},handler:async ctx=>{await requirePermission(ctx,"view_general_ledger");const s=await ctx.db.query("generalLedgerSettings").first();return s?{initialized:true,baseCurrency:s.baseCurrency,chartVersion:s.chartVersion,status:s.status,operationalPostingEnabled:s.operationalPostingEnabled,initializedAt:s.initializedAt}:{initialized:false,operationalPostingEnabled:false};}});
export const chart=query({args:{activeOnly:v.optional(v.boolean())},handler:async(ctx,args)=>{await requirePermission(ctx,"view_general_ledger");const rows=args.activeOnly===false?await ctx.db.query("chartOfAccounts").withIndex("by_active").collect():await ctx.db.query("chartOfAccounts").withIndex("by_active",q=>q.eq("isActive",true)).collect();return rows.map(a=>({_id:a._id,code:a.code,nameAr:a.nameAr,nameEn:a.nameEn,parentId:a.parentId,accountClass:a.accountClass,normalSide:a.normalSide,isContra:a.isContra,isPosting:a.isPosting,isSystem:a.isSystem,systemKey:a.systemKey,isActive:a.isActive}));}});
export const accountPicker=query({args:{},handler:async ctx=>{await requirePermission(ctx,"view_general_ledger");const rows=await ctx.db.query("chartOfAccounts").withIndex("by_active",q=>q.eq("isActive",true)).collect();return rows.filter(a=>a.isPosting).map(a=>({_id:a._id,code:a.code,nameAr:a.nameAr,normalSide:a.normalSide}));}});
export const createAccount=mutation({args:{code:v.string(),nameAr:v.string(),nameEn:v.optional(v.string()),parentId:v.id("chartOfAccounts"),normalSide:v.union(v.literal("debit"),v.literal("credit")),isContra:v.boolean()},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"manage_chart_of_accounts"),code=args.code.replace(/\s+/g,"").toUpperCase(),nameAr=normalizeText(args.nameAr);if(!code)throw new ConvexError("الكود مطلوب");if(!nameAr)throw new ConvexError("اسم الحساب مطلوب");if(await ctx.db.query("chartOfAccounts").withIndex("by_code",q=>q.eq("normalizedCode",code)).unique())throw new ConvexError("كود الحساب مكرر");const parent=await ctx.db.get(args.parentId);if(!parent||parent.isPosting||!parent.isActive)throw new ConvexError("الحساب الأب غير صالح");const classSide=parent.accountClass==="asset"||parent.accountClass==="expense"?"debit":"credit",expected=args.isContra?(classSide==="debit"?"credit":"debit"):classSide;if(args.normalSide!==expected)throw new ConvexError("الطبيعة المحاسبية لا تطابق فئة الحساب");const id=await ctx.db.insert("chartOfAccounts",{code,normalizedCode:code,nameAr,nameEn:args.nameEn?normalizeText(args.nameEn):undefined,parentId:parent._id,accountClass:parent.accountClass,normalSide:args.normalSide,isContra:args.isContra,isPosting:true,isSystem:false,isActive:true,createdAt:Date.now(),createdBy:user.userId});await logAction(ctx,user,{action:"create",module:"general_ledger",recordId:String(id),recordLabel:code,details:`account ${nameAr}`});return id;}});
export const deactivateAccount=mutation({args:{accountId:v.id("chartOfAccounts")},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"manage_chart_of_accounts"),a=await ctx.db.get(args.accountId);if(!a||a.isSystem)throw new ConvexError("لا يمكن تعطيل حساب نظام");await ctx.db.patch(a._id,{isActive:false,deactivatedAt:Date.now(),deactivatedBy:user.userId});await logAction(ctx,user,{action:"deactivate",module:"general_ledger",recordId:String(a._id),recordLabel:a.code});return {accountId:a._id,isActive:false};}});
export const createOrOpenPeriod=mutation({args:{periodKey:v.string()},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"close_accounting_periods");if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(args.periodKey))throw new ConvexError("مفتاح الفترة غير صالح");const existing=await ctx.db.query("accountingPeriods").withIndex("by_key",q=>q.eq("periodKey",args.periodKey)).unique();if(existing){if(existing.status==="closed")throw new ConvexError("استخدم إعادة الفتح للفترة المغلقة");return existing._id;}const startDate=`${args.periodKey}-01`,d=new Date(`${startDate}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);const endDate=d.toISOString().slice(0,10);const id=await ctx.db.insert("accountingPeriods",{periodKey:args.periodKey,startDate,endDate,status:"open"});await logAction(ctx,user,{action:"open_period",module:"general_ledger",recordId:String(id),recordLabel:args.periodKey});return id;}});
export const closePeriod=mutation({args:{periodKey:v.string(),reason:v.string()},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"close_accounting_periods"),p=await ctx.db.query("accountingPeriods").withIndex("by_key",q=>q.eq("periodKey",args.periodKey)).unique(),reason=normalizeText(args.reason);if(!p||p.status!=="open"||!reason)throw new ConvexError("الفترة أو السبب غير صالح");const balances=await ctx.db.query("generalLedgerPeriodBalances").withIndex("by_period",q=>q.eq("periodKey",args.periodKey)).collect();const d=balances.reduce((s,x)=>s+x.debitTotal,0),c=balances.reduce((s,x)=>s+x.creditTotal,0);if(Math.round(d*100)!==Math.round(c*100))throw new ConvexError("الفترة غير متوازنة");await ctx.db.patch(p._id,{status:"closed",closedAt:Date.now(),closedBy:user.userId,closeReason:reason});await logAction(ctx,user,{action:"close_period",module:"general_ledger",recordId:String(p._id),details:reason});return p._id;}});
export const reopenPeriod=mutation({args:{periodKey:v.string(),reason:v.string()},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"reopen_accounting_periods"),p=await ctx.db.query("accountingPeriods").withIndex("by_key",q=>q.eq("periodKey",args.periodKey)).unique(),reason=normalizeText(args.reason);if(!p||p.status!=="closed"||!reason)throw new ConvexError("الفترة أو السبب غير صالح");await ctx.db.patch(p._id,{status:"open",reopenedAt:Date.now(),reopenedBy:user.userId,reopenReason:reason});await logAction(ctx,user,{action:"reopen_period",module:"general_ledger",recordId:String(p._id),details:reason});return p._id;}});
export const periods=query({args:{},handler:async ctx=>{await requirePermission(ctx,"view_general_ledger");return (await ctx.db.query("accountingPeriods").withIndex("by_start").order("desc").collect()).map(p=>({periodKey:p.periodKey,startDate:p.startDate,endDate:p.endDate,status:p.status,closeReason:p.closeReason,reopenReason:p.reopenReason}));}});
export const confirmOpening=mutation({args:{branchId:v.id("branches"),openingDate:v.string(),isZeroOpening:v.boolean(),lines:v.array(lineValidator),requestId:v.string()},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"initialize_general_ledger"),branchId=scopedBranch(user,args.branchId),requestId=normalizeRequestId(args.requestId),openingDate=assertIsoDate(args.openingDate),fp=fingerprint({branchId:String(branchId),openingDate,isZeroOpening:args.isZeroOpening,lines:args.lines});const retry=await ctx.db.query("generalLedgerOpenings").withIndex("by_request",q=>q.eq("requestId",requestId)).unique();if(retry){if(retry.fingerprint!==fp)throw new ConvexError("معرف الطلب مستخدم بحمولة مختلفة");return retry;}if(await ctx.db.query("generalLedgerOpenings").withIndex("by_branch",q=>q.eq("branchId",branchId)).unique())throw new ConvexError("تم اعتماد افتتاح الفرع");if(await ctx.db.query("journalEntries").withIndex("by_branch_date",q=>q.eq("branchId",branchId)).filter(q=>q.eq(q.field("sourceType"),"manual")).first())throw new ConvexError("لا يمكن الافتتاح بعد حركة يدوية");const settings=await ctx.db.query("generalLedgerSettings").first();if(!settings||openingDate<settings.cutoverDate)throw new ConvexError("تاريخ الافتتاح يسبق القطع");if(args.isZeroOpening&&args.lines.length)throw new ConvexError("الافتتاح الصفري لا يحتوي سطورًا");const entry=args.isZeroOpening?undefined:await postJournal(ctx,user,{branchId,date:openingDate,memo:"الأرصدة الافتتاحية",lines:args.lines,requestId,sourceType:"opening"});const id=await ctx.db.insert("generalLedgerOpenings",{branchId,openingDate,status:"confirmed",isZeroOpening:args.isZeroOpening,openingEntryId:entry?._id,requestId,fingerprint:fp,confirmedAt:Date.now(),confirmedBy:user.userId});return (await ctx.db.get(id))!;}});
export const postManualJournal=mutation({args:{branchId:v.id("branches"),date:v.string(),memo:v.string(),lines:v.array(lineValidator),requestId:v.string()},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"post_manual_journals"),branchId=scopedBranch(user,args.branchId);if(!await ctx.db.query("generalLedgerOpenings").withIndex("by_branch",q=>q.eq("branchId",branchId)).unique())throw new ConvexError("يجب اعتماد افتتاح الفرع أولًا");return postJournal(ctx,user,{branchId,date:args.date,memo:args.memo,lines:args.lines,requestId:args.requestId,sourceType:"manual"});}});
export const reverseJournal=mutation({args:{entryId:v.id("journalEntries"),reversalDate:v.string(),reason:v.string(),requestId:v.string()},handler:async(ctx,args)=>{
 const user=await requirePermission(ctx,"reverse_journal_entries"),original=await ctx.db.get(args.entryId),reason=normalizeText(args.reason),reversalDate=assertIsoDate(args.reversalDate),requestId=normalizeRequestId(args.requestId);
 if(!original||original.sourceType==="reversal"||!reason)throw new ConvexError("القيد غير قابل للعكس"); scopedBranch(user,original.branchId);
 const lines=await ctx.db.query("journalLines").withIndex("by_entry",q=>q.eq("entryId",original._id)).collect();
 const request={branchId:original.branchId,date:reversalDate,memo:`عكس ${original.entryNumber}: ${reason}`,lines:lines.map(l=>({accountId:l.accountId,debit:l.credit,credit:l.debit,description:`عكس: ${l.description??original.memo}`})),requestId,sourceType:"reversal" as const,originalEntryId:original._id,reversalReason:reason};
 const existing=await ctx.db.query("journalEntries").withIndex("by_original",q=>q.eq("originalEntryId",original._id)).unique();
 if(existing){const expected=fingerprint({branchId:String(request.branchId),date:request.date,memo:normalizeText(request.memo),lines:request.lines.map(l=>({accountId:String(l.accountId),debit:l.debit,credit:l.credit,description:normalizeText(l.description)})),sourceType:request.sourceType,originalEntryId:String(original._id),reversalReason:reason});if(existing.requestId!==requestId||existing.requestFingerprint!==expected)throw new ConvexError("بيانات العكس مختلفة");return existing;}
 if(original.status!=="posted")throw new ConvexError("القيد غير قابل للعكس");
 const reversal=await postJournal(ctx,user,request);await ctx.db.patch(original._id,{status:"reversed",reversalEntryId:reversal._id,reversalReason:reason,reversalDate,reversedAt:Date.now(),reversedBy:user.userId});return reversal;
}});
export const entriesPaginated=query({args:{branchId:v.optional(v.id("branches")),from:v.string(),to:v.string(),paginationOpts:paginationOptsValidator},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"view_general_ledger"),branchId=scopedBranch(user,args.branchId);const page=await ctx.db.query("journalEntries").withIndex("by_branch_date",q=>q.eq("branchId",branchId).gte("entryDate",args.from).lte("entryDate",args.to)).order("desc").paginate(args.paginationOpts);return {...page,page:page.page.map(e=>({_id:e._id,entryNumber:e.entryNumber,date:e.entryDate,memo:e.memo,totalDebit:e.totalDebit,totalCredit:e.totalCredit,lineCount:e.lineCount,status:e.status,sourceType:e.sourceType}))};}});
async function profileName(ctx:QueryCtx,postedBy:string){const byUser=await ctx.db.query("userProfiles").withIndex("by_user",q=>q.eq("userId",postedBy)).unique();if(byUser)return byUser.name;const byToken=await ctx.db.query("userProfiles").withIndex("by_token",q=>q.eq("tokenIdentifier",postedBy)).unique();return byToken?.name??"مستخدم غير معروف";}
async function details(ctx:QueryCtx,entryId:Id<"journalEntries">,print=false){const user=await requirePermission(ctx,print?"print_general_ledger":"view_general_ledger"),e=await ctx.db.get(entryId);if(!e)throw new ConvexError("القيد غير موجود");if(scopedBranch(user,e.branchId)!==e.branchId)throw new ConvexError("لا تملك صلاحية الوصول إلى هذا الفرع");const lines=await ctx.db.query("journalLines").withIndex("by_entry",q=>q.eq("entryId",e._id)).collect(),branch=await ctx.db.get(e.branchId),original=e.originalEntryId?await ctx.db.get(e.originalEntryId):null,reversal=e.reversalEntryId?await ctx.db.get(e.reversalEntryId):null;return {entryNumber:e.entryNumber,date:e.entryDate,memo:e.memo,branchName:branch?.name??"فرع غير معروف",employeeName:await profileName(ctx,e.postedBy),totalDebit:e.totalDebit,totalCredit:e.totalCredit,lineCount:e.lineCount,status:e.status,sourceType:e.sourceType,...(original?{originalEntryNumber:original.entryNumber}:{}),...(reversal?{reversalEntryNumber:reversal.entryNumber}:{}),...(e.reversalReason?{reversalReason:e.reversalReason}:{}),...(e.reversalDate?{reversalDate:e.reversalDate}:{}),lines:lines.map(l=>({lineNumber:l.lineNumber,accountCode:l.accountCodeSnapshot,accountName:l.accountNameSnapshot,normalSide:l.normalSideSnapshot,debit:l.debit,credit:l.credit,description:l.description??""}))};}
export const entryDetails=query({args:{entryId:v.id("journalEntries")},handler:(ctx,args)=>details(ctx,args.entryId)});
export const entryForPrint=query({args:{entryId:v.id("journalEntries")},handler:(ctx,args)=>details(ctx,args.entryId,true)});
function nextIsoDate(date:string){const value=new Date(`${date}T00:00:00Z`);value.setUTCDate(value.getUTCDate()+1);return value.toISOString().slice(0,10);}
export const accountLedgerPaginated=query({args:{branchId:v.optional(v.id("branches")),accountId:v.id("chartOfAccounts"),from:v.string(),to:v.string(),paginationOpts:paginationOptsValidator},handler:async(ctx,args)=>{
 const user=await requirePermission(ctx,"view_general_ledger"),branchId=scopedBranch(user,args.branchId),account=await ctx.db.get(args.accountId);
 if(!account)throw new ConvexError("الحساب غير موجود");
 const from=assertIsoDate(args.from),to=assertIsoDate(args.to);if(from>to)throw new ConvexError("نطاق التاريخ غير صالح");
 const signed=(debit:number,credit:number)=>account.normalSide==="debit"?debit-credit:credit-debit;
 const sumLines=(rows:Array<{debit:number;credit:number}>)=>rows.reduce((sum,row)=>sum+signed(row.debit,row.credit),0);
 const sumPeriods=(rows:Array<{debitTotal:number;creditTotal:number}>)=>rows.reduce((sum,row)=>sum+signed(row.debitTotal,row.creditTotal),0);
 const fromPeriod=periodKeyOf(from);
 const priorPeriods=await ctx.db.query("generalLedgerPeriodBalances").withIndex("by_account_branch_period",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).lt("periodKey",fromPeriod)).collect();
 const priorPartial=await ctx.db.query("journalLines").withIndex("by_account_branch_date_number_line",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).gte("entryDate",`${fromPeriod}-01`).lt("entryDate",from)).collect();
 const openingBalance=sumPeriods(priorPeriods)+sumLines(priorPartial);
 const result=await ctx.db.query("journalLines").withIndex("by_account_branch_date_number_line",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).gte("entryDate",from).lte("entryDate",to)).order("asc").paginate(args.paginationOpts);
 const movementBeforeDate=async(toExclusive:string)=>{
  if(toExclusive<=from)return 0;
  const endPeriod=periodKeyOf(toExclusive);
  if(endPeriod===fromPeriod){
   return sumLines(await ctx.db.query("journalLines").withIndex("by_account_branch_date_number_line",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).gte("entryDate",from).lt("entryDate",toExclusive)).collect());
  }
  const firstPartial=await ctx.db.query("journalLines").withIndex("by_account_branch_date_number_line",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).gte("entryDate",from).lte("entryDate",`${fromPeriod}-31`)).collect();
  const middlePeriods=await ctx.db.query("generalLedgerPeriodBalances").withIndex("by_account_branch_period",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).gt("periodKey",fromPeriod).lt("periodKey",endPeriod)).collect();
  const lastPartial=await ctx.db.query("journalLines").withIndex("by_account_branch_date_number_line",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).gte("entryDate",`${endPeriod}-01`).lt("entryDate",toExclusive)).collect();
  return sumLines(firstPartial)+sumPeriods(middlePeriods)+sumLines(lastPartial);
 };
 let balanceBeforePage=openingBalance;
 if(result.page.length){
  const first=result.page[0];
  const earlierSameDay=await ctx.db.query("journalLines").withIndex("by_account_branch_date_number_line",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).eq("entryDate",first.entryDate).lt("entryNumber",first.entryNumber)).collect();
  const earlierSameEntry=await ctx.db.query("journalLines").withIndex("by_account_branch_date_number_line",q=>q.eq("accountId",args.accountId).eq("branchId",branchId).eq("entryDate",first.entryDate).eq("entryNumber",first.entryNumber).lt("lineNumber",first.lineNumber)).collect();
  balanceBeforePage+=await movementBeforeDate(first.entryDate)+sumLines(earlierSameDay)+sumLines(earlierSameEntry);
 }else balanceBeforePage+=await movementBeforeDate(nextIsoDate(to));
 let runningBalance=balanceBeforePage;const page=[];
 for(const line of result.page){runningBalance+=signed(line.debit,line.credit);const entry=await ctx.db.get(line.entryId);page.push({entryNumber:line.entryNumber,date:line.entryDate,lineNumber:line.lineNumber,description:line.description??"",debit:line.debit,credit:line.credit,runningBalance,status:entry?.status??"posted",sourceType:entry?.sourceType??"manual"});}
 return {...result,page,openingBalance,balanceBeforePage};
}});
async function trial(ctx:QueryCtx,branchId:Id<"branches">,periodKey:string){const prior=await ctx.db.query("generalLedgerPeriodBalances").withIndex("by_branch_period",q=>q.eq("branchId",branchId).lt("periodKey",periodKey)).collect(),current=await ctx.db.query("generalLedgerPeriodBalances").withIndex("by_branch_period",q=>q.eq("branchId",branchId).eq("periodKey",periodKey)).collect(),byAccount=new Map<string,{accountId:Id<"chartOfAccounts">;opening:number;debit:number;credit:number}>();for(const b of prior){const key=String(b.accountId),row=byAccount.get(key)??{accountId:b.accountId,opening:0,debit:0,credit:0};row.opening+=b.netDebitMovement;byAccount.set(key,row);}for(const b of current){const key=String(b.accountId),row=byAccount.get(key)??{accountId:b.accountId,opening:0,debit:0,credit:0};row.debit+=b.debitTotal;row.credit+=b.creditTotal;byAccount.set(key,row);}const rows=[];for(const b of byAccount.values()){const a=await ctx.db.get(b.accountId);if(a){const closing=b.opening+b.debit-b.credit;rows.push({code:a.code,nameAr:a.nameAr,normalSide:a.normalSide,openingDebit:Math.max(b.opening,0),openingCredit:Math.max(-b.opening,0),periodDebit:b.debit,periodCredit:b.credit,closingDebit:Math.max(closing,0),closingCredit:Math.max(-closing,0)});}}return rows.sort((a,b)=>a.code.localeCompare(b.code));}
export const trialBalance=query({args:{branchId:v.optional(v.id("branches")),periodKey:v.string()},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"view_general_ledger");return trial(ctx,scopedBranch(user,args.branchId),args.periodKey);}});
export const trialBalanceForPrint=query({args:{branchId:v.optional(v.id("branches")),periodKey:v.string()},handler:async(ctx,args)=>{const user=await requirePermission(ctx,"print_general_ledger");return trial(ctx,scopedBranch(user,args.branchId),args.periodKey);}});
