import { ConvexError, v } from "convex/values";
import { mutation, query } from "./_generated/server";
import type { MutationCtx, QueryCtx } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import { PAYMENT_METHOD_PRESETS, paymentMethodAllowsAccount, type PaymentMethodDefinition, type PaymentMethodKind } from "../shared/paymentMethods.ts";
import { assertBranchAccess, logAction, requireAuth, requirePermission } from "./lib/auth.ts";
import { assertFinancialAccountBranch, requireActiveFinancialAccount } from "./lib/finance.ts";
import { requireActiveBranch } from "./lib/references.ts";

const methodKind = v.union(v.literal("cash"), v.literal("wallet"), v.literal("bank"), v.literal("gateway"), v.literal("credit"), v.literal("other"));
const FINANCIAL_ACCOUNT_TYPES = new Set(["cash", "instapay", "vodafone_cash", "fawry_clearing", "paymob_clearing", "card_clearing", "cod_clearing", "bank", "other"]);
function normalizeCode(value: string) { const code = value.trim().toLowerCase(); if (!/^[a-z][a-z0-9_-]{1,49}$/.test(code)) throw new ConvexError("رمز طريقة الدفع يجب أن يبدأ بحرف إنجليزي ويحتوي على حروف أو أرقام فقط"); return code; }
function normalizeName(value: string) { const name = value.trim().replace(/\s+/g, " "); if (name.length < 2 || name.length > 80) throw new ConvexError("اسم طريقة الدفع يجب أن يكون بين حرفين و80 حرفًا"); return name; }
function publicDefinition(document: Doc<"paymentMethods">): PaymentMethodDefinition & { _id: Id<"paymentMethods"> } { return { _id: document._id, code: document.code, name: document.name, kind: document.kind, requiresAccount: document.requiresAccount, allowedAccountTypes: document.allowedAccountTypes, isSystem: document.isSystem, isActive: document.isActive, sortOrder: document.sortOrder }; }
async function mergedMethods(ctx: QueryCtx | MutationCtx) { const stored = await ctx.db.query("paymentMethods").collect(); const storedByCode = new Map(stored.map((method) => [method.code, method])); const presets = PAYMENT_METHOD_PRESETS.map((preset) => { const override = storedByCode.get(preset.code); return override ? publicDefinition(override) : preset; }); const custom = stored.filter((method) => !PAYMENT_METHOD_PRESETS.some((preset) => preset.code === method.code)).map(publicDefinition); return [...presets, ...custom].sort((left, right) => left.sortOrder - right.sortOrder || left.name.localeCompare(right.name)); }
export async function resolvePaymentMethod(ctx: QueryCtx | MutationCtx, rawCode: string) { const code = normalizeCode(rawCode); const stored = await ctx.db.query("paymentMethods").withIndex("by_code", (q) => q.eq("code", code)).unique(); const method = stored ? publicDefinition(stored) : PAYMENT_METHOD_PRESETS.find((preset) => preset.code === code); if (!method || !method.isActive) throw new ConvexError("طريقة الدفع غير موجودة أو غير نشطة"); return method; }
export function assertPaymentMethodAccount(method: PaymentMethodDefinition, account: Doc<"financialAccounts">) { if (!paymentMethodAllowsAccount(method, account.type)) throw new ConvexError(`الحساب «${account.name}» غير مناسب لطريقة الدفع «${method.name}»`); }

export const listActive = query({ args: {}, handler: async (ctx) => { await requireAuth(ctx); return (await mergedMethods(ctx)).filter((method) => method.isActive); } });
export const listForSettings = query({ args: {}, handler: async (ctx) => { await requirePermission(ctx, "manage_settings"); return await mergedMethods(ctx); } });
export const configuration = query({ args: {}, handler: async (ctx) => { await requirePermission(ctx, "manage_settings"); const [methods, branches, accounts, defaults] = await Promise.all([mergedMethods(ctx), ctx.db.query("branches").collect(), ctx.db.query("financialAccounts").collect(), ctx.db.query("paymentAccountDefaults").collect()]); return { methods, branches: branches.filter((branch) => branch.isActive).map((branch) => ({ _id: branch._id, name: branch.name })), accounts: accounts.filter((account) => account.isActive).map((account) => ({ _id: account._id, name: account.name, type: account.type, branchId: account.branchId })), defaults: defaults.map((item) => ({ paymentMethodCode: item.paymentMethodCode, branchId: item.branchId, accountId: item.accountId })) }; } });
export const defaultsForBranch = query({ args: { branchId: v.optional(v.id("branches")) }, handler: async (ctx, args) => { const user = await requirePermission(ctx, "record_collections"); const branchId = user.role === "admin" || user.role === "accountant" ? args.branchId ?? user.branchId : user.branchId; if (!branchId) return []; assertBranchAccess(user, { branchId }); const defaults = await ctx.db.query("paymentAccountDefaults").withIndex("by_branch", (q) => q.eq("branchId", branchId)).collect(); const rows = []; for (const item of defaults) { const account = await ctx.db.get(item.accountId); if (account?.isActive) rows.push({ paymentMethodCode: item.paymentMethodCode, accountId: item.accountId, accountName: account.name }); } return rows; } });

export const upsert = mutation({ args: { code: v.string(), name: v.string(), kind: methodKind, requiresAccount: v.boolean(), allowedAccountTypes: v.array(v.string()), isActive: v.boolean(), sortOrder: v.number() }, handler: async (ctx, args) => {
  const user = await requirePermission(ctx, "manage_settings"); const code = normalizeCode(args.code); const name = normalizeName(args.name);
  if (!Number.isInteger(args.sortOrder) || args.sortOrder < 0 || args.sortOrder > 10_000) throw new ConvexError("ترتيب طريقة الدفع غير صالح");
  if (args.kind === "credit" && args.requiresAccount) throw new ConvexError("الدفع الآجل لا يرتبط بخزنة");
  if (args.kind !== "credit" && !args.requiresAccount) throw new ConvexError("طريقة الدفع المسددة يجب أن ترتبط بخزنة أو حساب");
  const allowedAccountTypes = [...new Set(args.allowedAccountTypes.map((value) => value.trim()).filter(Boolean))];
  if (allowedAccountTypes.some((value) => !FINANCIAL_ACCOUNT_TYPES.has(value))) throw new ConvexError("نوع الحساب المحدد غير مدعوم");
  if (!args.requiresAccount && allowedAccountTypes.length > 0) throw new ConvexError("طريقة الدفع الآجل لا تقبل أنواع حسابات مالية");
  if (args.requiresAccount && allowedAccountTypes.length === 0) throw new ConvexError("حدد نوع حساب واحدًا على الأقل لطريقة الدفع");
  const existing = await ctx.db.query("paymentMethods").withIndex("by_code", (q) => q.eq("code", code)).unique(); const preset = PAYMENT_METHOD_PRESETS.find((method) => method.code === code); const now = Date.now(); const values = { code, name, kind: args.kind as PaymentMethodKind, requiresAccount: args.requiresAccount, allowedAccountTypes, isSystem: Boolean(preset), isActive: args.isActive, sortOrder: args.sortOrder, updatedAt: now, updatedBy: user.userId };
  const id = existing ? (await ctx.db.patch(existing._id, values), existing._id) : await ctx.db.insert("paymentMethods", { ...values, createdAt: now, createdBy: user.userId });
  await logAction(ctx, user, { action: existing ? "update" : "create", module: "settings", recordId: String(id), recordLabel: name, details: `${existing ? "تعديل" : "إضافة"} طريقة الدفع ${name}`, after: { code, name, kind: args.kind, isActive: args.isActive } }); return id;
} });

export const setDefaultAccount = mutation({ args: { paymentMethodCode: v.string(), branchId: v.id("branches"), accountId: v.id("financialAccounts") }, handler: async (ctx, args) => { const user = await requirePermission(ctx, "manage_settings"); const method = await resolvePaymentMethod(ctx, args.paymentMethodCode); if (!method.requiresAccount) throw new ConvexError("طريقة الدفع الآجلة لا تحتاج حسابًا افتراضيًا"); await requireActiveBranch(ctx, args.branchId); const account = await requireActiveFinancialAccount(ctx, args.accountId); assertFinancialAccountBranch(account, args.branchId); assertPaymentMethodAccount(method, account); const key = `${args.branchId}:${method.code}`; const existing = await ctx.db.query("paymentAccountDefaults").withIndex("by_key", (q) => q.eq("key", key)).unique(); const values = { key, paymentMethodCode: method.code, branchId: args.branchId, accountId: account._id, updatedAt: Date.now(), updatedBy: user.userId }; const id = existing ? (await ctx.db.patch(existing._id, values), existing._id) : await ctx.db.insert("paymentAccountDefaults", values); await logAction(ctx, user, { action: existing ? "update" : "create", module: "settings", recordId: String(id), recordLabel: `${method.name} — ${account.name}`, details: `تعيين ${account.name} حسابًا افتراضيًا لطريقة ${method.name}`, branchId: args.branchId, after: { paymentMethodCode: method.code, accountId: String(account._id) } }); return id; } });
