import { randomUUID } from 'node:crypto'
import type { PoolClient } from 'pg'

export type AuditJsonPrimitive = string | number | boolean | null
export type AuditJsonValue =
  | AuditJsonPrimitive
  | AuditJsonValue[]
  | { [key: string]: AuditJsonValue }

export interface CreateAuditLogInput {
  companyId: string
  branchId?: string | null
  userId?: string | null
  action: string
  entityType: string
  entityId: string
  reason?: string | null
  before?: AuditJsonValue | null
  after?: AuditJsonValue | null
}

export interface AuditLogRecord {
  id: string
  companyId: string
  branchId: string | null
  userId: string | null
  action: string
  entityType: string
  entityId: string
  reason: string | null
  before: AuditJsonValue | null
  after: AuditJsonValue | null
  createdAt: Date
}

interface StoredAuditLogRow {
  id: string
  company_id: string
  branch_id: string | null
  user_id: string | null
  action: string
  entity_type: string
  entity_id: string
  reason: string | null
  before_json: AuditJsonValue | null
  after_json: AuditJsonValue | null
  created_at: Date
}

function requireNonBlank(name: string, value: string): void {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new TypeError(`${name} must be a non-empty string`)
  }
}

function validateNullableNonBlank(
  name: string,
  value: string | null | undefined,
): void {
  if (value === null || value === undefined) return
  requireNonBlank(name, value)
}

function validateAuditJsonValue(
  value: unknown,
  path: string,
  ancestors: WeakSet<object>,
): asserts value is AuditJsonValue {
  if (value === null) return

  if (
    typeof value === 'string' ||
    typeof value === 'boolean'
  ) {
    return
  }

  if (typeof value === 'number') {
    if (!Number.isFinite(value)) {
      throw new TypeError(
        `Audit snapshot contains a non-finite number at ${path}`,
      )
    }
    return
  }

  if (typeof value !== 'object') {
    throw new TypeError(
      `Audit snapshot contains unsupported ${typeof value} at ${path}`,
    )
  }

  if (ancestors.has(value)) {
    throw new TypeError(`Audit snapshot contains a cycle at ${path}`)
  }

  const isArray = Array.isArray(value)
  const prototype = Object.getPrototypeOf(value)
  if (!isArray && prototype !== Object.prototype && prototype !== null) {
    throw new TypeError(
      `Audit snapshot must contain only JSON-compatible plain objects at ${path}`,
    )
  }

  if (Object.getOwnPropertySymbols(value).length > 0) {
    throw new TypeError(
      `Audit snapshot cannot contain symbol keys at ${path}`,
    )
  }

  ancestors.add(value)
  try {
    if (isArray) {
      for (let index = 0; index < value.length; index += 1) {
        if (!(index in value)) {
          throw new TypeError(
            `Audit snapshot cannot contain sparse arrays at ${path}[${index}]`,
          )
        }
        validateAuditJsonValue(
          value[index],
          `${path}[${index}]`,
          ancestors,
        )
      }
      return
    }

    for (const [key, child] of Object.entries(
      value as Record<string, unknown>,
    )) {
      validateAuditJsonValue(child, `${path}.${key}`, ancestors)
    }
  } finally {
    ancestors.delete(value)
  }
}

export function serializeAuditSnapshot(
  value: AuditJsonValue | null | undefined,
): string | null {
  if (value === null || value === undefined) return null
  validateAuditJsonValue(value, '$', new WeakSet<object>())
  return JSON.stringify(value)
}

function validateInput(input: CreateAuditLogInput): void {
  requireNonBlank('Audit companyId', input.companyId)
  validateNullableNonBlank('Audit branchId', input.branchId)
  validateNullableNonBlank('Audit userId', input.userId)
  requireNonBlank('Audit action', input.action)
  requireNonBlank('Audit entityType', input.entityType)
  requireNonBlank('Audit entityId', input.entityId)
  validateNullableNonBlank('Audit reason', input.reason)
}

function mapAuditLog(row: StoredAuditLogRow): AuditLogRecord {
  return {
    id: row.id,
    companyId: row.company_id,
    branchId: row.branch_id,
    userId: row.user_id,
    action: row.action,
    entityType: row.entity_type,
    entityId: row.entity_id,
    reason: row.reason,
    before: row.before_json,
    after: row.after_json,
    createdAt: row.created_at,
  }
}

/**
 * Appends one immutable audit record inside an already-open business transaction.
 *
 * Sensitive commands must call this with the same PoolClient used for their
 * business effects so success commits both and failure rolls both back.
 * created_at is generated by PostgreSQL and cannot be backdated by the caller.
 */
export class AuditService {
  async record(
    client: PoolClient,
    input: CreateAuditLogInput,
  ): Promise<AuditLogRecord> {
    validateInput(input)

    const beforeJson = serializeAuditSnapshot(input.before)
    const afterJson = serializeAuditSnapshot(input.after)
    const id = randomUUID()

    const result = await client.query<StoredAuditLogRow>(
      `INSERT INTO audit_logs
        (id,company_id,branch_id,user_id,action,entity_type,entity_id,reason,
         before_json,after_json,created_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,clock_timestamp())
       RETURNING
         id,
         company_id,
         branch_id,
         user_id,
         action,
         entity_type,
         entity_id,
         reason,
         before_json,
         after_json,
         created_at`,
      [
        id,
        input.companyId,
        input.branchId ?? null,
        input.userId ?? null,
        input.action,
        input.entityType,
        input.entityId,
        input.reason ?? null,
        beforeJson,
        afterJson,
      ],
    )

    const row = result.rows[0]
    if (!row) {
      throw new Error('Audit record invariant failed: no row returned')
    }

    return mapAuditLog(row)
  }
}
