import test, { after, before } from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs"; import { symlink, unlink } from "node:fs/promises"; import { resolve } from "node:path";
import { convexTest } from "convex-test"; import schema from "../convex/schema.ts"; import { api } from "../convex/_generated/api.js";
import { allocateProportionally, calculateInventoryChange, roundAverageCost } from "../shared/inventoryRules.ts";
const links = [["convex/_generated/server","server.js"],["convex/lib/auth","auth.ts"],["convex/lib/inventory","inventory.ts"],["convex/lib/documentNumbers","documentNumbers.ts"],["convex/lib/permissions","permissions.ts"],["convex/lib/references","references.ts"],["convex/lib/finance","finance.ts"],["convex/lib/productVisibility","productVisibility.ts"],["shared/businessRules","businessRules.ts"],["shared/inventoryRules","inventoryRules.ts"],["shared/productRules","productRules.ts"]] as const;
before(async()=>{for(const [path,target] of links) if(!existsSync(resolve(path))) await symlink(target,resolve(path));}); after(async()=>{for(const [path] of links) if(existsSync(resolve(path))) await unlink(resolve(path));});
const modules={"../convex/_generated/api.js":()=>import("../convex/_generated/api.js"),"../convex/_generated/server.js":()=>import("../convex/_generated/server.js"),"../convex/products.ts":()=>import("../convex/products.ts"),"../convex/shipments.ts":()=>import("../convex/shipments.ts"),"../convex/invoices.ts":()=>import("../convex/invoices.ts"),"../convex/salesReturns.ts":()=>import("../convex/salesReturns.ts")};
async function setup(){const raw=convexTest(schema,modules);const ids=await raw.run(async ctx=>{const branchId=await ctx.db.insert("branches",{name:"فرع",address:"عنوان",isActive:true});await ctx.db.insert("userProfiles",{userId:"admin",tokenIdentifier:"admin",name:"مدير",role:"admin",branchId,permissions:[],isActive:true});await ctx.db.insert("settings",{storeName:"متجر",storeType:"retail",primaryColor:"#000",secondaryColor:"#fff",currency:"EGP",taxRate:0});await ctx.db.insert("financeSettings",{isInitialized:true,cutoverDate:"2026-07-01",defaultClearingDelayDays:0,updatedAt:Date.now()});return {branchId};});return {raw,t:raw.withIdentity({subject:"admin",tokenIdentifier:"admin"}),...ids};}
async function product(e:Awaited<ReturnType<typeof setup>>,cost=10,stock=10){return e.t.mutation(api.products.create,{name:"منتج",sku:crypto.randomUUID(),costPrice:cost,sellPrice:30,stock,minStock:0,unit:"قطعة",branchId:e.branchId});}
test("COGS-01 pure weighted-average rule preserves four-decimal precision",()=>{const r=calculateInventoryChange(3,10,30,2,11.1111);assert.equal(r.stockAfter,5);assert.equal(r.inventoryValueAfter,52.22);assert.equal(r.averageCostAfter,roundAverageCost(52.22/5));});
test("COGS-02 shipping allocation is exact and puts rounding remainder on last eligible line",()=>assert.deepEqual(allocateProportionally(1,[1,1,1]),[0.33,0.33,0.34]));
test("COGS-03 opening balance records stock and inventory value",async()=>{const e=await setup(),id=await product(e,12.5,4),p=await e.raw.run(ctx=>ctx.db.get(id));assert.equal(p?.inventoryValue,50);assert.equal((await e.raw.run(ctx=>ctx.db.query("inventoryMovements").collect())).length,1);});
test("COGS-04 shipment receipt applies landed moving average and cannot arrive twice",async()=>{const e=await setup(),id=await product(e);const sh=await e.t.mutation(api.shipments.create,{supplierName:"مورد",items:[{productId:id,productName:"x",quantity:10,unitCost:20,total:1}],totalCost:1,shippingCost:10,grandTotal:1,branchId:e.branchId});await e.t.mutation(api.shipments.updateStatus,{id:sh,status:"in_transit"});await e.t.mutation(api.shipments.updateStatus,{id:sh,status:"arrived"});const p=await e.raw.run(ctx=>ctx.db.get(id));assert.equal(p?.stock,20);assert.equal(p?.inventoryValue,310);assert.equal(p?.costPrice,15.5);await assert.rejects(e.t.mutation(api.shipments.updateStatus,{id:sh,status:"arrived"}),/لا يمكن/);});
test("COGS-05 sale freezes COGS and lowers value without changing average",async()=>{const e=await setup(),pid=await product(e,10,10);const cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:"2",balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"نقدي",items:[{productId:pid,productName:"مزيف",quantity:2,unitPrice:1,discount:0,total:1}],subtotal:1,discount:0,tax:0,total:1,creationRequestId:"invoice",branchId:e.branchId});const result=await e.raw.run(async ctx=>({p:await ctx.db.get(pid),i:await ctx.db.get(iid)}));assert.equal(result.p?.inventoryValue,80);assert.equal(result.p?.costPrice,10);assert.equal(result.i?.items[0].unitCost,10);assert.equal(result.i?.cogsTotal,20);assert.equal(result.i?.items[0].unitPrice,30);});
test("COGS-06 legacy invoice cannot create an automatic stock return",async()=>{const e=await setup(),pid=await product(e),iid=await e.raw.run(ctx=>ctx.db.insert("invoices",{invoiceNumber:"OLD",customerName:"قديم",items:[{productId:pid,productName:"منتج",quantity:1,unitPrice:30,discount:0,total:30}],subtotal:30,discount:0,tax:0,total:30,paid:0,remaining:30,paymentMethod:"unpaid",status:"unpaid",branchId:e.branchId,type:"sale"}));await assert.rejects(e.t.mutation(api.salesReturns.create,{invoiceId:iid,items:[{productId:pid,quantity:1}],reason:"مرتجع",date:"2026-07-21",requestId:"legacy"}),/قديمة بلا تكلفة تاريخية/);});
test("COGS-07 partial return restores historical value and is idempotent",async()=>{const e=await setup(),pid=await product(e),cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:"1",balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"x",items:[{productId:pid,productName:"x",quantity:3,unitPrice:1,discount:0,total:1}],subtotal:1,discount:0,tax:0,total:1,creationRequestId:"i",branchId:e.branchId});const args={invoiceId:iid,items:[{productId:pid,quantity:1}],reason:"إرجاع",date:"2026-07-21",requestId:"same"};const one=await e.t.mutation(api.salesReturns.create,args),two=await e.t.mutation(api.salesReturns.create,args);assert.equal(one,two);const state=await e.raw.run(async ctx=>({p:await ctx.db.get(pid),notes:await ctx.db.query("salesReturns").collect()}));assert.equal(state.p?.stock,8);assert.equal(state.p?.inventoryValue,80);assert.equal(state.notes.length,1);});
test("COGS-08 cumulative full return equals original net line despite rounding",async()=>{const allocations=allocateProportionally(100,[1,1,1]);assert.equal(allocations.reduce((a,b)=>a+b,0),100);});
