import test from "node:test";import assert from "node:assert/strict";import { readFileSync } from "node:fs";
const panel=readFileSync("src/components/SalesReturnsPanel.tsx","utf8"), invoices=readFileSync("src/components/InvoicesPage.tsx","utf8"), backend=readFileSync("convex/salesReturns.ts","utf8");
test("UI-01 uses limited eligible query",()=>assert.match(panel,/salesReturns\.eligibleInvoices/));
test("UI-02 shows returned and available quantities with max",()=>{assert.match(panel,/المرتجع سابقًا/);assert.match(panel,/max=\{item\.availableQuantity\}/);});
test("UI-03 request id remains stable while retrying",()=>assert.match(panel,/requestId: requestId\.current/));
test("UI-04 busy guard prevents double submit",()=>assert.match(panel,/if \(!invoice \|\| busy\) return/));
test("UI-05 return statuses have distinct labels",()=>["partial_return","paid_returned_partial","returned"].forEach(x=>assert.match(invoices,new RegExp(x))));
test("UI-06 invoice rows display the net total without obsolete summary cards",()=>{assert.match(invoices,/formatCurrency\(inv\.netTotal \?\? inv\.total\)/);assert.doesNotMatch(invoices,/s \+ \(i\.netTotal \?\? i\.total\)/);});
test("UI-07 create print and reverse are permission guarded",()=>{assert.match(panel,/canCreate && canReverse/);assert.match(panel,/canPrint &&/);});
test("UI-08 print query and modal are guarded",()=>assert.match(panel,/canPrint && printId/));
test("UI-09 eligible response never exposes COGS",()=>{const body=backend.slice(backend.indexOf("eligibleInvoices"),backend.indexOf("export const create"));assert.doesNotMatch(body,/unitCost|costTotal|cogsTotal/i);});
test("UI-10 partial returns expose collection when a balance remains",()=>assert.match(invoices,/inv\.status !== "returned" && inv\.remaining > 0/));
test("UI-11 partially returned invoices retain financial refund action",()=>assert.match(invoices,/inv\.status !== "returned" && inv\.paid > 0/));
