import test, { after, before } from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs"; import { symlink, unlink } from "node:fs/promises"; import { resolve } from "node:path";
import { convexTest } from "convex-test"; import schema from "../convex/schema.ts"; import { api } from "../convex/_generated/api.js";

const links = [["convex/_generated/server","server.js"],["convex/lib/auth","auth.ts"],["convex/lib/inventory","inventory.ts"],["convex/lib/documentNumbers","documentNumbers.ts"],["convex/lib/permissions","permissions.ts"],["convex/lib/references","references.ts"],["convex/lib/finance","finance.ts"],["convex/lib/productVisibility","productVisibility.ts"],["convex/lib/supplierLedger","supplierLedger.ts"],["shared/businessRules","businessRules.ts"],["shared/inventoryRules","inventoryRules.ts"],["shared/productRules","productRules.ts"]] as const;
before(async()=>{for(const [path,target] of links) if(!existsSync(resolve(path))) await symlink(target,resolve(path));}); after(async()=>{for(const [path] of links) if(existsSync(resolve(path))) await unlink(resolve(path));});
const modules={"../convex/_generated/api.js":()=>import("../convex/_generated/api.js"),"../convex/_generated/server.js":()=>import("../convex/_generated/server.js"),"../convex/products.ts":()=>import("../convex/products.ts"),"../convex/shipments.ts":()=>import("../convex/shipments.ts"),"../convex/invoices.ts":()=>import("../convex/invoices.ts"),"../convex/salesReturns.ts":()=>import("../convex/salesReturns.ts")};
async function setup(){const raw=convexTest(schema,modules);const ids=await raw.run(async ctx=>{const branchId=await ctx.db.insert("branches",{name:"فرع",address:"عنوان",isActive:true});await ctx.db.insert("userProfiles",{userId:"admin",tokenIdentifier:"admin",name:"مدير",role:"admin",branchId,permissions:[],isActive:true});await ctx.db.insert("settings",{storeName:"متجر",storeType:"retail",primaryColor:"#000",secondaryColor:"#fff",currency:"EGP",taxRate:0});await ctx.db.insert("financeSettings",{isInitialized:true,cutoverDate:"2026-07-01",defaultClearingDelayDays:0,updatedAt:Date.now()});const supplierId=await ctx.db.insert("suppliers",{name:"مورد",phone:"1",balance:0,isActive:true});return {branchId,supplierId};});return {raw,t:raw.withIdentity({subject:"admin",tokenIdentifier:"admin"}),...ids};}
async function product(e:Awaited<ReturnType<typeof setup>>,cost=10,stock=10){return e.t.mutation(api.products.create,{name:"منتج",sku:crypto.randomUUID(),costPrice:cost,sellPrice:30,stock,minStock:0,unit:"قطعة",branchId:e.branchId});}
test("COGS-01 opening balance records stock and inventory value",async()=>{const e=await setup(),id=await product(e,12.5,4),p=await e.raw.run(ctx=>ctx.db.get(id));assert.equal(p?.inventoryValue,50);assert.equal((await e.raw.run(ctx=>ctx.db.query("inventoryMovements").collect())).length,1);});
test("COGS-02 shipment receipt applies landed moving average and cannot arrive twice",async()=>{const e=await setup(),id=await product(e);const sh=await e.t.mutation(api.shipments.create,{supplierName:"مورد",supplierId:e.supplierId,items:[{productId:id,productName:"x",quantity:10,unitCost:20,total:1}],totalCost:1,shippingCost:10,grandTotal:1,branchId:e.branchId});await e.t.mutation(api.shipments.updateStatus,{id:sh,status:"in_transit"});await e.t.mutation(api.shipments.receive,{shipmentId:sh,receiptDate:"2026-07-21",requestId:"cogs-02",supplierFreightAmount:10});const p=await e.raw.run(ctx=>ctx.db.get(id));assert.equal(p?.stock,20);assert.equal(p?.inventoryValue,310);assert.equal(p?.costPrice,15.5);await assert.rejects(e.t.mutation(api.shipments.receive,{shipmentId:sh,receiptDate:"2026-07-21",requestId:"different",supplierFreightAmount:10}),/طلب مختلف/);});
test("COGS-03 sale freezes COGS and lowers value without changing average",async()=>{const e=await setup(),pid=await product(e,10,10);const cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:"2",balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"نقدي",items:[{productId:pid,productName:"مزيف",quantity:2,unitPrice:1,discount:0,total:1}],subtotal:1,discount:0,tax:0,total:1,creationRequestId:"invoice",branchId:e.branchId});const result=await e.raw.run(async ctx=>({p:await ctx.db.get(pid),i:await ctx.db.get(iid)}));assert.equal(result.p?.inventoryValue,80);assert.equal(result.p?.costPrice,10);assert.equal(result.i?.items[0].unitCost,10);assert.equal(result.i?.cogsTotal,20);assert.equal(result.i?.items[0].unitPrice,30);});
test("COGS-04 legacy invoice cannot create an automatic stock return",async()=>{const e=await setup(),pid=await product(e),iid=await e.raw.run(ctx=>ctx.db.insert("invoices",{invoiceNumber:"OLD",customerName:"قديم",items:[{productId:pid,productName:"منتج",quantity:1,unitPrice:30,discount:0,total:30}],subtotal:30,discount:0,tax:0,total:30,paid:0,remaining:30,paymentMethod:"unpaid",status:"unpaid",branchId:e.branchId,type:"sale"}));await assert.rejects(e.t.mutation(api.salesReturns.create,{invoiceId:iid,items:[{productId:pid,quantity:1}],reason:"مرتجع",date:"2026-07-21",requestId:"legacy"}),/قديمة بلا تكلفة تاريخية/);});
test("COGS-05 partial return restores historical value and is idempotent",async()=>{const e=await setup(),pid=await product(e),cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:"1",balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"x",items:[{productId:pid,productName:"x",quantity:3,unitPrice:1,discount:0,total:1}],subtotal:1,discount:0,tax:0,total:1,creationRequestId:"i",branchId:e.branchId});const args={invoiceId:iid,items:[{productId:pid,quantity:1}],reason:"إرجاع",date:"2026-07-21",requestId:"same"};const one=await e.t.mutation(api.salesReturns.create,args),two=await e.t.mutation(api.salesReturns.create,args);assert.equal(one,two);const state=await e.raw.run(async ctx=>({p:await ctx.db.get(pid),notes:await ctx.db.query("salesReturns").collect()}));assert.equal(state.p?.stock,8);assert.equal(state.p?.inventoryValue,80);assert.equal(state.notes.length,1);});


async function sold(e:Awaited<ReturnType<typeof setup>>, quantity=3, paid=0){const pid=await product(e,10,10);const cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:crypto.randomUUID(),balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"عميل",items:[{productId:pid,productName:"hostile",quantity,unitPrice:.01,discount:0,total:.01}],subtotal:.01,discount:0,tax:0,total:.01,creationRequestId:crypto.randomUUID(),branchId:e.branchId});return {pid,cid,iid};}
async function state(e:Awaited<ReturnType<typeof setup>>){return e.raw.run(async ctx=>({products:await ctx.db.query("products").collect(),invoices:await ctx.db.query("invoices").collect(),notes:await ctx.db.query("salesReturns").collect(),customers:await ctx.db.query("customers").collect(),transactions:await ctx.db.query("financialTransactions").collect(),movements:await ctx.db.query("inventoryMovements").collect()}));}

async function account(e:Awaited<ReturnType<typeof setup>>,balance=200,isActive=true,branchId=e.branchId){return e.raw.run(ctx=>ctx.db.insert("financialAccounts",{name:"خزينة",code:crypto.randomUUID(),uniqueKey:crypto.randomUUID(),type:"cash",branchId,isActive,currentBalance:balance,allowNegative:false,settlementDelayDays:0,createdAt:Date.now(),createdBy:"admin",updatedAt:Date.now()}));}
async function snapshot(e:Awaited<ReturnType<typeof setup>>){return e.raw.run(async ctx=>({products:await ctx.db.query("products").collect(),invoices:await ctx.db.query("invoices").collect(),notes:await ctx.db.query("salesReturns").collect(),customers:await ctx.db.query("customers").collect(),transactions:await ctx.db.query("financialTransactions").collect(),movements:await ctx.db.query("inventoryMovements").collect(),accounts:await ctx.db.query("financialAccounts").collect(),financialMovements:await ctx.db.query("financialMovements").collect()}));}
async function receive(e:Awaited<ReturnType<typeof setup>>,items:Array<{productId:any,quantity:number,unitCost:number}>,shippingCost=0){const id=await e.t.mutation(api.shipments.create,{supplierName:"مورد",supplierId:e.supplierId,items:items.map(x=>({...x,productName:"مزيف",total:0})),totalCost:0,shippingCost,grandTotal:0,branchId:e.branchId});await e.t.mutation(api.shipments.updateStatus,{id,status:"in_transit"});await e.t.mutation(api.shipments.receive,{shipmentId:id,receiptDate:"2026-07-21",requestId:crypto.randomUUID(),supplierFreightAmount:shippingCost});return id;}
async function returnOne(e:Awaited<ReturnType<typeof setup>>,x:Awaited<ReturnType<typeof sold>>,requestId=crypto.randomUUID(),extra={}){return e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"مرتجع",date:"2026-07-21",requestId,...extra});}

test("COGS-06 weighted average is persisted by receipt",async()=>{const e=await setup(),pid=await product(e,10,10);await receive(e,[{productId:pid,quantity:10,unitCost:20}]);const s=await snapshot(e),p=s.products[0],m=s.movements.at(-1)!;assert.deepEqual([p.stock,p.inventoryValue,p.costPrice],[20,300,15]);assert.deepEqual([m.quantityDelta,m.valueDelta,m.stockAfter],[10,200,20]);});
test("COGS-07 landed cost includes shipping",async()=>{const e=await setup(),pid=await product(e,10,10);await receive(e,[{productId:pid,quantity:10,unitCost:20}],40);const s=await snapshot(e);assert.equal(s.products[0].inventoryValue,340);assert.equal(s.movements.at(-1)?.valueDelta,240);});
test("COGS-08 shipping allocation survives rounding",async()=>{const e=await setup(),ids=[await product(e,0,1),await product(e,0,1),await product(e,0,1)];await receive(e,ids.map(productId=>({productId,quantity:1,unitCost:1})),1);const deltas=(await snapshot(e)).movements.filter(x=>x.type==="shipment_receipt").map(x=>Math.round((x.valueDelta-1)*100)/100);assert.deepEqual(deltas,[.33,.33,.34]);assert.equal(Math.round(deltas.reduce((a,b)=>a+b,0)*100)/100,1);});
test("COGS-09 duplicate receipt is rejected without effects",async()=>{const e=await setup(),pid=await product(e),id=await receive(e,[{productId:pid,quantity:2,unitCost:20}],2),before=await snapshot(e);await assert.rejects(e.t.mutation(api.shipments.receive,{shipmentId:id,receiptDate:"2026-07-21",requestId:"different",supplierFreightAmount:2}),/طلب مختلف/);const after=await snapshot(e);assert.deepEqual([after.products[0].stock,after.products[0].inventoryValue,after.movements.length],[before.products[0].stock,before.products[0].inventoryValue,before.movements.length]);});
test("COGS-10 sale reduces quantity and value without changing average",async()=>{const e=await setup(),x=await sold(e,2),s=await snapshot(e),m=s.movements.at(-1)!;assert.deepEqual([s.products[0].stock,s.products[0].inventoryValue,s.products[0].costPrice,m.valueDelta],[8,80,10,-20]);});
test("COGS-11 server freezes historical cost snapshot",async()=>{const e=await setup(),x=await sold(e,2),i=(await snapshot(e)).invoices[0];assert.deepEqual([i.items[0].unitCost,i.items[0].costTotal,i.cogsTotal],[10,20,20]);await e.raw.run(ctx=>ctx.db.patch(x.pid,{costPrice:99}));assert.equal((await snapshot(e)).invoices[0].items[0].unitCost,10);});
test("COGS-12 hostile client prices names and totals are ignored",async()=>{const e=await setup();await sold(e,2);const i=(await snapshot(e)).invoices[0];assert.deepEqual([i.customerName,i.items[0].productName,i.items[0].unitPrice,i.items[0].total,i.total],["عميل","منتج",30,60,60]);});
test("COGS-13 invoice query redacts costs without profit permission",async()=>{const e=await setup(),x=await sold(e);await e.raw.run(ctx=>ctx.db.insert("userProfiles",{userId:"viewer",tokenIdentifier:"viewer",name:"مشاهد",role:"viewer",branchId:e.branchId,permissions:["view_invoices"],isActive:true}));const q=await e.raw.withIdentity({subject:"viewer",tokenIdentifier:"viewer"}).query(api.invoices.get,{id:x.iid});assert.equal("cogsTotal" in q!,false);assert.equal("unitCost" in q!.items[0],false);assert.equal("costTotal" in q!.items[0],false);});
test("COGS-14 profit permission exposes historical cost",async()=>{const e=await setup(),x=await sold(e),q=await e.t.query(api.invoices.get,{id:x.iid});assert.deepEqual([q?.items[0].unitCost,q?.items[0].costTotal,q?.cogsTotal],[10,30,30]);});
test("COGS-15 cancellation restores stock value and customer",async()=>{const e=await setup(),x=await sold(e,2);await e.t.mutation(api.invoices.cancel,{id:x.iid,reason:"خطأ"});const s=await snapshot(e);assert.deepEqual([s.products[0].stock,s.products[0].inventoryValue,s.invoices[0].status,s.customers[0].balance,s.customers[0].totalPurchases],[10,100,"cancelled",0,0]);assert.equal(s.movements.at(-1)?.type,"sale_reversal");});
test("COGS-16 cancellation retry cannot duplicate reversal",async()=>{const e=await setup(),x=await sold(e,2);await e.t.mutation(api.invoices.cancel,{id:x.iid,reason:"خطأ"});const before=await snapshot(e);await assert.rejects(e.t.mutation(api.invoices.cancel,{id:x.iid,reason:"ثانية"}),/ملغاة بالفعل/);const after=await snapshot(e);assert.deepEqual([after.products[0].stock,after.movements.length,after.customers[0].balance],[before.products[0].stock,before.movements.length,before.customers[0].balance]);});
test("COGS-17 invoice edit reverses historical old lines and freezes new cost",async()=>{const e=await setup(),x=await sold(e,2);await e.raw.run(ctx=>ctx.db.patch(x.pid,{costPrice:15,inventoryValue:120}));await e.t.mutation(api.invoices.update,{id:x.iid,customerId:x.cid,customerName:"x",items:[{productId:x.pid,productName:"x",quantity:1,unitPrice:1,discount:0,total:1}],subtotal:1,discount:0,tax:0,total:1,paid:0,branchId:e.branchId});const s=await snapshot(e),last=s.movements.slice(-2);assert.deepEqual(last.map(x=>[x.type,x.valueDelta]),[["sale_reversal",20],["sale",-15]]);assert.deepEqual([s.products[0].stock,s.products[0].inventoryValue,s.invoices[0].items[0].unitCost],[9,125,15]);});
test("COGS-18 legacy costing is rejected without guessed inventory",async()=>{const e=await setup(),pid=await product(e),iid=await e.raw.run(ctx=>ctx.db.insert("invoices",{invoiceNumber:"OLD2",customerName:"قديم",items:[{productId:pid,productName:"منتج",quantity:1,unitPrice:30,discount:0,total:30}],subtotal:30,discount:0,tax:0,total:30,paid:0,remaining:30,paymentMethod:"unpaid",status:"unpaid",branchId:e.branchId,type:"sale"})),before=await snapshot(e);await assert.rejects(e.t.mutation(api.salesReturns.create,{invoiceId:iid,items:[{productId:pid,quantity:1}],reason:"x",date:"2026-07-21",requestId:"legacy2"}),/قديمة بلا تكلفة/);assert.deepEqual(await snapshot(e),before);});
test("COGS-19 partial return restores stock value credit net and status",async()=>{const e=await setup(),x=await sold(e,3);await returnOne(e,x);const s=await snapshot(e);assert.deepEqual([s.products[0].stock,s.products[0].inventoryValue,s.notes[0].totalCredit,s.invoices[0].creditedTotal,s.invoices[0].netTotal,s.invoices[0].status],[8,80,30,30,60,"partial_return"]);});
test("COGS-20 multiple returns accumulate returned and available quantities",async()=>{const e=await setup(),x=await sold(e,3);await returnOne(e,x,"r1");await returnOne(e,x,"r2");const eligible=await e.t.query(api.salesReturns.eligibleInvoices,{}),s=await snapshot(e);assert.deepEqual([eligible[0].items[0].returnedQuantity,eligible[0].items[0].availableQuantity,s.notes.reduce((n,x)=>n+x.totalCredit,0)],[2,1,60]);});
test("COGS-21 over-return rejects atomically",async()=>{const e=await setup(),x=await sold(e,2),before=await snapshot(e);await assert.rejects(e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:3}],reason:"x",date:"2026-07-21",requestId:"over"}),/تتجاوز/);assert.deepEqual(await snapshot(e),before);});
test("COGS-22 full rounded return reconciles exact invoice net",async()=>{const e=await setup(),x=await sold(e,3);for(let n=0;n<3;n++)await returnOne(e,x,`round-main-${n}`);const s=await snapshot(e);assert.equal(s.notes.reduce((sum,n)=>sum+n.totalCredit,0),s.invoices[0].total);assert.deepEqual([s.invoices[0].netTotal,s.invoices[0].status],[0,"returned"]);});
test("COGS-23 unpaid return reduces debt without financial movement",async()=>{const e=await setup(),x=await sold(e,3);await returnOne(e,x);const s=await snapshot(e);assert.deepEqual([s.notes[0].debtReduction,s.notes[0].cashRefund,s.invoices[0].remaining,s.customers[0].balance,s.transactions.length],[30,0,60,60,0]);});
test("COGS-24 paid return posts cash refund and updates account",async()=>{const e=await setup(),a=await account(e),pid=await product(e),cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:"paid",balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"x",items:[{productId:pid,productName:"x",quantity:2,unitPrice:1,discount:0,total:1}],subtotal:0,discount:0,tax:0,total:0,creationRequestId:"paid",branchId:e.branchId,initialPayment:{amount:60,accountId:a,paymentDate:"2026-07-20",requestId:"initial"}});await returnOne(e,{pid,cid,iid},"paid-return",{accountId:a});const s=await snapshot(e);assert.deepEqual([s.notes[0].cashRefund,s.invoices[0].paid,s.invoices[0].netTotal,s.accounts[0].currentBalance,s.transactions.at(-1)?.type],[30,30,30,230,"sales_return_refund"]);});
test("COGS-25 mixed return splits debt and cash exactly",async()=>{const e=await setup(),a=await account(e),x=await sold(e,3);await e.t.mutation(api.invoices.recordPayment,{invoiceId:x.iid,amount:60,accountId:a,paymentDate:"2026-07-20",requestId:"mix-pay"});await e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:2}],reason:"x",date:"2026-07-21",requestId:"mix-return",accountId:a});const n=(await snapshot(e)).notes[0];assert.deepEqual([n.totalCredit,n.debtReduction,n.cashRefund],[60,30,30]);});
test("COGS-26 return status survives collection refund and reversal",async()=>{const e=await setup(),a=await account(e),x=await sold(e,3),id=await returnOne(e,x,"status-return");let i=(await snapshot(e)).invoices[0];assert.equal(i.status,"partial_return");await e.t.mutation(api.invoices.recordPayment,{invoiceId:x.iid,amount:60,accountId:a,paymentDate:"2026-07-21",requestId:"status-pay"});i=(await snapshot(e)).invoices[0];assert.equal(i.status,"paid_returned_partial");await e.t.mutation(api.invoices.refundPayment,{invoiceId:x.iid,amount:10,accountId:a,date:"2026-07-21",reason:"x",requestId:"status-refund"});i=(await snapshot(e)).invoices[0];assert.equal(i.status,"partial_return");await e.t.mutation(api.salesReturns.reverse,{id,reason:"x",date:"2026-07-22",requestId:"status-reverse"});i=(await snapshot(e)).invoices[0];assert.deepEqual([i.status,i.paid,i.remaining,i.netTotal],["partial",50,40,90]);});
test("COGS-27 customer balance follows sale return collection and reversal",async()=>{const e=await setup(),a=await account(e),x=await sold(e,3);assert.equal((await snapshot(e)).customers[0].balance,90);const id=await returnOne(e,x,"bal-return");assert.equal((await snapshot(e)).customers[0].balance,60);await e.t.mutation(api.invoices.recordPayment,{invoiceId:x.iid,amount:20,accountId:a,paymentDate:"2026-07-21",requestId:"bal-pay"});assert.equal((await snapshot(e)).customers[0].balance,40);await e.t.mutation(api.salesReturns.reverse,{id,reason:"x",date:"2026-07-22",requestId:"bal-reverse"});assert.equal((await snapshot(e)).customers[0].balance,70);});
test("COGS-28 total purchases follows sale return and reversal",async()=>{const e=await setup(),x=await sold(e,3);assert.equal((await snapshot(e)).customers[0].totalPurchases,90);const id=await returnOne(e,x,"purchase-return");assert.equal((await snapshot(e)).customers[0].totalPurchases,60);await e.t.mutation(api.salesReturns.reverse,{id,reason:"x",date:"2026-07-22",requestId:"purchase-reverse"});assert.equal((await snapshot(e)).customers[0].totalPurchases,90);});
test("COGS-29 disabled refund account rejects all effects",async()=>{const e=await setup(),a=await account(e,200,false),x=await sold(e,2);await e.raw.run(ctx=>ctx.db.patch(x.iid,{paid:60,remaining:0,status:"paid"}));const before=await snapshot(e);await assert.rejects(returnOne(e,x,"disabled",{accountId:a}),/معطل/);assert.deepEqual(await snapshot(e),before);});
test("COGS-30 cross-branch refund account rejects and isolates",async()=>{const e=await setup(),other=await e.raw.run(ctx=>ctx.db.insert("branches",{name:"آخر",address:"x",isActive:true})),a=await account(e,200,true,other),x=await sold(e,2);await e.raw.run(ctx=>ctx.db.patch(x.iid,{paid:60,remaining:0,status:"paid"}));const before=await snapshot(e);await assert.rejects(returnOne(e,x,"cross",{accountId:a}),/لا ينتمي/);assert.deepEqual(await snapshot(e),before);});
test("COGS-31 insufficient account balance rolls back entire return",async()=>{const e=await setup(),a=await account(e,5),x=await sold(e,2);await e.raw.run(ctx=>ctx.db.patch(x.iid,{paid:60,remaining:0,status:"paid"}));const before=await snapshot(e);await assert.rejects(returnOne(e,x,"poor",{accountId:a}),/الرصيد غير كاف/);assert.deepEqual(await snapshot(e),before);});
test("COGS-32 return before cutover is rejected without effects",async()=>{const e=await setup(),x=await sold(e),before=await snapshot(e);await assert.rejects(e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"x",date:"2026-06-30",requestId:"old-date"}),/تاريخ القطع/);assert.deepEqual(await snapshot(e),before);});
test("COGS-33 creation request idempotency duplicates no effect",async()=>{const e=await setup(),a=await account(e),x=await sold(e,2);await e.raw.run(ctx=>ctx.db.patch(x.iid,{paid:60,remaining:0,status:"paid"}));const one=await returnOne(e,x,"idem",{accountId:a}),before=await snapshot(e),two=await returnOne(e,x,"idem",{accountId:a}),after=await snapshot(e);assert.equal(one,two);assert.deepEqual([after.notes.length,after.movements.length,after.transactions.length],[1,before.movements.length,before.transactions.length]);});
test("COGS-34 credit note numbering is unique sequential and ignores count",async()=>{const e=await setup(),x=await sold(e,3);await e.raw.run(ctx=>ctx.db.insert("salesReturns",{creditNoteNumber:"CRN-2026-00009",invoiceId:x.iid,invoiceNumber:"legacy",customerName:"x",items:[],subtotal:0,totalCredit:0,totalCogsReversed:0,debtReduction:0,cashRefund:0,reason:"legacy",date:"2026-07-20",branchId:e.branchId,status:"reversed",creationRequestId:"legacy",createdBy:"x",createdAt:0}));await returnOne(e,x,"num1");await returnOne(e,x,"num2");const nums=(await snapshot(e)).notes.map(x=>x.creditNoteNumber).sort();assert.equal(new Set(nums).size,3);assert.deepEqual(nums,["CRN-2026-00009","CRN-2026-00010","CRN-2026-00011"]);});
test("COGS-35 cancelled invoice rejects sales return",async()=>{const e=await setup(),x=await sold(e);await e.t.mutation(api.invoices.cancel,{id:x.iid,reason:"x"});const before=await snapshot(e);await assert.rejects(returnOne(e,x,"cancelled-return"),/ملغاة/);assert.deepEqual(await snapshot(e),before);});
test("COGS-36 permissions branch isolation and return cost redaction",async()=>{const e=await setup(),x=await sold(e),id=await returnOne(e,x,"secure");const other=await e.raw.run(ctx=>ctx.db.insert("branches",{name:"آخر",address:"x",isActive:true}));await e.raw.run(async ctx=>{await ctx.db.insert("userProfiles",{userId:"no",tokenIdentifier:"no",name:"no",role:"viewer",branchId:e.branchId,permissions:["view_sales_returns"],isActive:true});await ctx.db.insert("userProfiles",{userId:"other",tokenIdentifier:"other",name:"other",role:"viewer",branchId:other,permissions:["view_sales_returns","create_sales_returns"],isActive:true});});const no=e.raw.withIdentity({subject:"no",tokenIdentifier:"no"}),foreign=e.raw.withIdentity({subject:"other",tokenIdentifier:"other"});await assert.rejects(no.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"x",date:"2026-07-21",requestId:"denied"}),/create_sales_returns/);assert.deepEqual(await foreign.query(api.salesReturns.list,{}),[]);await assert.rejects(foreign.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"x",date:"2026-07-21",requestId:"foreign"}),/الفرع/);const visible=await no.query(api.salesReturns.list,{invoiceId:x.iid});assert.equal(visible[0]._id,id);assert.equal("totalCogsReversed" in visible[0],false);assert.equal("historicalUnitCost" in visible[0].items[0],false);});

test("COGS-22A actual cumulative full return equals invoice net despite rounding",async()=>{const e=await setup(),x=await sold(e,3);for(let n=0;n<3;n++)await e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"تقريب",date:"2026-07-21",requestId:`round-${n}`});const xstate=await state(e);assert.equal(xstate.notes.reduce((sum,n)=>sum+n.totalCredit,0),xstate.invoices[0].total);assert.equal(xstate.invoices[0].netTotal,0);assert.equal(xstate.invoices[0].status,"returned");});
test("COGS-35A reversal without cash is atomic and idempotent",async()=>{const e=await setup(),x=await sold(e,2);const id=await e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"خطأ",date:"2026-07-21",requestId:"create-reverse"});const args={id,reason:"تصحيح",date:"2026-07-22",requestId:"reverse-once"};assert.equal(await e.t.mutation(api.salesReturns.reverse,args),id);assert.equal(await e.t.mutation(api.salesReturns.reverse,args),id);const s=await state(e);assert.equal(s.notes[0].status,"reversed");assert.equal(s.products[0].stock,8);await assert.rejects(e.t.mutation(api.salesReturns.reverse,{...args,requestId:"different"}),/بطلب مختلف/);});
test("COGS-35B cash-refund reversal links both financial transactions",async()=>{const e=await setup();const accountId=await e.raw.run(ctx=>ctx.db.insert("financialAccounts",{name:"خزينة",code:"C",uniqueKey:crypto.randomUUID(),type:"cash",branchId:e.branchId,isActive:true,currentBalance:200,allowNegative:false,settlementDelayDays:0,createdAt:Date.now(),createdBy:"admin",updatedAt:Date.now()}));const x=await sold(e,2);await e.t.mutation(api.invoices.recordPayment,{invoiceId:x.iid,amount:60,accountId,paymentDate:"2026-07-20",requestId:"pay"});const id=await e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"رد",date:"2026-07-21",requestId:"cash-return",accountId});await e.t.mutation(api.salesReturns.reverse,{id,reason:"تصحيح",date:"2026-07-22",requestId:"cash-reverse"});const s=await state(e),original=s.transactions.find(t=>t.type==="sales_return_refund"),reversal=s.transactions.find(t=>t.type==="reversal");assert.equal(original?.status,"reversed");assert.equal(original?.reversalTransactionId,reversal?._id);assert.equal(reversal?.originalTransactionId,original?._id);assert.equal(s.notes[0].reversalTransactionId,reversal?._id);});

test("COGS-35C cash reversal insufficient account state rolls back atomically",async()=>{const e=await setup(),a=await account(e),x=await sold(e,2);await e.t.mutation(api.invoices.recordPayment,{invoiceId:x.iid,amount:60,accountId:a,paymentDate:"2026-07-20",requestId:"poor-reverse-pay"});const id=await returnOne(e,x,"poor-reverse-return",{accountId:a});await e.raw.run(ctx=>ctx.db.patch(a,{currentBalance:-40}));const before=await snapshot(e);await assert.rejects(e.t.mutation(api.salesReturns.reverse,{id,reason:"x",date:"2026-07-22",requestId:"poor-reverse"}),/الرصيد غير كاف/);assert.deepEqual(await snapshot(e),before);});
test("COGS-35D reversal date is persisted and cutover enforced",async()=>{const e=await setup(),x=await sold(e,2),id=await returnOne(e,x,"dated-return"),before=await snapshot(e);await assert.rejects(e.t.mutation(api.salesReturns.reverse,{id,reason:"x",date:"2026-06-30",requestId:"early-reverse"}),/تاريخ القطع/);assert.deepEqual(await snapshot(e),before);await e.t.mutation(api.salesReturns.reverse,{id,reason:"x",date:"2026-07-23",requestId:"dated-reverse"});assert.equal((await snapshot(e)).notes[0].reversalDate,"2026-07-23");});
