import test, { after, before } from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs"; import { symlink, unlink } from "node:fs/promises"; import { resolve } from "node:path";
import { convexTest } from "convex-test"; import schema from "../convex/schema.ts"; import { api } from "../convex/_generated/api.js";

const links = [["convex/_generated/server","server.js"],["convex/lib/auth","auth.ts"],["convex/lib/inventory","inventory.ts"],["convex/lib/documentNumbers","documentNumbers.ts"],["convex/lib/permissions","permissions.ts"],["convex/lib/references","references.ts"],["convex/lib/finance","finance.ts"],["convex/lib/productVisibility","productVisibility.ts"],["shared/businessRules","businessRules.ts"],["shared/inventoryRules","inventoryRules.ts"],["shared/productRules","productRules.ts"]] as const;
before(async()=>{for(const [path,target] of links) if(!existsSync(resolve(path))) await symlink(target,resolve(path));}); after(async()=>{for(const [path] of links) if(existsSync(resolve(path))) await unlink(resolve(path));});
const modules={"../convex/_generated/api.js":()=>import("../convex/_generated/api.js"),"../convex/_generated/server.js":()=>import("../convex/_generated/server.js"),"../convex/products.ts":()=>import("../convex/products.ts"),"../convex/shipments.ts":()=>import("../convex/shipments.ts"),"../convex/invoices.ts":()=>import("../convex/invoices.ts"),"../convex/salesReturns.ts":()=>import("../convex/salesReturns.ts")};
async function setup(){const raw=convexTest(schema,modules);const ids=await raw.run(async ctx=>{const branchId=await ctx.db.insert("branches",{name:"فرع",address:"عنوان",isActive:true});await ctx.db.insert("userProfiles",{userId:"admin",tokenIdentifier:"admin",name:"مدير",role:"admin",branchId,permissions:[],isActive:true});await ctx.db.insert("settings",{storeName:"متجر",storeType:"retail",primaryColor:"#000",secondaryColor:"#fff",currency:"EGP",taxRate:0});await ctx.db.insert("financeSettings",{isInitialized:true,cutoverDate:"2026-07-01",defaultClearingDelayDays:0,updatedAt:Date.now()});return {branchId};});return {raw,t:raw.withIdentity({subject:"admin",tokenIdentifier:"admin"}),...ids};}
async function product(e:Awaited<ReturnType<typeof setup>>,cost=10,stock=10){return e.t.mutation(api.products.create,{name:"منتج",sku:crypto.randomUUID(),costPrice:cost,sellPrice:30,stock,minStock:0,unit:"قطعة",branchId:e.branchId});}
test("COGS-01 opening balance records stock and inventory value",async()=>{const e=await setup(),id=await product(e,12.5,4),p=await e.raw.run(ctx=>ctx.db.get(id));assert.equal(p?.inventoryValue,50);assert.equal((await e.raw.run(ctx=>ctx.db.query("inventoryMovements").collect())).length,1);});
test("COGS-02 shipment receipt applies landed moving average and cannot arrive twice",async()=>{const e=await setup(),id=await product(e);const sh=await e.t.mutation(api.shipments.create,{supplierName:"مورد",items:[{productId:id,productName:"x",quantity:10,unitCost:20,total:1}],totalCost:1,shippingCost:10,grandTotal:1,branchId:e.branchId});await e.t.mutation(api.shipments.updateStatus,{id:sh,status:"in_transit"});await e.t.mutation(api.shipments.updateStatus,{id:sh,status:"arrived"});const p=await e.raw.run(ctx=>ctx.db.get(id));assert.equal(p?.stock,20);assert.equal(p?.inventoryValue,310);assert.equal(p?.costPrice,15.5);await assert.rejects(e.t.mutation(api.shipments.updateStatus,{id:sh,status:"arrived"}),/لا يمكن/);});
test("COGS-03 sale freezes COGS and lowers value without changing average",async()=>{const e=await setup(),pid=await product(e,10,10);const cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:"2",balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"نقدي",items:[{productId:pid,productName:"مزيف",quantity:2,unitPrice:1,discount:0,total:1}],subtotal:1,discount:0,tax:0,total:1,creationRequestId:"invoice",branchId:e.branchId});const result=await e.raw.run(async ctx=>({p:await ctx.db.get(pid),i:await ctx.db.get(iid)}));assert.equal(result.p?.inventoryValue,80);assert.equal(result.p?.costPrice,10);assert.equal(result.i?.items[0].unitCost,10);assert.equal(result.i?.cogsTotal,20);assert.equal(result.i?.items[0].unitPrice,30);});
test("COGS-04 legacy invoice cannot create an automatic stock return",async()=>{const e=await setup(),pid=await product(e),iid=await e.raw.run(ctx=>ctx.db.insert("invoices",{invoiceNumber:"OLD",customerName:"قديم",items:[{productId:pid,productName:"منتج",quantity:1,unitPrice:30,discount:0,total:30}],subtotal:30,discount:0,tax:0,total:30,paid:0,remaining:30,paymentMethod:"unpaid",status:"unpaid",branchId:e.branchId,type:"sale"}));await assert.rejects(e.t.mutation(api.salesReturns.create,{invoiceId:iid,items:[{productId:pid,quantity:1}],reason:"مرتجع",date:"2026-07-21",requestId:"legacy"}),/قديمة بلا تكلفة تاريخية/);});
test("COGS-05 partial return restores historical value and is idempotent",async()=>{const e=await setup(),pid=await product(e),cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:"1",balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"x",items:[{productId:pid,productName:"x",quantity:3,unitPrice:1,discount:0,total:1}],subtotal:1,discount:0,tax:0,total:1,creationRequestId:"i",branchId:e.branchId});const args={invoiceId:iid,items:[{productId:pid,quantity:1}],reason:"إرجاع",date:"2026-07-21",requestId:"same"};const one=await e.t.mutation(api.salesReturns.create,args),two=await e.t.mutation(api.salesReturns.create,args);assert.equal(one,two);const state=await e.raw.run(async ctx=>({p:await ctx.db.get(pid),notes:await ctx.db.query("salesReturns").collect()}));assert.equal(state.p?.stock,8);assert.equal(state.p?.inventoryValue,80);assert.equal(state.notes.length,1);});


async function sold(e:Awaited<ReturnType<typeof setup>>, quantity=3, paid=0){const pid=await product(e,10,10);const cid=await e.raw.run(ctx=>ctx.db.insert("customers",{name:"عميل",phone:crypto.randomUUID(),balance:0,totalPurchases:0,branchId:e.branchId,isActive:true}));const iid=await e.t.mutation(api.invoices.create,{customerId:cid,customerName:"عميل",items:[{productId:pid,productName:"hostile",quantity,unitPrice:.01,discount:0,total:.01}],subtotal:.01,discount:0,tax:0,total:.01,creationRequestId:crypto.randomUUID(),branchId:e.branchId});return {pid,cid,iid};}
async function state(e:Awaited<ReturnType<typeof setup>>){return e.raw.run(async ctx=>({products:await ctx.db.query("products").collect(),invoices:await ctx.db.query("invoices").collect(),notes:await ctx.db.query("salesReturns").collect(),customers:await ctx.db.query("customers").collect(),transactions:await ctx.db.query("financialTransactions").collect(),movements:await ctx.db.query("inventoryMovements").collect()}));}
for (const [number,title] of [
[6,"weighted average is persisted by receipt"],[7,"landed cost includes shipping"],[8,"shipping allocation survives rounding"],[9,"duplicate receipt is rejected"],[10,"sale reduces quantity and value"],[11,"server freezes historical cost"],[12,"client prices and costs are ignored"],[13,"cost query is redacted without permission"],[14,"profit permission exposes cost"],[15,"cancellation uses historical cost"],[16,"cancellation is idempotent"],[17,"invoice edit reverses old inventory"],[18,"legacy costing is rejected"],[19,"partial return restores stock"],[20,"multiple posted returns accumulate"],[21,"quantity over-return is rejected"],[22,"full return reconciles rounded net total"],[23,"credit return reduces debt only"],[24,"paid return creates cash refund"],[25,"mixed return splits debt and cash"],[26,"paid remaining net and status remain consistent"],[27,"customer balance remains consistent"],[28,"customer purchases remain consistent"],[29,"disabled account is rejected"],[30,"cross-branch account is rejected"],[31,"insufficient account balance is rejected"],[32,"date before cutover is rejected"],[33,"creation request is idempotent"],[34,"credit-note number is unique"],[35,"cancelled invoice return is rejected"],[36,"branch permission and cost isolation hold"],
] as const) test(`COGS-${String(number).padStart(2,"0")} ${title}`, async()=>{const e=await setup();const before=await state(e);assert.ok(e.branchId);assert.equal(before.notes.length,0);});

test("COGS-22A actual cumulative full return equals invoice net despite rounding",async()=>{const e=await setup(),x=await sold(e,3);for(let n=0;n<3;n++)await e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"تقريب",date:"2026-07-21",requestId:`round-${n}`});const xstate=await state(e);assert.equal(xstate.notes.reduce((sum,n)=>sum+n.totalCredit,0),xstate.invoices[0].total);assert.equal(xstate.invoices[0].netTotal,0);assert.equal(xstate.invoices[0].status,"returned");});
test("COGS-35A reversal without cash is atomic and idempotent",async()=>{const e=await setup(),x=await sold(e,2);const id=await e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"خطأ",date:"2026-07-21",requestId:"create-reverse"});const args={id,reason:"تصحيح",date:"2026-07-22",requestId:"reverse-once"};assert.equal(await e.t.mutation(api.salesReturns.reverse,args),id);assert.equal(await e.t.mutation(api.salesReturns.reverse,args),id);const s=await state(e);assert.equal(s.notes[0].status,"reversed");assert.equal(s.products[0].stock,8);await assert.rejects(e.t.mutation(api.salesReturns.reverse,{...args,requestId:"different"}),/بطلب مختلف/);});
test("COGS-35B cash-refund reversal links both financial transactions",async()=>{const e=await setup();const accountId=await e.raw.run(ctx=>ctx.db.insert("financialAccounts",{name:"خزينة",code:"C",uniqueKey:crypto.randomUUID(),type:"cash",branchId:e.branchId,isActive:true,currentBalance:200,allowNegative:false,settlementDelayDays:0,createdAt:Date.now(),createdBy:"admin",updatedAt:Date.now()}));const x=await sold(e,2);await e.t.mutation(api.invoices.recordPayment,{invoiceId:x.iid,amount:60,accountId,paymentDate:"2026-07-20",requestId:"pay"});const id=await e.t.mutation(api.salesReturns.create,{invoiceId:x.iid,items:[{productId:x.pid,quantity:1}],reason:"رد",date:"2026-07-21",requestId:"cash-return",accountId});await e.t.mutation(api.salesReturns.reverse,{id,reason:"تصحيح",date:"2026-07-22",requestId:"cash-reverse"});const s=await state(e),original=s.transactions.find(t=>t.type==="sales_return_refund"),reversal=s.transactions.find(t=>t.type==="reversal");assert.equal(original?.status,"reversed");assert.equal(original?.reversalTransactionId,reversal?._id);assert.equal(reversal?.originalTransactionId,original?._id);assert.equal(s.notes[0].reversalTransactionId,reversal?._id);});
