import test from "node:test";import assert from "node:assert/strict";import { readFile } from "node:fs/promises";
const source=await readFile("src/components/DeliveriesPage.tsx","utf8");
const check=(name:string,pattern:RegExp)=>test(name,()=>assert.match(source,pattern));
test("UI-01 removes legacy create",()=>assert.doesNotMatch(source,/api\.deliveries\.create\b/));
check("UI-02 creates from order and invoice",/api\.deliveries\.createFromOrderInvoice/);
check("UI-03 paginates deliveries",/usePaginatedQuery\(api\.deliveries\.listPaginated/);
check("UI-04 skips unauthorized queries",/canViewSettlements&&activeBranch\?\{branchId:activeBranch\}:"skip"/);
check("UI-05 preserves requestId across retry",/operationRequestId\.current/);
check("UI-06 has busy guards",/if\(busy\)return/);
test("UI-07 has no prompts",()=>assert.doesNotMatch(source,/window\.prompt|\bprompt\(/));
check("UI-08 delivery confirmation modal",/تأكيد التسليم والتحصيل/);
check("UI-09 return and cancel modals",/إرجاع قبل التسليم[\s\S]+إلغاء التوصيل/);
check("UI-10 confirmation reversal modal",/عكس تأكيد التسليم/);
check("UI-11 restricted COD account picker",/api\.deliveries\.accountPicker/);
check("UI-12 batch settlement",/api\.deliveries\.createCodSettlement/);
check("UI-13 settlement reversal modal",/عكس تسوية COD/);
check("UI-14 waits for print DTO",/const dto=await/);
check("UI-15 guards print",/if\(busy\|\|!canPrint\)return/);
test("UI-16 picker does not expose balances",()=>assert.doesNotMatch(source,/currentBalance|availableBalance/));
check("UI-17 shows Convex errors",/getErrorMessage/);
test("UI-18 has no TypeScript escapes",()=>assert.doesNotMatch(source,/as any|@ts-ignore/));
