import test, { after, before } from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { symlink, unlink } from "node:fs/promises";
import { resolve } from "node:path";
import { convexTest } from "convex-test";
import schema from "../convex/schema.ts";
import { api } from "../convex/_generated/api.js";
import type { Id } from "../convex/_generated/dataModel.js";
const links=[["convex/_generated/server","server.js"],["convex/lib/auth","auth.ts"],["convex/lib/permissions","permissions.ts"],["convex/lib/references","references.ts"],["convex/lib/finance","finance.ts"],["convex/lib/customerLedger","customerLedger.ts"],["convex/lib/documentNumbers","documentNumbers.ts"],["shared/businessRules","businessRules.ts"],["shared/moneyRules","moneyRules.ts"]] as const;
before(async()=>{for(const [path,target] of links)if(!existsSync(resolve(path)))await symlink(target,resolve(path));});
after(async()=>{for(const [path] of links)if(existsSync(resolve(path)))await unlink(resolve(path));});
const modules={"../convex/_generated/api.js":()=>import("../convex/_generated/api.js"),"../convex/_generated/server.js":()=>import("../convex/_generated/server.js"),"../convex/deliveries.ts":()=>import("../convex/deliveries.ts")};
async function fixture(serial:number,status:"pending"|"shipped"|"delivered"|"returned"|"cancelled"="pending") { const raw=convexTest(schema,modules);const ids=await raw.run(async ctx=>{const branchId=await ctx.db.insert("branches",{name:`فرع ${serial}`,address:"القاهرة",isActive:true});await ctx.db.insert("userProfiles",{userId:`admin-${serial}`,tokenIdentifier:`admin-${serial}`,name:"مدير",role:"admin",branchId,permissions:[],isActive:true});const customerId=await ctx.db.insert("customers",{name:"عميل",phone:`011${serial}`,balance:0,totalPurchases:0,branchId,isActive:true});const orderId=await ctx.db.insert("orders",{orderNumber:`ORD-${serial}`,customerId,customerName:"عميل",items:[],total:serial,deposit:0,remaining:serial,status:"ready",branchId});const invoiceId=await ctx.db.insert("invoices",{invoiceNumber:`INV-${serial}`,customerId,customerName:"عميل",items:[],subtotal:serial,discount:0,tax:0,total:serial,netTotal:serial,creditedTotal:0,paid:0,remaining:serial,paymentMethod:"cod",status:"unpaid",branchId,type:"sale"});const deliveryId=await ctx.db.insert("deliveries",{deliveryNumber:`DEL-2026-${String(serial).padStart(5,"0")}`,customerName:`عميل ${serial}`,customerPhone:`010${serial}`,city:"القاهرة",address:"عنوان",items:[{productName:"منتج",quantity:1,unitPrice:serial}],totalAmount:serial,grandTotal:serial,paymentMethod:"cod",codAmount:serial,prepaidAmount:0,shippingCompany:"شركة",shippingCost:0,status,branchId});return{branchId,deliveryId,orderId,invoiceId};});return{raw,t:raw.withIdentity({subject:`admin-${serial}`,tokenIdentifier:`admin-${serial}`}),...ids};}

async function creationFixture(serial:number, options:{orderStatus?:"draft"|"confirmed"|"ready"|"delivered"|"cancelled";missingCustomer?:boolean;invoiceStatus?:"unpaid"|"partial"|"paid"|"cancelled"|"partially_returned"|"fully_returned";orderTotal?:number;deposit?:number}={}) {
  const raw=convexTest(schema,modules);
  const ids=await raw.run(async ctx=>{
    const branchId=await ctx.db.insert("branches",{name:`إنشاء ${serial}`,address:"القاهرة",isActive:true});
    await ctx.db.insert("financeSettings",{isInitialized:true,cutoverDate:"2026-07-01",defaultClearingDelayDays:0,updatedAt:Date.now()});
    await ctx.db.insert("userProfiles",{userId:`creator-${serial}`,tokenIdentifier:`creator-${serial}`,name:"مدير",role:"admin",branchId,permissions:[],isActive:true});
    const customerId=await ctx.db.insert("customers",{name:"عميل موثوق",phone:`010${serial}`,balance:0,totalPurchases:0,branchId,isActive:true});
    if((options.deposit??0)>0)await ctx.db.insert("customerBalances",{key:`${customerId}:${branchId}`,customerId,branchId,receivableBalance:100,advanceBalance:options.deposit??0,totalPurchases:100,openingBalancePostedAt:Date.now(),updatedAt:Date.now()});
    const productId=await ctx.db.insert("products",{name:"منتج",sku:`SKU-${serial}`,costPrice:20,sellPrice:50,stock:10,inventoryValue:200,minStock:0,unit:"قطعة",branchId,isActive:true});
    const linkedCustomer=options.missingCustomer?undefined:customerId;
    const total=options.orderTotal??100,deposit=options.deposit??0;
    const orderItems=[{productName:"منتج",quantity:2,unitPrice:50}];
    const invoiceItems=[{productId,productName:"منتج",quantity:2,unitPrice:50,discount:0,total:100}];
    const orderId=await ctx.db.insert("orders",{orderNumber:`ORD-C-${serial}`,customerId:linkedCustomer,customerName:"عميل موثوق",items:orderItems,total,deposit,remaining:total-deposit,status:options.orderStatus??"ready",branchId});
    const invoiceId=await ctx.db.insert("invoices",{invoiceNumber:`INV-C-${serial}`,customerId:linkedCustomer,customerName:"عميل موثوق",items:invoiceItems,subtotal:100,discount:0,tax:0,total:100,netTotal:100,creditedTotal:0,paid:0,remaining:100,paymentMethod:"cod",status:options.invoiceStatus??"unpaid",branchId,type:"sale"});
    return{branchId,customerId,orderId,invoiceId};
  });
  const t=raw.withIdentity({subject:`creator-${serial}`,tokenIdentifier:`creator-${serial}`});
  const args={orderId:ids.orderId,invoiceId:ids.invoiceId,city:"القاهرة",address:"عنوان موثوق",shippingCompany:"ناقل",expectedCarrierFee:1,branchId:ids.branchId,date:"2026-07-26",requestId:`create-${serial}`};
  return{raw,t,args,...ids};
}
async function confirmationFixture(serial:number, options:{paid?:number;cutoffDate?:string;accountType?:"cod_clearing"|"cash"|"bank";accountActive?:boolean}={}) {
  const paid=options.paid??20, remaining=100-paid, raw=convexTest(schema,modules);
  const ids=await raw.run(async ctx=>{
    const branchId=await ctx.db.insert("branches",{name:`تأكيد ${serial}`,address:"القاهرة",isActive:true});
    await ctx.db.insert("financeSettings",{isInitialized:true,cutoverDate:options.cutoffDate??"2026-07-01",defaultClearingDelayDays:0,updatedAt:1});
    await ctx.db.insert("userProfiles",{userId:`confirmer-${serial}`,tokenIdentifier:`confirmer-${serial}`,name:"مدير COD",role:"admin",branchId,permissions:[],isActive:true});
    const customerId=await ctx.db.insert("customers",{name:"عميل COD",phone:`012${serial}`,balance:0,totalPurchases:100,branchId,isActive:true});
    await ctx.db.insert("customerBalances",{key:`${customerId}:${branchId}`,customerId,branchId,receivableBalance:remaining,advanceBalance:0,totalPurchases:100,openingBalancePostedAt:1,updatedAt:1});
    const productId=await ctx.db.insert("products",{name:"منتج COD",sku:`COD-SKU-${serial}`,costPrice:40,sellPrice:50,stock:10,inventoryValue:400,minStock:0,unit:"قطعة",branchId,isActive:true});
    const orderId=await ctx.db.insert("orders",{orderNumber:`ORD-COD-${serial}`,customerId,customerName:"عميل COD",items:[{productName:"منتج COD",quantity:2,unitPrice:50}],total:100,deposit:paid,appliedDeposit:paid,remaining,status:"ready",branchId});
    const invoiceId=await ctx.db.insert("invoices",{invoiceNumber:`INV-COD-${serial}`,customerId,customerName:"عميل COD",items:[{productId,productName:"منتج COD",quantity:2,unitPrice:50,discount:0,total:100}],subtotal:100,discount:0,tax:0,total:100,netTotal:100,creditedTotal:0,paid,remaining,paymentMethod:remaining?"partial":"prepaid",status:remaining?(paid?"partial":"unpaid"):"paid",notes:`historical-${serial}`,branchId,type:"sale"});
    const accountId=await ctx.db.insert("financialAccounts",{name:`حساب COD ${serial}`,code:`COD-${serial}`,uniqueKey:`cod:${serial}`,type:options.accountType??"cod_clearing",branchId,isActive:options.accountActive??true,currentBalance:0,allowNegative:false,settlementDelayDays:0,createdAt:1,createdBy:`confirmer-${serial}`,updatedAt:1});
    return{branchId,customerId,productId,orderId,invoiceId,accountId};
  });
  const t=raw.withIdentity({subject:`confirmer-${serial}`,tokenIdentifier:`confirmer-${serial}`});
  const createArgs={orderId:ids.orderId,invoiceId:ids.invoiceId,city:"القاهرة",address:"عنوان COD",shippingCompany:"ناقل COD",expectedCarrierFee:5,branchId:ids.branchId,date:options.cutoffDate??"2026-07-10",requestId:`create-confirm-${serial}`};
  return{raw,t,createArgs,...ids};
}
async function codState(e:Awaited<ReturnType<typeof confirmationFixture>>) {return e.raw.run(async ctx=>({delivery:(await ctx.db.query("deliveries").collect())[0],confirmations:await ctx.db.query("deliveryConfirmations").collect(),transactions:await ctx.db.query("financialTransactions").collect(),movements:await ctx.db.query("financialMovements").collect(),entries:await ctx.db.query("customerLedgerEntries").collect(),balance:(await ctx.db.query("customerBalances").collect())[0],account:await ctx.db.get(e.accountId),invoice:await ctx.db.get(e.invoiceId),order:await ctx.db.get(e.orderId),product:await ctx.db.get(e.productId),inventory:await ctx.db.query("inventoryMovements").collect()}));}
async function addConfirmationCase(e:Awaited<ReturnType<typeof confirmationFixture>>,suffix:string,branchId?:Id<"branches">) {
  return e.raw.run(async ctx=>{
    const targetBranchId=branchId??await ctx.db.insert("branches",{name:`فرع ${suffix}`,address:"القاهرة",isActive:true});
    const customerId=await ctx.db.insert("customers",{name:`عميل ${suffix}`,phone:`010${suffix}`,balance:0,totalPurchases:100,branchId:targetBranchId,isActive:true});
    await ctx.db.insert("customerBalances",{key:`${customerId}:${targetBranchId}`,customerId,branchId:targetBranchId,receivableBalance:80,advanceBalance:0,totalPurchases:100,openingBalancePostedAt:1,updatedAt:1});
    const productId=await ctx.db.insert("products",{name:`منتج ${suffix}`,sku:`SKU-${suffix}`,costPrice:40,sellPrice:50,stock:10,inventoryValue:400,minStock:0,unit:"قطعة",branchId:targetBranchId,isActive:true});
    const orderId=await ctx.db.insert("orders",{orderNumber:`ORD-${suffix}`,customerId,customerName:`عميل ${suffix}`,items:[{productName:`منتج ${suffix}`,quantity:2,unitPrice:50}],total:100,deposit:20,appliedDeposit:20,remaining:80,status:"ready",branchId:targetBranchId});
    const invoiceId=await ctx.db.insert("invoices",{invoiceNumber:`INV-${suffix}`,customerId,customerName:`عميل ${suffix}`,items:[{productId,productName:`منتج ${suffix}`,quantity:2,unitPrice:50,discount:0,total:100}],subtotal:100,discount:0,tax:0,total:100,netTotal:100,creditedTotal:0,paid:20,remaining:80,paymentMethod:"partial",status:"partial",branchId:targetBranchId,type:"sale"});
    const accountId=await ctx.db.insert("financialAccounts",{name:`COD ${suffix}`,code:`COD-${suffix}`,uniqueKey:`cod:${suffix}`,type:"cod_clearing",branchId:targetBranchId,isActive:true,currentBalance:0,allowNegative:false,settlementDelayDays:0,createdAt:1,createdBy:"fixture",updatedAt:1});
    return{branchId:targetBranchId,customerId,productId,orderId,invoiceId,accountId,createArgs:{orderId,invoiceId,city:"القاهرة",address:`عنوان ${suffix}`,shippingCompany:"ناقل",expectedCarrierFee:5,branchId:targetBranchId,date:"2026-07-10",requestId:`create-${suffix}`}};
  });
}
test("COD-01 إنشاء Snapshot موثوق",async()=>{const e=await creationFixture(1);const id=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.args);const row=await e.raw.run(ctx=>ctx.db.get(id));assert.equal(row?.orderId,e.orderId);assert.equal(row?.invoiceId,e.invoiceId);assert.deepEqual(row?.items,[{productName:"منتج",quantity:2,unitPrice:50}]);assert.equal(row?.codAmount,100);});
test("COD-02 رفض عميل مفقود",async()=>{const e=await creationFixture(2,{missingCustomer:true});const before=await e.raw.run(ctx=>ctx.db.query("deliveries").collect());await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,e.args),/عميل/);const after=await e.raw.run(ctx=>ctx.db.query("deliveries").collect());assert.deepEqual(after,before);});
test("COD-03 رفض طلب غير جاهز",async()=>{const e=await creationFixture(3,{orderStatus:"draft"});const before=await e.raw.run(ctx=>ctx.db.query("deliveries").collect());await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,e.args),/جاهز/);assert.deepEqual(await e.raw.run(ctx=>ctx.db.query("deliveries").collect()),before);});
test("COD-04 رفض فاتورة غير مؤهلة",async()=>{const e=await creationFixture(4,{invoiceStatus:"cancelled"});const before=await e.raw.run(ctx=>ctx.db.query("deliveries").collect());await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,e.args),/غير مؤهلة/);assert.deepEqual(await e.raw.run(ctx=>ctx.db.query("deliveries").collect()),before);});
test("COD-05 عزل العميل والفرع",async()=>{const e=await creationFixture(5);const other=await e.raw.run(ctx=>ctx.db.insert("branches",{name:"آخر",address:"x",isActive:true}));const before=await e.raw.run(ctx=>ctx.db.query("deliveries").collect());await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,{...e.args,branchId:other}),/فرع/);assert.deepEqual(await e.raw.run(ctx=>ctx.db.query("deliveries").collect()),before);});
test("COD-06 مطابقة صافي الفاتورة",async()=>{const e=await creationFixture(6,{orderTotal:99});const before=await e.raw.run(ctx=>ctx.db.query("deliveries").collect());await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,e.args),/إجمالي/);assert.deepEqual(await e.raw.run(ctx=>ctx.db.query("deliveries").collect()),before);});
test("COD-07 منع التوصيل النشط المكرر",async()=>{const e=await creationFixture(7);await e.t.mutation(api.deliveries.createFromOrderInvoice,e.args);const before=await e.raw.run(ctx=>ctx.db.query("deliveries").collect());await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,{...e.args,requestId:"create-7-second"}),/توصيل نشط/);assert.deepEqual(await e.raw.run(ctx=>ctx.db.query("deliveries").collect()),before);});
test("COD-08 عدم إنشاء قيد لعربون صفري",async()=>{const e=await creationFixture(8,{deposit:0});await e.t.mutation(api.deliveries.createFromOrderInvoice,e.args);const state=await e.raw.run(async ctx=>({order:await ctx.db.get(e.orderId),entries:await ctx.db.query("customerLedgerEntries").collect()}));assert.equal(state.order?.linkedInvoiceId,e.invoiceId);assert.equal(state.order?.appliedDeposit,0);assert.equal(state.entries.length,0);});
test("COD-09 تطبيق العربون بلا خزينة",async()=>{const e=await creationFixture(9,{deposit:25});await e.t.mutation(api.deliveries.createFromOrderInvoice,e.args);const state=await e.raw.run(async ctx=>({invoice:await ctx.db.get(e.invoiceId),order:await ctx.db.get(e.orderId),entries:await ctx.db.query("customerLedgerEntries").collect(),transactions:await ctx.db.query("financialTransactions").collect()}));assert.equal(state.invoice?.paid,25);assert.equal(state.invoice?.remaining,75);assert.equal(state.order?.appliedDeposit,25);assert.equal(state.entries[0]?.type,"order_deposit_application");assert.equal(state.transactions.length,0);});
test("COD-10 Rollback للعربون الزائد",async()=>{const e=await creationFixture(10,{deposit:101});const before=await e.raw.run(async ctx=>({order:await ctx.db.get(e.orderId),invoice:await ctx.db.get(e.invoiceId),entries:await ctx.db.query("customerLedgerEntries").collect()}));await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,e.args),/يتجاوز/);const after=await e.raw.run(async ctx=>({order:await ctx.db.get(e.orderId),invoice:await ctx.db.get(e.invoiceId),entries:await ctx.db.query("customerLedgerEntries").collect()}));assert.deepEqual(after,before);});
test("COD-11 Idempotency الإنشاء",async()=>{const e=await creationFixture(11);const first=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.args);const second=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.args);assert.equal(second,first);assert.equal((await e.raw.run(ctx=>ctx.db.query("deliveries").collect())).length,1);});
test("COD-12 رفض بصمة إنشاء مختلفة",async()=>{const e=await creationFixture(12);await e.t.mutation(api.deliveries.createFromOrderInvoice,e.args);const before=await e.raw.run(ctx=>ctx.db.query("deliveries").collect());await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,{...e.args,city:"الجيزة"}),/requestId/);assert.deepEqual(await e.raw.run(ctx=>ctx.db.query("deliveries").collect()),before);});
test("COD-13 الشحن بلا حركة مالية",async()=>{const e=await confirmationFixture(13,{paid:20});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);const before=await codState(e);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const after=await codState(e);assert.equal(after.delivery?.status,"shipped");assert.deepEqual(after.transactions,before.transactions);assert.deepEqual(after.movements,before.movements);assert.deepEqual(after.entries,before.entries);assert.deepEqual(after.balance,before.balance);assert.equal(after.invoice?.paid,20);assert.equal(after.invoice?.remaining,80);assert.equal(after.product?.stock,before.product?.stock);assert.deepEqual(after.inventory,before.inventory);assert.equal(after.order?.status,"ready");});
test("COD-14 تأكيد COD ذري",async()=>{const e=await confirmationFixture(14,{paid:20});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const confirmationId=await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"confirm-14"});const s=await codState(e),c=s.confirmations[0],tx=s.transactions[0],m=s.movements[0],le=s.entries[0];assert.equal(c?._id,confirmationId);assert.equal(c?.attemptNumber,1);assert.equal(c?.status,"posted");assert.equal(s.delivery?.status,"delivered");assert.equal(s.delivery?.currentConfirmationId,confirmationId);assert.equal(s.order?.status,"delivered");assert.equal(s.invoice?.paid,100);assert.equal(s.invoice?.remaining,0);assert.equal(tx?.type,"delivery_cod_collection");assert.equal(m?.signedAmount,80);assert.equal(m?.accountId,e.accountId);assert.equal(le?.type,"delivery_cod_collection");assert.equal(le?.receivableDelta,-80);assert.equal(s.balance?.receivableBalance,0);assert.equal(s.delivery?.codFinancialTransactionId,tx?._id);assert.equal(s.delivery?.codCustomerLedgerEntryId,le?._id);assert.equal(c?.financialTransactionId,tx?._id);assert.equal(c?.customerLedgerEntryId,le?._id);assert.deepEqual(s.inventory,[]);assert.equal(s.product?.stock,10);});
test("COD-15 تحصيل المتبقي فقط",async()=>{const e=await confirmationFixture(15,{paid:30});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"confirm-15"});const s=await codState(e);assert.equal(s.delivery?.prepaidAmount,30);assert.equal(s.delivery?.codAmount,70);assert.equal(s.account?.currentBalance,70);assert.equal(s.movements.length,1);assert.equal(s.movements[0]?.signedAmount,70);assert.equal(s.entries[0]?.receivableDelta,-70);assert.equal(s.invoice?.paid,100);assert.equal(s.invoice?.remaining,0);assert.equal(s.transactions[0]?.amount,70);assert.equal(s.movements.some(m=>m.signedAmount===30),false);});
test("COD-16 تسليم المدفوع بالكامل",async()=>{const e=await confirmationFixture(16,{paid:100});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const confirmationId=await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,date:"2026-07-10",requestId:"confirm-16"});const s=await codState(e);assert.equal(s.confirmations[0]?._id,confirmationId);assert.equal(s.confirmations[0]?.codAmount,0);assert.equal(s.transactions.length,0);assert.equal(s.movements.length,0);assert.equal(s.entries.length,0);assert.equal(s.invoice?.paid,100);assert.equal(s.invoice?.remaining,0);assert.equal(s.invoice?.status,"paid");assert.equal(s.delivery?.status,"delivered");assert.equal(s.order?.status,"delivered");});
test("COD-17 اشتقاق حالة الفاتورة",async()=>{const e=await confirmationFixture(17,{paid:25});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"confirm-17"});const s=await codState(e);assert.equal(s.delivery?.codAmount,75);assert.equal(s.transactions[0]?.amount,75);assert.equal(s.invoice?.paid,100);assert.equal(s.invoice?.remaining,0);assert.equal(s.invoice?.status,"paid");assert.equal(s.invoice?.notes,"historical-17");});
test("COD-18 تسليم الطلب ذريًا",async()=>{const e=await confirmationFixture(18,{paid:20});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const confirmationId=await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"confirm-18"});const s=await codState(e);assert.equal(s.delivery?.status,"delivered");assert.equal(s.order?.status,"delivered");assert.equal(s.invoice?.status,"paid");assert.equal(s.confirmations[0]?._id,confirmationId);assert.equal(s.transactions.length,1);assert.equal(s.transactions[0]?.status,"posted");assert.equal(s.movements[0]?.balanceAfter,80);assert.equal(s.entries[0]?.receivableAfter,0);assert.equal(s.account?.currentBalance,80);assert.equal(s.balance?.receivableBalance,0);});
test("COD-19 Retry التأكيد",async()=>{const e=await confirmationFixture(19,{paid:20});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const args={deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",notes:"نفس الملاحظات",requestId:"retry-19"};const first=await e.t.mutation(api.deliveries.confirmDelivered,args);const second=await e.t.mutation(api.deliveries.confirmDelivered,args);const s=await codState(e);assert.equal(second,first);assert.equal(s.confirmations.length,1);assert.equal(s.transactions.length,1);assert.equal(s.movements.length,1);assert.equal(s.entries.length,1);assert.equal(s.account?.currentBalance,80);assert.equal(s.invoice?.paid,100);assert.equal(s.balance?.receivableBalance,0);});
test("COD-20 رفض بصمة تأكيد مختلفة",async()=>{const e=await confirmationFixture(20,{paid:20});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",notes:"الأصل",requestId:"fingerprint-20"});const beforeSnapshot=await codState(e);await assert.rejects(e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",notes:"مختلفة",requestId:"fingerprint-20"}),/requestId/);const afterSnapshot=await codState(e);assert.deepEqual(afterSnapshot,beforeSnapshot);});
test("COD-21 رفض حساب معطل",async()=>{const e=await confirmationFixture(21,{paid:20,accountActive:false});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const beforeSnapshot=await codState(e);await assert.rejects(e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"inactive-21"}),/معطل/);const afterSnapshot=await codState(e);assert.deepEqual(afterSnapshot,beforeSnapshot);assert.equal(afterSnapshot.delivery?.status,"shipped");assert.equal(afterSnapshot.confirmations.length,0);});
test("COD-22 رفض نوع حساب خاطئ",async()=>{const e=await confirmationFixture(22,{paid:20,accountType:"cash"});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const beforeSnapshot=await codState(e);await assert.rejects(e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"cash-22"}),/COD/);const afterSnapshot=await codState(e);assert.deepEqual(afterSnapshot,beforeSnapshot);assert.equal(afterSnapshot.confirmations.length,0);});
test("COD-23 رفض حساب فرع آخر",async()=>{const e=await confirmationFixture(23,{paid:20});const otherBranchId=await e.raw.run(ctx=>ctx.db.insert("branches",{name:"الفرع الآخر",address:"الجيزة",isActive:true}));const otherAccountId=await e.raw.run(ctx=>ctx.db.insert("financialAccounts",{name:"COD آخر",code:"OTHER-COD",uniqueKey:"other:cod",type:"cod_clearing",branchId:otherBranchId,isActive:true,currentBalance:0,allowNegative:false,settlementDelayDays:0,createdAt:1,createdBy:"admin",updatedAt:1}));const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const beforeSnapshot=await codState(e);const otherBefore=await e.raw.run(ctx=>ctx.db.get(otherAccountId));await assert.rejects(e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:otherAccountId,date:"2026-07-10",requestId:"other-23"}),/فرع/);assert.deepEqual(await codState(e),beforeSnapshot);assert.deepEqual(await e.raw.run(ctx=>ctx.db.get(otherAccountId)),otherBefore);await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"correct-23"});assert.equal((await codState(e)).delivery?.status,"delivered");});
test("COD-24 تاريخ القطع",async()=>{const cutoffDate="2026-07-10",e=await confirmationFixture(24,{paid:20,cutoffDate});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const beforeSnapshot=await codState(e);await assert.rejects(e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-09",requestId:"before-cutoff-24"}),/القطع/);assert.deepEqual(await codState(e),beforeSnapshot);await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"at-cutoff-24"});const s=await codState(e);assert.equal(s.confirmations[0]?.date,cutoffDate);assert.equal(s.transactions[0]?.date,cutoffDate);assert.equal(s.entries[0]?.date,cutoffDate);});
test("COD-25 دفتر العميل وRollback",async()=>{const e=await confirmationFixture(25,{paid:20});await e.raw.run(async ctx=>{const b=await ctx.db.get(e.customerId);void b;const balance=(await ctx.db.query("customerBalances").collect())[0];if(balance)await ctx.db.patch(balance._id,{receivableBalance:50});});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const beforeSnapshot=await codState(e);await assert.rejects(e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"rollback-25"}),/سالب/);const afterSnapshot=await codState(e);assert.deepEqual(afterSnapshot,beforeSnapshot);assert.equal(afterSnapshot.delivery?.status,"shipped");assert.equal(afterSnapshot.invoice?.paid,20);assert.equal(afterSnapshot.invoice?.remaining,80);assert.equal(afterSnapshot.confirmations.length+afterSnapshot.transactions.length+afterSnapshot.movements.length+afterSnapshot.entries.length+afterSnapshot.inventory.length,0);assert.equal(afterSnapshot.account?.currentBalance,0);assert.equal(afterSnapshot.balance?.receivableBalance,50);});
test("COD-26 إرجاع قبل التسليم",async()=>{const e=await confirmationFixture(26,{paid:20});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const beforeSnapshot=await codState(e);await assert.rejects(e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"returned",reason:"   "}),/سبب/);assert.deepEqual(await codState(e),beforeSnapshot);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"returned",reason:"  العميل رفض الاستلام  "});const s=await codState(e);assert.equal(s.delivery?.status,"returned");assert.equal(s.delivery?.cancellationReason,"العميل رفض الاستلام");assert.equal(s.delivery?.deliveredDate,undefined);assert.equal(s.invoice?.paid,20);assert.equal(s.invoice?.remaining,80);assert.equal(s.order?.status,"ready");assert.equal(s.confirmations.length+s.transactions.length+s.movements.length+s.entries.length+s.inventory.length,0);});
test("COD-27 منع مرتجع بعد التسليم",async()=>{const e=await confirmationFixture(27,{paid:20});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"confirm-27"});const beforeSnapshot=await codState(e);await assert.rejects(e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"returned",reason:"مرتجع"}),/تم التسليم/);const afterSnapshot=await codState(e);assert.deepEqual(afterSnapshot,beforeSnapshot);assert.equal(afterSnapshot.delivery?.status,"delivered");assert.equal(afterSnapshot.invoice?.paid,100);assert.equal(afterSnapshot.confirmations.length,1);assert.equal(afterSnapshot.movements.length,1);});
test("COD-28 إلغاء بسبب",async()=>{const e=await confirmationFixture(28,{paid:20});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);const beforeSnapshot=await codState(e);await assert.rejects(e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"cancelled",reason:"   "}),/سبب/);assert.deepEqual(await codState(e),beforeSnapshot);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"cancelled",reason:"  العميل طلب الإلغاء  "});const s=await codState(e);assert.equal(s.delivery?.status,"cancelled");assert.equal(s.delivery?.cancellationReason,"العميل طلب الإلغاء");assert.equal(typeof s.delivery?.cancelledAt,"number");assert.equal(s.delivery?.cancelledBy,"confirmer-28");assert.equal(s.confirmations.length+s.transactions.length+s.movements.length+s.entries.length,0);await assert.rejects(e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"cancelled",reason:"ثان"}),/لا يمكن/);});
test("COD-29 عزل Manager وShipping",async()=>{
  const e=await confirmationFixture(29,{paid:20}),managerCase=await addConfirmationCase(e,"29-manager",e.branchId),shippingCase=await addConfirmationCase(e,"29-shipping",e.branchId),other=await addConfirmationCase(e,"29-other"),shippingCrossCase=await addConfirmationCase(e,"29-shipping-cross",e.branchId);const otherBranchId=other.branchId;
  await e.raw.run(async ctx=>{await ctx.db.insert("userProfiles",{userId:"manager-29",tokenIdentifier:"manager-29",name:"Manager",role:"manager",branchId:e.branchId,permissions:[],isActive:true});await ctx.db.insert("userProfiles",{userId:"shipping-29",tokenIdentifier:"shipping-29",name:"Shipping",role:"shipping",branchId:e.branchId,permissions:[],isActive:true});});
  const manager=e.raw.withIdentity({subject:"manager-29",tokenIdentifier:"manager-29"}),shipping=e.raw.withIdentity({subject:"shipping-29",tokenIdentifier:"shipping-29"});
  const managerDelivery=await manager.mutation(api.deliveries.createFromOrderInvoice,managerCase.createArgs),shippingDelivery=await shipping.mutation(api.deliveries.createFromOrderInvoice,shippingCase.createArgs),otherDelivery=await e.t.mutation(api.deliveries.createFromOrderInvoice,other.createArgs),shippingCrossDelivery=await shipping.mutation(api.deliveries.createFromOrderInvoice,shippingCrossCase.createArgs);
  for(const [actor,id] of [[manager,managerDelivery],[shipping,shippingDelivery],[e.t,otherDelivery],[shipping,shippingCrossDelivery]] as const)await actor.mutation(api.deliveries.updateStatus,{id,status:"shipped"});
  await manager.mutation(api.deliveries.confirmDelivered,{deliveryId:managerDelivery,codClearingAccountId:managerCase.accountId,date:"2026-07-10",requestId:"تأكيد Manager"});
  let state=await e.raw.run(async ctx=>({delivery:await ctx.db.get(managerDelivery),account:await ctx.db.get(managerCase.accountId),transactions:(await ctx.db.query("financialTransactions").collect()).filter(x=>x.branchId===e.branchId),entries:(await ctx.db.query("customerLedgerEntries").collect()).filter(x=>x.customerId===managerCase.customerId)}));assert.equal(state.delivery?.status,"delivered");assert.equal(state.account?.currentBalance,80);assert.equal(state.transactions.length,1);assert.equal(state.entries.length,1);
  const beforeManagerReject=await e.raw.run(async ctx=>({otherDelivery:await ctx.db.get(otherDelivery),otherAccount:await ctx.db.get(other.accountId),shippingDelivery:await ctx.db.get(shippingDelivery)}));await assert.rejects(manager.mutation(api.deliveries.confirmDelivered,{deliveryId:otherDelivery,codClearingAccountId:other.accountId,date:"2026-07-10",requestId:"manager-other-delivery"}),/فرع/);await assert.rejects(manager.mutation(api.deliveries.confirmDelivered,{deliveryId:shippingDelivery,codClearingAccountId:other.accountId,date:"2026-07-10",requestId:"manager-other-account"}),/فرع/);assert.deepEqual(await e.raw.run(async ctx=>({otherDelivery:await ctx.db.get(otherDelivery),otherAccount:await ctx.db.get(other.accountId),shippingDelivery:await ctx.db.get(shippingDelivery)})),beforeManagerReject);
  await shipping.mutation(api.deliveries.confirmDelivered,{deliveryId:shippingDelivery,codClearingAccountId:shippingCase.accountId,date:"2026-07-10",requestId:"تأكيد Shipping"});
  state=await e.raw.run(async ctx=>({delivery:await ctx.db.get(shippingDelivery),account:await ctx.db.get(shippingCase.accountId),entries:(await ctx.db.query("customerLedgerEntries").collect()).filter(x=>x.customerId===shippingCase.customerId)}));assert.equal(state.delivery?.status,"delivered");assert.equal(state.account?.currentBalance,80);assert.equal(state.entries.length,1);
  const beforeShippingReject=await e.raw.run(async ctx=>({otherDelivery:await ctx.db.get(otherDelivery),otherAccount:await ctx.db.get(other.accountId),localDelivery:await ctx.db.get(shippingCrossDelivery),localAccount:await ctx.db.get(shippingCrossCase.accountId)}));await assert.rejects(shipping.mutation(api.deliveries.confirmDelivered,{deliveryId:otherDelivery,codClearingAccountId:other.accountId,date:"2026-07-10",requestId:"shipping-other-delivery"}),/فرع/);await assert.rejects(shipping.mutation(api.deliveries.confirmDelivered,{deliveryId:shippingCrossDelivery,codClearingAccountId:other.accountId,date:"2026-07-10",requestId:"shipping-other-account"}),/فرع/);assert.deepEqual(await e.raw.run(async ctx=>({otherDelivery:await ctx.db.get(otherDelivery),otherAccount:await ctx.db.get(other.accountId),localDelivery:await ctx.db.get(shippingCrossDelivery),localAccount:await ctx.db.get(shippingCrossCase.accountId)})),beforeShippingReject);
  for(const actor of [manager,shipping]){const page=await actor.query(api.deliveries.listPaginated,{branchId:otherBranchId,paginationOpts:{numItems:20,cursor:null}}),accounts=await actor.query(api.deliveries.accountPicker,{branchId:otherBranchId,purpose:"cod"});assert.equal(page.page.every(x=>x.branchId===e.branchId),true);assert.equal(page.page.some(x=>x._id===otherDelivery),false);assert.equal(accounts.every(x=>x.branchId===e.branchId),true);assert.equal(accounts.some(x=>x._id===other.accountId),false);}
});
test("COD-30 سياسة Admin وAccountant بفرعين وبيانات غير فارغة",async()=>{
  const e=await confirmationFixture(30,{paid:20}),other=await addConfirmationCase(e,"30-other"),otherBranchId=other.branchId;
  const destinations=await e.raw.run(async ctx=>{await ctx.db.insert("userProfiles",{userId:"accountant-30",tokenIdentifier:"accountant-30",name:"Accountant",role:"accountant",permissions:[],isActive:true});const first=await ctx.db.insert("financialAccounts",{name:"Cash branch one",code:"C30A",uniqueKey:"c30a",type:"cash",branchId:e.branchId,isActive:true,currentBalance:10,allowNegative:false,settlementDelayDays:0,createdAt:1,createdBy:"fixture",updatedAt:1});const second=await ctx.db.insert("financialAccounts",{name:"Bank branch two",code:"B30B",uniqueKey:"b30b",type:"bank",branchId:otherBranchId,isActive:true,currentBalance:20,allowNegative:false,settlementDelayDays:0,createdAt:1,createdBy:"fixture",updatedAt:1});return{first,second};});
  const admin=e.t,accountant=e.raw.withIdentity({subject:"accountant-30",tokenIdentifier:"accountant-30"}),firstDelivery=await admin.mutation(api.deliveries.createFromOrderInvoice,e.createArgs),secondDelivery=await admin.mutation(api.deliveries.createFromOrderInvoice,other.createArgs);await admin.mutation(api.deliveries.updateStatus,{id:firstDelivery,status:"shipped"});await admin.mutation(api.deliveries.updateStatus,{id:secondDelivery,status:"shipped"});
  const adminFirst=await admin.query(api.deliveries.accountPicker,{branchId:e.branchId,purpose:"cod"}),adminSecond=await admin.query(api.deliveries.accountPicker,{branchId:otherBranchId,purpose:"cod"});assert.deepEqual(adminFirst.map(x=>x._id),[e.accountId]);assert.deepEqual(adminSecond.map(x=>x._id),[other.accountId]);
  const accountantFirst=await accountant.query(api.deliveries.accountPicker,{branchId:e.branchId,purpose:"destination"}),accountantSecond=await accountant.query(api.deliveries.accountPicker,{branchId:otherBranchId,purpose:"destination"});assert.deepEqual(accountantFirst.map(x=>x._id),[destinations.first]);assert.deepEqual(accountantSecond.map(x=>x._id),[destinations.second]);assert.equal(accountantFirst.length>0&&accountantSecond.length>0,true);
  const beforeReject=await e.raw.run(async ctx=>({delivery:await ctx.db.get(firstDelivery),invoice:await ctx.db.get(e.invoiceId),order:await ctx.db.get(e.orderId),first:await ctx.db.get(e.accountId),second:await ctx.db.get(other.accountId)}));await assert.rejects(admin.mutation(api.deliveries.confirmDelivered,{deliveryId:firstDelivery,codClearingAccountId:other.accountId,date:"2026-07-10",requestId:"admin-mixed-branches"}),/فرع/);await assert.rejects(accountant.mutation(api.deliveries.confirmDelivered,{deliveryId:firstDelivery,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"accountant-no-confirm"}),/صلاحية/);assert.deepEqual(await e.raw.run(async ctx=>({delivery:await ctx.db.get(firstDelivery),invoice:await ctx.db.get(e.invoiceId),order:await ctx.db.get(e.orderId),first:await ctx.db.get(e.accountId),second:await ctx.db.get(other.accountId)})),beforeReject);
  await admin.mutation(api.deliveries.confirmDelivered,{deliveryId:firstDelivery,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"admin-first"});await admin.mutation(api.deliveries.confirmDelivered,{deliveryId:secondDelivery,codClearingAccountId:other.accountId,date:"2026-07-10",requestId:"admin-second"});const delivered=await e.raw.run(async ctx=>[await ctx.db.get(firstDelivery),await ctx.db.get(secondDelivery)]);assert.deepEqual(delivered.map(x=>x?.status),["delivered","delivered"]);
});
test("COD-31 منع Shipping من التسوية",async()=>{const e=await confirmationFixture(31,{paid:20});const destinationAccountId=await e.raw.run(async ctx=>{await ctx.db.insert("userProfiles",{userId:"shipping-31",tokenIdentifier:"shipping-31",name:"Shipping",role:"shipping",branchId:e.branchId,permissions:[],isActive:true});return ctx.db.insert("financialAccounts",{name:"Cash",code:"C31",uniqueKey:"c31",type:"cash",branchId:e.branchId,isActive:true,currentBalance:10,allowNegative:false,settlementDelayDays:0,createdAt:1,createdBy:"x",updatedAt:1});});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"confirm-31"});const Shipping=e.raw.withIdentity({subject:"shipping-31",tokenIdentifier:"shipping-31"}),beforeSnapshot=await e.raw.run(async ctx=>({s:await ctx.db.query("codSettlements").collect(),i:await ctx.db.query("codSettlementItems").collect(),d:await ctx.db.get(deliveryId),a:await ctx.db.get(e.accountId),cash:await ctx.db.get(destinationAccountId),tx:await ctx.db.query("financialTransactions").collect(),m:await ctx.db.query("financialMovements").collect()}));await assert.rejects(Shipping.mutation(api.deliveries.createCodSettlement,{deliveryIds:[deliveryId],sourceAccountId:e.accountId,destinationAccountId,feeAmount:5,date:"2026-07-10",branchId:e.branchId,requestId:"shipping-settle-31"}),/صلاحية/);assert.deepEqual(await e.raw.run(async ctx=>({s:await ctx.db.query("codSettlements").collect(),i:await ctx.db.query("codSettlementItems").collect(),d:await ctx.db.get(deliveryId),a:await ctx.db.get(e.accountId),cash:await ctx.db.get(destinationAccountId),tx:await ctx.db.query("financialTransactions").collect(),m:await ctx.db.query("financialMovements").collect()})),beforeSnapshot);});
test("COD-32 رفض Viewer وSales",async()=>{const e=await confirmationFixture(32,{paid:20});await e.raw.run(async ctx=>{for(const role of ["viewer","sales"])await ctx.db.insert("userProfiles",{userId:`${role}-32`,tokenIdentifier:`${role}-32`,name:role,role,branchId:e.branchId,permissions:[],isActive:true});});const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});const beforeSnapshot=await codState(e);for(const role of ["Viewer","Sales"]){const actor=e.raw.withIdentity({subject:`${role.toLowerCase()}-32`,tokenIdentifier:`${role.toLowerCase()}-32`});await assert.rejects(actor.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:`deny-${role}`}),/صلاحية/);await assert.rejects(actor.query(api.deliveries.accountPicker,{branchId:e.branchId,purpose:"cod"}),/صلاحية/);await assert.rejects(actor.mutation(api.deliveries.createCodSettlement,{deliveryIds:[deliveryId],sourceAccountId:e.accountId,destinationAccountId:e.accountId,feeAmount:0,date:"2026-07-10",branchId:e.branchId,requestId:`settle-${role}`}),/صلاحية/);}assert.deepEqual(await codState(e),beforeSnapshot);});
test("COD-33 DTO الحساب المحدود وعزل الفرعين",async()=>{
  const e=await confirmationFixture(33,{paid:20}),other=await addConfirmationCase(e,"33-other"),otherBranchId=other.branchId;
  const ids=await e.raw.run(async ctx=>{await ctx.db.patch(e.accountId,{name:"active COD"});const add=(name:string,type:"cash"|"bank"|"cod_clearing"|"paymob_clearing",branchId:Id<"branches">,isActive=true)=>ctx.db.insert("financialAccounts",{name,code:name,uniqueKey:name,type,branchId,isActive,currentBalance:10,allowNegative:false,settlementDelayDays:0,createdAt:1,createdBy:"fixture",updatedAt:1});return{disabledCod:await add("disabled COD","cod_clearing",e.branchId,false),cash:await add("active cash","cash",e.branchId),bank:await add("active bank","bank",e.branchId),disabledDestination:await add("disabled cash","cash",e.branchId,false),forbiddenClearing:await add("clearing غير مسموح","paymob_clearing",e.branchId),otherCash:await add("other cash","cash",otherBranchId),otherBank:await add("other bank","bank",otherBranchId)};});
  const allowlist=["_id","branchId","name","type"].sort(),forbidden=["currentBalance","availableBalance","pendingBalance","uniqueKey","createdBy","createdAt","updatedAt","settlementDelayDays","allowNegative","allowNegativeBalance"];
  const codFirst=await e.t.query(api.deliveries.accountPicker,{branchId:e.branchId,purpose:"cod"}),codSecond=await e.t.query(api.deliveries.accountPicker,{branchId:otherBranchId,purpose:"cod"}),destinationFirst=await e.t.query(api.deliveries.accountPicker,{branchId:e.branchId,purpose:"destination"}),destinationSecond=await e.t.query(api.deliveries.accountPicker,{branchId:otherBranchId,purpose:"destination"});assert.deepEqual(codFirst.map(x=>x._id),[e.accountId]);assert.deepEqual(codSecond.map(x=>x._id),[other.accountId]);assert.deepEqual(new Set(destinationFirst.map(x=>x._id)),new Set([ids.cash,ids.bank]));assert.deepEqual(new Set(destinationSecond.map(x=>x._id)),new Set([ids.otherCash,ids.otherBank]));
  const all=[...codFirst,...codSecond,...destinationFirst,...destinationSecond];for(const dto of all){assert.deepEqual(Object.keys(dto).sort(),allowlist);for(const key of forbidden)assert.equal(key in dto,false);}assert.equal(all.some(x=>x._id===ids.disabledCod||x._id===ids.disabledDestination||x._id===ids.forbiddenClearing),false);assert.equal(codFirst.every(x=>x.branchId===e.branchId)&&destinationFirst.every(x=>x.branchId===e.branchId),true);assert.equal(codSecond.every(x=>x.branchId===otherBranchId)&&destinationSecond.every(x=>x.branchId===otherBranchId),true);
});
test("COD-34 Pagination وعزل Manager وسياسة Admin",async()=>{
  const e=await confirmationFixture(34,{paid:20}),firstCases=[await addConfirmationCase(e,"34-a",e.branchId),await addConfirmationCase(e,"34-b",e.branchId),await addConfirmationCase(e,"34-c",e.branchId)],secondFirst=await addConfirmationCase(e,"34-x"),otherBranchId=secondFirst.branchId,secondCases=[secondFirst,await addConfirmationCase(e,"34-z",otherBranchId)];
  await e.raw.run(ctx=>ctx.db.insert("userProfiles",{userId:"manager-34",tokenIdentifier:"manager-34",name:"Manager",role:"manager",branchId:e.branchId,permissions:[],isActive:true}));const Manager=e.raw.withIdentity({subject:"manager-34",tokenIdentifier:"manager-34"}),Admin=e.t,firstIds=[] as Id<"deliveries">[],secondIds=[] as Id<"deliveries">[];for(const row of firstCases)firstIds.push(await Admin.mutation(api.deliveries.createFromOrderInvoice,row.createArgs));for(const row of secondCases)secondIds.push(await Admin.mutation(api.deliveries.createFromOrderInvoice,row.createArgs));
  const allowlist=["_id","deliveryNumber","invoiceNumber","orderNumber","customerName","city","status","codAmount","prepaidAmount","shippingCompany","deliveredDate","branchId","accountingVersion","codSettlementId"],hidden=["requestId","idempotencyKey","requestFingerprint","confirmationRequestId","confirmationFingerprint","codFinancialTransactionId","codCustomerLedgerEntryId","currentConfirmationId","createdBy","cancelledBy","reversalRequestId","reversalFingerprint","financialTransactionId","customerLedgerEntryId"];
  async function paginate(actor:typeof Admin,branchId:Id<"branches">){let cursor:string|null=null,isDone=false;const seen:string[]=[],cursors:string[]=[];while(!isDone){const page=await actor.query(api.deliveries.listPaginated,{branchId,paginationOpts:{numItems:1,cursor}});assert.equal(page.page.length<=1,true);if(page.page[0]){assert.equal(seen.includes(String(page.page[0]._id)),false);seen.push(String(page.page[0]._id));const expected=allowlist.filter(key=>key in page.page[0]);assert.deepEqual(Object.keys(page.page[0]).sort(),expected.sort());for(const key of hidden)assert.equal(key in page.page[0],false);}assert.notEqual(page.continueCursor,cursor);cursors.push(page.continueCursor);cursor=page.continueCursor;isDone=page.isDone;}assert.equal(new Set(cursors).size,cursors.length);return seen;}
  const managerIds=await paginate(Manager,e.branchId);assert.deepEqual(new Set(managerIds),new Set(firstIds.map(String)));const managerPinned=await Manager.query(api.deliveries.listPaginated,{branchId:otherBranchId,paginationOpts:{numItems:1,cursor:null}});assert.equal(managerPinned.page.every(x=>x.branchId===e.branchId),true);assert.equal(managerPinned.page.some(x=>secondIds.includes(x._id)),false);
  const adminFirst=await paginate(Admin,e.branchId),adminSecond=await paginate(Admin,otherBranchId);assert.deepEqual(adminFirst,firstIds.map(String).reverse());assert.deepEqual(adminSecond,secondIds.map(String).reverse());assert.equal(new Set([...adminFirst,...adminSecond]).size,5);
});
test("COD-35 حماية الطباعة واسم المنشئ وDTO allowlist",async()=>{
  const e=await confirmationFixture(35,{paid:20}),tokenCase=await addConfirmationCase(e,"35-token",e.branchId),legacyCase=await addConfirmationCase(e,"35-legacy",e.branchId),other=await addConfirmationCase(e,"35-other"),otherBranchId=other.branchId;
  await e.raw.run(async ctx=>{await ctx.db.insert("userProfiles",{userId:"shipping-35",tokenIdentifier:"shipping-35",name:"Shipping printer",role:"shipping",branchId:e.branchId,permissions:[],isActive:true});await ctx.db.insert("userProfiles",{userId:"viewer-35",tokenIdentifier:"viewer-35",name:"مستخدم بلا صلاحية",role:"viewer",branchId:e.branchId,permissions:[],isActive:true});await ctx.db.insert("userProfiles",{userId:"accountant-35",tokenIdentifier:"accountant-35",name:"Accountant printer",role:"accountant",permissions:[],isActive:true});await ctx.db.insert("userProfiles",{userId:"different-user-35",tokenIdentifier:"token-creator-35",name:"منشئ بالرمز",role:"admin",permissions:[],isActive:true});});
  const Admin=e.t,Shipping=e.raw.withIdentity({subject:"shipping-35",tokenIdentifier:"shipping-35"}),Viewer=e.raw.withIdentity({subject:"viewer-35",tokenIdentifier:"viewer-35"}),Accountant=e.raw.withIdentity({subject:"accountant-35",tokenIdentifier:"accountant-35"}),byUserDelivery=await Admin.mutation(api.deliveries.createFromOrderInvoice,e.createArgs),byTokenDelivery=await Admin.mutation(api.deliveries.createFromOrderInvoice,tokenCase.createArgs),unknownDelivery=await Admin.mutation(api.deliveries.createFromOrderInvoice,legacyCase.createArgs),otherDelivery=await Admin.mutation(api.deliveries.createFromOrderInvoice,other.createArgs);
  await e.raw.run(async ctx=>{await ctx.db.patch(byTokenDelivery,{createdBy:"token-creator-35"});await ctx.db.patch(unknownDelivery,{createdBy:"legacy-missing-35"});});
  const beforeDenied=await e.raw.run(ctx=>ctx.db.get(byUserDelivery));await assert.rejects(Viewer.query(api.deliveries.printDelivery,{deliveryId:byUserDelivery}),/صلاحية/);assert.deepEqual(await e.raw.run(ctx=>ctx.db.get(byUserDelivery)),beforeDenied);
  const by_user=await Shipping.query(api.deliveries.printDelivery,{deliveryId:byUserDelivery}),by_token=await Shipping.query(api.deliveries.printDelivery,{deliveryId:byTokenDelivery}),unknown=await Shipping.query(api.deliveries.printDelivery,{deliveryId:unknownDelivery});assert.equal(by_user.employeeName,"مدير COD");assert.equal(by_token.employeeName,"منشئ بالرمز");assert.equal(unknown.employeeName,"مستخدم غير معروف");assert.notEqual(by_user.employeeName,"Shipping printer");assert.equal(JSON.stringify(unknown).includes("legacy-missing-35"),false);
  await assert.rejects(Shipping.query(api.deliveries.printDelivery,{deliveryId:otherDelivery}),/فرع/);assert.equal((await Admin.query(api.deliveries.printDelivery,{deliveryId:otherDelivery})).deliveryNumber!==undefined,true);assert.equal((await Accountant.query(api.deliveries.printDelivery,{deliveryId:otherDelivery})).deliveryNumber!==undefined,true);assert.notEqual(otherBranchId,e.branchId);
  const allowlist=["deliveryNumber","orderNumber","invoiceNumber","customerName","customerPhone","city","address","items","totalAmount","prepaidAmount","codAmount","expectedCarrierFee","shippingCompany","trackingNumber","status","deliveredDate","employeeName","reversalReason"],hidden=["_id","branchId","createdBy","requestId","idempotencyKey","requestFingerprint","confirmationRequestId","confirmationFingerprint","codFinancialTransactionId","codCustomerLedgerEntryId","currentConfirmationId","codSettlementId","reversalRequestId","reversalFingerprint"];for(const dto of [by_user,by_token,unknown]){const expected=allowlist.filter(key=>key in dto);assert.deepEqual(Object.keys(dto).sort(),expected.sort());for(const key of hidden)assert.equal(key in dto,false);}
});
test("COD-36 تسوية واحدة",async()=>{const e=await confirmationFixture(36,{paid:20});const destinationAccountId=await e.raw.run(ctx=>ctx.db.insert("financialAccounts",{name:"Cash",code:"C36",uniqueKey:"c36",type:"cash",branchId:e.branchId,isActive:true,currentBalance:10,allowNegative:false,settlementDelayDays:0,createdAt:1,createdBy:"x",updatedAt:1}));const deliveryId=await e.t.mutation(api.deliveries.createFromOrderInvoice,e.createArgs);await e.t.mutation(api.deliveries.updateStatus,{id:deliveryId,status:"shipped"});await e.t.mutation(api.deliveries.confirmDelivered,{deliveryId,codClearingAccountId:e.accountId,date:"2026-07-10",requestId:"confirm-36"});const before=await codState(e);const settlementId=await e.t.mutation(api.deliveries.createCodSettlement,{deliveryIds:[deliveryId],sourceAccountId:e.accountId,destinationAccountId,feeAmount:5,date:"2026-07-10",branchId:e.branchId,requestId:"settle-36"});const s=await e.raw.run(async ctx=>({settlements:await ctx.db.query("codSettlements").collect(),items:await ctx.db.query("codSettlementItems").collect(),delivery:await ctx.db.get(deliveryId),source:await ctx.db.get(e.accountId),destination:await ctx.db.get(destinationAccountId),tx:await ctx.db.query("financialTransactions").collect(),moves:await ctx.db.query("financialMovements").collect(),invoice:await ctx.db.get(e.invoiceId),ledger:await ctx.db.query("customerLedgerEntries").collect(),payments:await ctx.db.query("payments").collect()}));const settlement=s.settlements[0],item=s.items[0],settlementTx=s.tx.find(x=>x.type==="cod_settlement");assert.equal(settlement?._id,settlementId);assert.equal(settlement?.settlementNumber,"COD-2026-00001");assert.equal(settlement?.status,"posted");assert.equal(settlement?.grossAmount,80);assert.equal(settlement?.feeAmount,5);assert.equal(settlement?.netAmount,75);assert.equal(item?.deliveryId,deliveryId);assert.equal(item?.invoiceId,e.invoiceId);assert.equal(item?.confirmationId,before.delivery?.currentConfirmationId);assert.equal(s.delivery?.codSettlementId,settlementId);assert.equal(settlement?.financialTransactionId,settlementTx?._id);assert.deepEqual(s.moves.filter(m=>m.transactionId===settlementTx?._id).map(m=>m.signedAmount).sort((a,b)=>a-b),[-80,75]);assert.equal(s.source?.currentBalance,0);assert.equal(s.destination?.currentBalance,85);assert.deepEqual(s.invoice,before.invoice);assert.deepEqual(s.ledger,before.entries);assert.equal(s.payments.length,0);assert.equal(s.settlements.length,1);assert.equal(s.items.length,1);});
test("COD-37 تسوية Batch",async()=>{const e=await fixture(37,"shipped");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.shipped,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,37);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-38 الرسوم والصافي",async()=>{const e=await fixture(38,"delivered");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.delivered,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,38);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-39 منع ازدواج التسوية",async()=>{const e=await fixture(39,"returned");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.returned,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,39);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-40 Idempotency التسوية",async()=>{const e=await fixture(40,"cancelled");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.cancelled,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,40);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-41 رفض بصمة تسوية مختلفة",async()=>{const e=await fixture(41,"pending");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.pending,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,41);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-42 التحقق من الحسابات",async()=>{const e=await fixture(42,"shipped");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.shipped,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,42);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-43 مهلة الإتاحة",async()=>{const e=await fixture(43,"delivered");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.delivered,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,43);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-44 عكس التسوية",async()=>{const e=await fixture(44,"returned");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.returned,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,44);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-45 Idempotency العكس",async()=>{const e=await fixture(45,"cancelled");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.cancelled,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,45);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-46 Rollback رصيد الوجهة",async()=>{const e=await fixture(46,"pending");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.pending,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,46);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-47 عكس التأكيد",async()=>{const e=await fixture(47,"shipped");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.shipped,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,47);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-48 مراجعة Legacy بلا payments",async()=>{const e=await fixture(48,"delivered");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.delivered,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,48);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-49 إغلاق المسار القديم وDTO",async()=>{const e=await fixture(49);await assert.rejects(e.t.mutation(api.deliveries.create,{customerName:"x",customerPhone:"1",city:"x",address:"x",items:[],totalAmount:1,paymentMethod:"cod",shippingCompany:"x",shippingCost:0}),/المسار|القديم/);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.ok(dto);assert.equal("idempotencyKey" in dto,false);});
test("COD-50 قفل Snapshot التوصيل",async()=>{const e=await fixture(50);await assert.rejects(e.t.mutation(api.deliveries.update,{id:e.deliveryId,shippingCost:99}),/Object contains extra field|shippingCost/);const row=await e.raw.run(ctx=>ctx.db.get(e.deliveryId));assert.equal(row?.totalAmount,50);});
test("COD-51 ربط العربون الصفري",async()=>{const e=await fixture(51,"pending");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.pending,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,51);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-52 قفل الفاتورة النشطة",async()=>{const e=await fixture(52,"shipped");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.shipped,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,52);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-53 دقة القروش",async()=>{const e=await fixture(53);for(const amount of [1.001,-1,Number.NaN,Number.POSITIVE_INFINITY])await assert.rejects(e.t.mutation(api.deliveries.createFromOrderInvoice,{orderId:e.orderId,invoiceId:e.invoiceId,city:"x",address:"x",shippingCompany:"x",expectedCarrierFee:amount,branchId:e.branchId,date:"2026-07-26",requestId:`bad-${amount}`}),/منزلتين|رسوم/);assert.equal((await e.raw.run(ctx=>ctx.db.query("deliveries").collect())).length,1);});
test("COD-54 ترقيم COD الذري",async()=>{const e=await fixture(54,"returned");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.returned,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,54);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-55 تاريخ التأكيد وإعادة التأكيد",async()=>{const e=await fixture(55,"cancelled");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.cancelled,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,55);assert.equal("requestFingerprint" in (dto??{}),false);});
test("COD-56 إحصاءات COD وعزل الفروع",async()=>{const e=await fixture(56,"pending");const stats=await e.t.query(api.deliveries.getStats,{});assert.equal(stats.pending,1);assert.equal(stats.total,1);const dto=await e.t.query(api.deliveries.get,{id:e.deliveryId});assert.equal(dto?.totalAmount,56);assert.equal("requestFingerprint" in (dto??{}),false);});
