import test, { after, before } from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { symlink, unlink } from "./moduleLinkTestUtils.ts";
import { resolve } from "node:path";
import { convexTest } from "convex-test";
import schema from "../convex/schema.ts";
import { api } from "../convex/_generated/api.js";
import { PERMISSIONS, ROLE_PERMISSIONS } from "../convex/lib/permissions.ts";

const links = [["convex/_generated/server", "server.js"], ["convex/lib/auth", "auth.ts"], ["convex/lib/finance", "finance.ts"], ["convex/lib/documentNumbers", "documentNumbers.ts"], ["convex/lib/permissions", "permissions.ts"], ["convex/lib/references", "references.ts"], ["convex/lib/inventory", "inventory.ts"], ["shared/businessRules", "businessRules.ts"], ["shared/inventoryRules", "inventoryRules.ts"]] as const;
before(async () => { for (const [path, target] of links) if (!existsSync(resolve(path))) await symlink(target, resolve(path)); });
after(async () => { for (const [path] of links) if (existsSync(resolve(path))) await unlink(resolve(path)); });
const modules = { "../convex/_generated/api.js": () => import("../convex/_generated/api.js"), "../convex/_generated/server.js": () => import("../convex/_generated/server.js"), "../convex/finance.ts": () => import("../convex/finance.ts"), "../convex/orders.ts": () => import("../convex/orders.ts"), "../convex/orderPagination.ts": () => import("../convex/orderPagination.ts"), "../convex/expenses.ts": () => import("../convex/expenses.ts"), "../convex/auditLogs.ts": () => import("../convex/auditLogs.ts") };
const date = "2026-07-23";
async function setup() {
  const raw = convexTest(schema, modules);
  const ids = await raw.run(async ctx => {
    const branchId = await ctx.db.insert("branches", { name: "أ", address: "أ", isActive: true });
    const otherBranchId = await ctx.db.insert("branches", { name: "ب", address: "ب", isActive: true });
    await ctx.db.insert("financeSettings", { isInitialized: true, cutoverDate: date, defaultClearingDelayDays: 1, updatedAt: Date.now() });
    const customerId = await ctx.db.insert("customers", { name: "عميل", phone: "010", balance: 0, totalPurchases: 0, branchId, isActive: true }); return { branchId, otherBranchId, customerId };
  });
  return { raw, ...ids };
}
async function user(e: Awaited<ReturnType<typeof setup>>, id: string, role: string, permissions: string[], branchId = e.branchId) {
  await e.raw.run(ctx => ctx.db.insert("userProfiles", { userId: id, tokenIdentifier: id, name: id, role, branchId, permissions, isActive: true }));
  return e.raw.withIdentity({ subject: id, tokenIdentifier: id });
}
async function account(e: Awaited<ReturnType<typeof setup>>, name: string, balance: number, branchId = e.branchId, active = true) { return e.raw.run(ctx => ctx.db.insert("financialAccounts", { name, code: name, uniqueKey: `${branchId}:${name}`, type: "cash", branchId, isActive: active, currentBalance: balance, allowNegative: false, settlementDelayDays: 0, openingBalancePostedAt: Date.now(), createdAt: Date.now(), createdBy: "seed", updatedAt: Date.now() })); }
async function order(e: Awaited<ReturnType<typeof setup>>, deposit = 40) { return e.raw.run(async ctx => { if (deposit > 0) await ctx.db.insert("customerBalances", { key: `${e.customerId}:${e.branchId}`, customerId: e.customerId, branchId: e.branchId, receivableBalance: 0, advanceBalance: deposit, totalPurchases: 0, updatedAt: Date.now() }); return ctx.db.insert("orders", { orderNumber: `O-${deposit}`, customerId: e.customerId, customerName: "عميل", items: [], total: 100, deposit, remaining: 100 - deposit, status: "pending", branchId: e.branchId }); }); }
async function state(e: Awaited<ReturnType<typeof setup>>) { return e.raw.run(async ctx => ({ accounts: await ctx.db.query("financialAccounts").collect(), transactions: await ctx.db.query("financialTransactions").collect(), movements: await ctx.db.query("financialMovements").collect(), orders: await ctx.db.query("orders").collect(), expenses: await ctx.db.query("expenses").collect() })); }

test("shipping can view orders but cannot load collection accounts", async () => { const e = await setup(), t = await user(e, "shipping", "shipping", []); await order(e); assert.equal((await t.query(api.orderPagination.list, { paginationOpts: { numItems: 10, cursor: null } })).page.length, 1); await assert.rejects(t.query(api.finance.collectionAccountPicker, {}), /صلاحية/); });
test("customer service edit permission does not authorize collection", async () => { const e = await setup(), t = await user(e, "cs", "customer_service", []), a = await account(e, "C", 0), id = await order(e, 0); await assert.rejects(t.mutation(api.orders.addPayment, { id, amount: 5, accountId: a, paymentDate: date, requestId: "x" }), /صلاحية/); assert.equal((await state(e)).transactions.length, 0); });
test("sales can load collection picker and collect an order deposit", async () => { const e = await setup(), t = await user(e, "sales", "sales", []), a = await account(e, "C", 0), id = await order(e, 0); assert.equal((await t.query(api.finance.collectionAccountPicker, {})).length, 1); await t.mutation(api.orders.addPayment, { id, amount: 20, accountId: a, paymentDate: date, requestId: "pay" }); assert.equal((await state(e)).orders[0]?.deposit, 20); });
test("refund-only user can load refund picker", async () => { const e = await setup(), t = await user(e, "refund", "employee", ["refund_collections"]); await account(e, "C", 10); assert.equal((await t.query(api.finance.refundAccountPicker, {})).length, 1); });
test("refund-only user cannot load collection picker", async () => { const e = await setup(), t = await user(e, "refund", "employee", ["refund_collections"]); await assert.rejects(t.query(api.finance.collectionAccountPicker, {}), /صلاحية/); });
test("collection-only user cannot load refund picker", async () => { const e = await setup(), t = await user(e, "collect", "employee", ["record_collections"]); await assert.rejects(t.query(api.finance.refundAccountPicker, {}), /صلاحية/); });
test("account pickers expose no balances", async () => { const e = await setup(), t = await user(e, "both", "employee", ["record_collections", "refund_collections"]); await account(e, "C", 99); for (const row of [...await t.query(api.finance.collectionAccountPicker, {}), ...await t.query(api.finance.refundAccountPicker, {})]) { assert.deepEqual(Object.keys(row).sort(), ["_id", "branchId", "name", "type"]); assert.equal("currentBalance" in row, false); assert.equal("availableBalance" in row, false); assert.equal("pendingBalance" in row, false); } });
test("ordinary branch users cannot see another branch accounts", async () => { const e = await setup(), t = await user(e, "refund", "employee", ["refund_collections"]); await account(e, "A", 1); await account(e, "B", 1, e.otherBranchId); assert.deepEqual((await t.query(api.finance.refundAccountPicker, {})).map(x => x.name), ["A"]); });
test("admin and accountant retain cross-branch picker policy", async () => { const e = await setup(), admin = await user(e, "admin", "admin", []), accountant = await user(e, "accountant", "accountant", []); await account(e, "A", 1); await account(e, "B", 1, e.otherBranchId); assert.equal((await admin.query(api.finance.refundAccountPicker, {})).length, 2); assert.equal((await accountant.query(api.finance.refundAccountPicker, {})).length, 2); });
test("order refund atomically updates transaction movement account and order", async () => { const e = await setup(), t = await user(e, "refund", "employee", ["refund_collections"]), a = await account(e, "C", 50), id = await order(e); const before = await state(e); await t.mutation(api.orders.refundDeposit, { id, amount: 15, accountId: a, date, reason: " تصحيح ", requestId: "r" }); const after = await state(e); assert.equal(before.transactions.length, 0); assert.equal(after.transactions.length, 1); assert.equal(after.movements.length, 1); assert.equal(after.accounts[0]?.currentBalance, 35); assert.equal(after.orders[0]?.deposit, 25); assert.equal(after.orders[0]?.remaining, 75); });
test("order refund request id is idempotent", async () => { const e = await setup(), t = await user(e, "refund", "employee", ["refund_collections"]), a = await account(e, "C", 50), id = await order(e); const args = { id, amount: 10, accountId: a, date, reason: "تصحيح", requestId: "same" }; assert.equal(await t.mutation(api.orders.refundDeposit, args), await t.mutation(api.orders.refundDeposit, args)); const s = await state(e); assert.equal(s.transactions.length, 1); assert.equal(s.movements.length, 1); assert.equal(s.orders[0]?.deposit, 30); });
test("inactive refund account rejects with no effects", async () => { const e = await setup(), t = await user(e, "refund", "employee", ["refund_collections"]), a = await account(e, "C", 50, e.branchId, false), id = await order(e), before = await state(e); await assert.rejects(t.mutation(api.orders.refundDeposit, { id, amount: 10, accountId: a, date, reason: "x", requestId: "r" }), /معطل/); assert.deepEqual(await state(e), before); });
test("cross-branch refund account rejects with no effects", async () => { const e = await setup(), t = await user(e, "refund", "employee", ["refund_collections"]), a = await account(e, "C", 50, e.otherBranchId), id = await order(e), before = await state(e); await assert.rejects(t.mutation(api.orders.refundDeposit, { id, amount: 10, accountId: a, date, reason: "x", requestId: "r" }), /فرع/); assert.deepEqual(await state(e), before); });
test("insufficient refund balance rejects atomically", async () => { const e = await setup(), t = await user(e, "refund", "employee", ["refund_collections"]), a = await account(e, "C", 5), id = await order(e), before = await state(e); await assert.rejects(t.mutation(api.orders.refundDeposit, { id, amount: 10, accountId: a, date, reason: "x", requestId: "r" }), /الرصيد غير كاف/); assert.deepEqual(await state(e), before); });
test("expense creator without disbursement cannot pick or create", async () => { const e = await setup(), t = await user(e, "creator", "employee", ["create_expenses", "view_expenses"]), a = await account(e, "C", 50); await assert.rejects(t.query(api.finance.disbursementAccountPicker, {}), /صلاحية/); await assert.rejects(t.mutation(api.expenses.create, { title: "إيجار", category: "تشغيل", amount: 10, date, accountId: a, requestId: "r" }), /الصرف/); assert.equal((await state(e)).expenses.length, 0); });
test("disbursement user without create expense cannot create", async () => { const e = await setup(), t = await user(e, "payer", "employee", ["record_disbursements", "view_expenses"]), a = await account(e, "C", 50); await assert.rejects(t.mutation(api.expenses.create, { title: "إيجار", category: "تشغيل", amount: 10, date, accountId: a, requestId: "r" }), /صلاحية/); assert.equal((await state(e)).expenses.length, 0); });
test("print_orders is assigned only to required default roles", () => { assert.ok(PERMISSIONS.includes("print_orders")); for (const role of ["admin", "manager", "sales", "customer_service", "shipping"]) assert.ok(ROLE_PERMISSIONS[role]?.includes("print_orders"), role); for (const role of ["technician", "accountant", "viewer"]) assert.equal(ROLE_PERMISSIONS[role]?.includes("print_orders"), false, role); });

