import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";const page=readFileSync("src/components/PurchaseReturnsPage.tsx","utf8"),app=readFileSync("src/components/ERPApp.tsx","utf8"),sidebar=readFileSync("src/components/Sidebar.tsx","utf8");
test("PRT-UI-01 route and sidebar",()=>{assert.match(app,/purchase-returns/);assert.match(sidebar,/مرتجعات المشتريات/)});
test("PRT-UI-02 hooks are explicit top-level calls",()=>{assert.doesNotMatch(page,/const can\s*=\s*usePermission/);assert.equal((page.match(/usePermission\("[^"]+"\)/g)??[]).length,7)});
test("PRT-UI-03 admin branch selector",()=>{assert.match(page,/me\?\.role\s*===\s*"admin"/);assert.match(page,/aria-label="اختيار الفرع"/)});
test("PRT-UI-04 protected queries skip",()=>{assert.match(page,/canCreate\s*\?\s*\{\}\s*:\s*"skip"/);assert.match(page,/canPrint\s*&&\s*printId\s*\?\s*\{\s*purchaseReturnId:\s*printId\s*\}\s*:\s*"skip"/)});
test("PRT-UI-05 true pagination",()=>{assert.match(page,/usePaginatedQuery/);assert.match(page,/تحميل المزيد/)});
test("PRT-UI-06 external note is wired",()=>{assert.match(page,/\[externalCreditNoteNumber,\s*setExternalCreditNoteNumber\]/);assert.match(page,/externalCreditNoteNumber\s*\|\|\s*undefined/)});
test("PRT-UI-07 branch supplier receipt reset state",()=>{assert.match(page,/resetForm/);assert.match(page,/changeSupplier/);assert.match(page,/changeReceipt/);assert.match(page,/setQuantities\(\{\}\)/)});
test("PRT-UI-08 freight-only is enabled and empty is blocked",()=>assert.match(page,/!rawItems\.length\s*&&\s*freight\s*<=\s*0/));
test("PRT-UI-09 reversal modal reason date",()=>{assert.match(page,/role="dialog"/);assert.match(page,/reversalReason/);assert.match(page,/reversalDate/)});
test("PRT-UI-10 reversal request survives retry",()=>{assert.match(page,/reversalRequestId\.current/);assert.match(page,/openReverse/)});
test("PRT-UI-11 busy guards both writes",()=>{assert.match(page,/if\s*\(busy\s*\|\|\s*!receiptId/);assert.match(page,/if\s*\(busy\s*\|\|\s*!reverseRow/)});
test("PRT-UI-12 reverse mutation is called",()=>assert.match(page,/await reverse\(\{[\s\S]*purchaseReturnId/));
test("PRT-UI-13 print query and handler guard",()=>{assert.match(page,/api\.purchaseReturns\.getForPrint/);assert.match(page,/if\s*\(!canPrint\)/);assert.match(page,/canPrint\s*&&\s*<button/)});
test("PRT-UI-14 prompt is absent",()=>assert.doesNotMatch(page,/window\.prompt/));
test("PRT-UI-15 Convex errors are rendered",()=>{assert.match(page,/getErrorMessage\(caught\)/);assert.match(page,/setError\(message\)/)});
test("PRT-UI-16 line identity and limits",()=>{assert.match(page,/receiptItemIndex/);assert.match(page,/max=\{item\.availableQuantity\}/)});
test("PRT-UI-17 no unsafe TypeScript escapes",()=>assert.doesNotMatch(page,new RegExp(["as ","any|@ts","-ignore"].join(""))));
