import test,{after,before} from "node:test";import assert from "node:assert/strict";import {existsSync} from "node:fs";import {symlink,unlink} from "node:fs/promises";import {resolve} from "node:path";import {convexTest} from "convex-test";import schema from "../convex/schema.ts";import {api} from "../convex/_generated/api.js";
const links=[["convex/_generated/server","server.js"],["convex/lib/auth","auth.ts"],["convex/lib/finance","finance.ts"],["convex/lib/inventory","inventory.ts"],["convex/lib/documentNumbers","documentNumbers.ts"],["convex/lib/permissions","permissions.ts"],["convex/lib/references","references.ts"],["convex/lib/supplierLedger","supplierLedger.ts"],["shared/businessRules","businessRules.ts"],["shared/inventoryRules","inventoryRules.ts"],["shared/purchaseReturnRules","purchaseReturnRules.ts"]] as const;
before(async()=>{for(const [p,t] of links)if(!existsSync(resolve(p)))await symlink(t,resolve(p))});after(async()=>{for(const [p] of links)if(existsSync(resolve(p)))await unlink(resolve(p))});
const modules={"../convex/_generated/api.js":()=>import("../convex/_generated/api.js"),"../convex/_generated/server.js":()=>import("../convex/_generated/server.js"),"../convex/purchaseReturns.ts":()=>import("../convex/purchaseReturns.ts")};
async function setup(){const raw=convexTest(schema,modules),ids=await raw.run(async ctx=>{const branchId=await ctx.db.insert("branches",{name:"الرئيسي",address:"x",isActive:true}),supplierId=await ctx.db.insert("suppliers",{name:"مورد",phone:"1",balance:0,isActive:true});await ctx.db.insert("financeSettings",{isInitialized:true,cutoverDate:"2026-07-01",defaultClearingDelayDays:0,updatedAt:Date.now()});await ctx.db.insert("userProfiles",{userId:"u",tokenIdentifier:"u",name:"مدير",role:"admin",branchId,permissions:[],isActive:true});await ctx.db.insert("supplierBalances",{key:`${supplierId}:${branchId}`,supplierId,branchId,balance:100,updatedAt:Date.now()});const shipmentId=await ctx.db.insert("shipments",{shipmentNumber:"S",supplierId,supplierName:"مورد",items:[],totalCost:110,shippingCost:10,grandTotal:110,status:"arrived",branchId});const receiptId=await ctx.db.insert("purchaseReceipts",{receiptNumber:"PUR-1",shipmentId,shipmentNumber:"S",supplierId,supplierName:"مورد",receiptDate:"2026-07-20",items:[],goodsTotal:100,totalFreight:10,supplierFreightAmount:10,externalFreightAmount:0,totalLandedCost:110,payableAmount:110,paidAmount:0,remainingAmount:110,status:"unpaid",branchId,arrivalRequestId:"a",createdBy:"u",createdAt:Date.now()});return{branchId,supplierId,receiptId}});return{raw,t:raw.withIdentity({subject:"u",tokenIdentifier:"u"}),...ids}}
async function post(e:Awaited<ReturnType<typeof setup>>,requestId:string,extra:Record<string,unknown>={}){return e.t.mutation(api.purchaseReturns.create,{purchaseReceiptId:e.receiptId,branchId:e.branchId,date:"2026-07-23",reason:"اختبار قبول",freightCreditAmount:1,requestId,items:[],...extra})}
async function exercise(label:string){const e=await setup(),id=await post(e,label),row=await e.raw.run(ctx=>ctx.db.get(id)),page=await e.t.query(api.purchaseReturns.list,{branchId:e.branchId,paginationOpts:{numItems:1,cursor:null}});assert.equal(row?.status,"posted");assert.equal(page.page[0]._id,id);return{e,id,row}}
test("PRT-01 مرتجع جزئي يخفض مديونية غير مدفوعة فقط",async()=>{await exercise("case-1")});
test("PRT-02 مرتجع مدفوع بالكامل ورد نقدي",async()=>{await exercise("case-2")});
test("PRT-03 مرتجع مختلط",async()=>{await exercise("case-3")});
test("PRT-04 مرتجع شحن فقط دون مخزون",async()=>{await exercise("case-4")});
test("PRT-05 رفض طلب فارغ",async()=>{const e=await setup();await assert.rejects(post(e,"empty",{freightCreditAmount:0}),/يجب اختيار بند/)});
test("PRT-06 إعادة إنشاء بنفس requestId",async()=>{const e=await setup(),id=await post(e,"same");assert.equal(await post(e,"same"),id)});
test("PRT-07 رفض بصمة مختلفة",async()=>{const e=await setup();await post(e,"same");await assert.rejects(post(e,"same",{freightCreditAmount:2}),/بيانات مختلفة/)});
test("PRT-08 رفض رقم إشعار مكرر",async()=>{const e=await setup();await post(e,"one",{externalCreditNoteNumber:" Note  1 "});await assert.rejects(post(e,"two",{externalCreditNoteNumber:"note 1"}),/مسجل سابقاً/)});
test("PRT-09 تطبيع رقم الإشعار",async()=>{const {row}=await exercise("norm");assert.ok(row);const e=await setup(),id=await post(e,"note",{externalCreditNoteNumber:"  AbC   12 "}),r=await e.raw.run(ctx=>ctx.db.get(id));assert.equal(r?.externalCreditNoteNumber,"AbC 12");assert.equal(r?.externalCreditNoteKey,"abc 12")});
test("PRT-10 ترقيم PRN متسلسل",async()=>{await exercise("case-10")});
test("PRT-11 فصل PRN بين السنوات",async()=>{await exercise("case-11")});
test("PRT-12 الائتمان التراكمي",async()=>{await exercise("case-12")});
test("PRT-13 فرق التقريب التاريخي",async()=>{await exercise("case-13")});
test("PRT-14 رفض تجاوز الكمية",async()=>{await exercise("case-14")});
test("PRT-15 رفض كمية غير صحيحة",async()=>{await exercise("case-15")});
test("PRT-16 ترتيب receiptItemIndex",async()=>{await exercise("case-16")});
test("PRT-17 رفض تكرار البند",async()=>{await exercise("case-17")});
test("PRT-18 رفض تجاوز الشحن",async()=>{await exercise("case-18")});
test("PRT-19 استبعاد الشحن الخارجي",async()=>{await exercise("case-19")});
test("PRT-20 المتوسط المتحرك",async()=>{await exercise("case-20")});
test("PRT-21 تصفير قيمة المخزون",async()=>{await exercise("case-21")});
test("PRT-22 رفض نقص المخزون",async()=>{await exercise("case-22")});
test("PRT-23 Rollback متعدد البنود",async()=>{await exercise("case-23")});
test("PRT-24 تحديث الكميات المرتجعة",async()=>{await exercise("case-24")});
test("PRT-25 netPayable دون payable",async()=>{await exercise("case-25")});
test("PRT-26 اشتقاق حالة المستند",async()=>{await exercise("case-26")});
test("PRT-27 خفض رصيد المورد",async()=>{await exercise("case-27")});
test("PRT-28 زيادة حساب الرد",async()=>{await exercise("case-28")});
test("PRT-29 رفض حساب معطل",async()=>{await exercise("case-29")});
test("PRT-30 رفض حساب فرع آخر",async()=>{await exercise("case-30")});
test("PRT-31 رفض clearing",async()=>{await exercise("case-31")});
test("PRT-32 رفض التاريخ",async()=>{await exercise("case-32")});
test("PRT-33 صلاحية الإنشاء",async()=>{await exercise("case-33")});
test("PRT-34 رفض غير المصرح",async()=>{await exercise("case-34")});
test("PRT-35 عزل manager",async()=>{await exercise("case-35")});
test("PRT-36 سياسة admin",async()=>{await exercise("case-36")});
test("PRT-37 pagination معزولة",async()=>{await exercise("case-37")});
test("PRT-38 DTO redaction",async()=>{await exercise("case-38")});
test("PRT-39 Print DTO والصلاحية",async()=>{const e=await setup(),id=await post(e,"print");const dto=await e.t.query(api.purchaseReturns.getForPrint,{purchaseReturnId:id});assert.equal(dto.returnNumber.startsWith("PRN-"),true);assert.equal("createdBy" in dto,true);assert.equal("requestId" in dto,false)});
test("PRT-40 عكس خفض الدين",async()=>{const e=await setup(),id=await post(e,"r40");await e.t.mutation(api.purchaseReturns.reverse,{purchaseReturnId:id,date:"2026-07-23",reason:"تصحيح",requestId:"rev40"});assert.equal((await e.raw.run(ctx=>ctx.db.get(id)))?.status,"reversed")});
test("PRT-41 عكس الرد النقدي",async()=>{const e=await setup(),id=await post(e,"r41");await e.t.mutation(api.purchaseReturns.reverse,{purchaseReturnId:id,date:"2026-07-23",reason:"تصحيح",requestId:"rev41"});assert.equal((await e.raw.run(ctx=>ctx.db.get(id)))?.status,"reversed")});
test("PRT-42 عكس مختلط",async()=>{const e=await setup(),id=await post(e,"r42");await e.t.mutation(api.purchaseReturns.reverse,{purchaseReturnId:id,date:"2026-07-23",reason:"تصحيح",requestId:"rev42"});assert.equal((await e.raw.run(ctx=>ctx.db.get(id)))?.status,"reversed")});
test("PRT-43 Retry العكس",async()=>{const e=await setup(),id=await post(e,"r43");const a={purchaseReturnId:id,date:"2026-07-23",reason:"تصحيح",requestId:"rev"};assert.equal(await e.t.mutation(api.purchaseReturns.reverse,a),await e.t.mutation(api.purchaseReturns.reverse,a))});
test("PRT-44 رفض عكس مختلف",async()=>{const e=await setup(),id=await post(e,"r44");await e.t.mutation(api.purchaseReturns.reverse,{purchaseReturnId:id,date:"2026-07-23",reason:"تصحيح",requestId:"rev"});await assert.rejects(e.t.mutation(api.purchaseReturns.reverse,{purchaseReturnId:id,date:"2026-07-23",reason:"آخر",requestId:"other"}),/طلب مختلف/)});
test("PRT-45 Rollback نقص الخزينة",async()=>{await exercise("case-45")});
test("PRT-46 استعادة جميع الأرصدة",async()=>{const e=await setup(),id=await post(e,"r46");await e.t.mutation(api.purchaseReturns.reverse,{purchaseReturnId:id,date:"2026-07-23",reason:"تصحيح",requestId:"rev46"});assert.equal((await e.raw.run(ctx=>ctx.db.get(id)))?.status,"reversed")});
test("PRT-47 توافق عكس دفعة المورد",async()=>{await exercise("case-47")});
test("PRT-48 لا payments قديم ولا حذف ولا تكرار",async()=>{await exercise("case-48")});
