import test, { after, before } from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs"; import { symlink, unlink } from "node:fs/promises"; import { resolve } from "node:path";
import { convexTest } from "convex-test"; import schema from "../convex/schema.ts"; import { api } from "../convex/_generated/api.js";
const links=[["convex/_generated/server","server.js"],["convex/lib/auth","auth.ts"],["convex/lib/finance","finance.ts"],["convex/lib/documentNumbers","documentNumbers.ts"],["convex/lib/permissions","permissions.ts"],["convex/lib/references","references.ts"],["convex/lib/inventory","inventory.ts"],["convex/lib/supplierLedger","supplierLedger.ts"],["shared/businessRules","businessRules.ts"],["shared/inventoryRules","inventoryRules.ts"]] as const;
before(async()=>{for(const [p,t] of links)if(!existsSync(resolve(p)))await symlink(t,resolve(p));});after(async()=>{for(const [p] of links)if(existsSync(resolve(p)))await unlink(resolve(p));});
const modules={"../convex/_generated/api.js":()=>import("../convex/_generated/api.js"),"../convex/_generated/server.js":()=>import("../convex/_generated/server.js"),"../convex/shipments.ts":()=>import("../convex/shipments.ts"),"../convex/suppliers.ts":()=>import("../convex/suppliers.ts")};
async function setup(options:{supplierActive?:boolean;productBranchMismatch?:boolean;permissions?:string[];status?:string;supplier?:boolean}={}){const raw=convexTest(schema,modules);const x=await raw.run(async ctx=>{const branchId=await ctx.db.insert("branches",{name:"فرع",address:"x",isActive:true});const other=await ctx.db.insert("branches",{name:"آخر",address:"x",isActive:true});await ctx.db.insert("financeSettings",{isInitialized:true,cutoverDate:"2026-07-01",defaultClearingDelayDays:0,updatedAt:Date.now()});await ctx.db.insert("userProfiles",{userId:"u",tokenIdentifier:"u",name:"مستخدم",role:options.permissions?"viewer":"admin",branchId,permissions:options.permissions??[],isActive:true});const supplierId=await ctx.db.insert("suppliers",{name:"مورد",phone:"1",balance:77,isActive:options.supplierActive!==false});const productId=await ctx.db.insert("products",{name:"أ",sku:crypto.randomUUID(),costPrice:1,inventoryValue:10,sellPrice:2,stock:10,minStock:0,unit:"قطعة",branchId:options.productBranchMismatch?other:branchId,isActive:true});const product2Id=await ctx.db.insert("products",{name:"ب",sku:crypto.randomUUID(),costPrice:1,inventoryValue:10,sellPrice:2,stock:10,minStock:0,unit:"قطعة",branchId,isActive:true});const shipmentId=await ctx.db.insert("shipments",{shipmentNumber:"SHP-2026-00001",supplierId:options.supplier===false?undefined:supplierId,supplierName:"قديم",items:[{productId,productName:"قديم",quantity:3,unitCost:10,total:30},{productId:product2Id,productName:"قديم",quantity:1,unitCost:20,total:20}],totalCost:50,shippingCost:10,grandTotal:60,status:options.status??"in_transit",branchId});return{branchId,other,supplierId,productId,product2Id,shipmentId};});return{raw,t:raw.withIdentity({subject:"u",tokenIdentifier:"u"}),...x};}
const args=(e:Awaited<ReturnType<typeof setup>>,requestId="r",supplierFreightAmount=4)=>({shipmentId:e.shipmentId,receiptDate:"2026-07-23",requestId,supplierFreightAmount});
async function state(e:Awaited<ReturnType<typeof setup>>){return e.raw.run(async ctx=>({receipts:await ctx.db.query("purchaseReceipts").collect(),ledger:await ctx.db.query("supplierLedgerEntries").collect(),balances:await ctx.db.query("supplierBalances").collect(),movements:await ctx.db.query("inventoryMovements").collect(),products:await ctx.db.query("products").collect(),transactions:await ctx.db.query("financialTransactions").collect(),payments:await ctx.db.query("payments").collect(),shipment:await ctx.db.get(e.shipmentId),supplier:await ctx.db.get(e.supplierId)}));}
test("PUR-01 posts numbered receipt, stock, ledger, balance and links atomically",async()=>{const e=await setup(),r=await e.t.mutation(api.shipments.receive,args(e)),s=await state(e);assert.match(r.receiptNumber!,/^PUR-2026-\d{5}$/);assert.deepEqual([s.receipts.length,s.movements.length,s.ledger.length,s.balances[0].balance,s.shipment?.purchaseReceiptId,s.receipts[0].supplierLedgerEntryId],[1,2,1,54,s.receipts[0]._id,s.ledger[0]._id]);assert.deepEqual([s.transactions.length,s.payments.length,s.supplier?.balance],[0,0,77]);});
test("PUR-02 retry returns one receipt and a different request is rejected",async()=>{const e=await setup(),a=await e.t.mutation(api.shipments.receive,args(e)),b=await e.t.mutation(api.shipments.receive,args(e));assert.equal(a.purchaseReceiptId,b.purchaseReceiptId);assert.equal((await state(e)).ledger.length,1);await assert.rejects(e.t.mutation(api.shipments.receive,args(e,"other")),/طلب مختلف/);});
test("PUR-03 landed freight is fully allocated with remainder on last eligible line",async()=>{const e=await setup();await e.t.mutation(api.shipments.receive,{...args(e),supplierFreightAmount:0});const s=await state(e),r=s.receipts[0];assert.equal(r.items.reduce((n,i)=>n+i.allocatedFreight,0),10);assert.deepEqual(r.items.map(i=>i.allocatedFreight),[6,4]);assert.deepEqual([r.payableAmount,r.externalFreightAmount,r.totalLandedCost],[50,10,60]);});
test("PUR-04 full supplier freight increases payable while external freight only increases inventory",async()=>{const e=await setup();await e.t.mutation(api.shipments.receive,args(e,"full",10));const r=(await state(e)).receipts[0];assert.deepEqual([r.payableAmount,r.externalFreightAmount,r.totalLandedCost],[60,0,60]);});
test("PUR-05 ledger snapshots balances and does not alter legacy supplier balance",async()=>{const e=await setup();await e.t.mutation(api.shipments.receive,args(e));const s=await state(e);assert.deepEqual([s.ledger[0].balanceBefore,s.ledger[0].balanceAfter,s.supplier?.balance],[0,54,77]);});
for(const [name,options,pattern] of [["disabled supplier",{supplierActive:false},/معطل/],["missing supplier",{supplier:false},/دون مورد/],["cross branch product",{productBranchMismatch:true},/فرعها/]] as const)test(`PUR rollback: ${name}`,async()=>{const e=await setup(options),before=await state(e);await assert.rejects(e.t.mutation(api.shipments.receive,args(e)),pattern);assert.deepEqual(await state(e),before);});
test("PUR-09 validates cutover, date, due date and duplicate supplier invoice",async()=>{const e=await setup();for(const a of [{...args(e),receiptDate:"bad"},{...args(e),receiptDate:"2026-06-30"},{...args(e),dueDate:"2026-07-01",invoiceDate:"2026-07-22"}])await assert.rejects(e.t.mutation(api.shipments.receive,a));await e.t.mutation(api.shipments.receive,{...args(e),externalInvoiceNumber:" INV  1 "});const second=await e.raw.run(ctx=>ctx.db.insert("shipments",{shipmentNumber:"SHP-2",supplierId:e.supplierId,supplierName:"مورد",items:[{productId:e.productId,productName:"أ",quantity:1,unitCost:1,total:1}],totalCost:1,shippingCost:0,grandTotal:1,status:"in_transit",branchId:e.branchId}));await assert.rejects(e.t.mutation(api.shipments.receive,{shipmentId:second,receiptDate:"2026-07-23",requestId:"second",supplierFreightAmount:0,externalInvoiceNumber:"inv 1"}),/مستخدم/);});
test("PUR-10 permissions and updateStatus cannot bypass receipt posting",async()=>{const e=await setup({permissions:["edit_shipments","view_shipments"]});await assert.rejects(e.t.mutation(api.shipments.receive,args(e)),/post_purchase_receipts/);await assert.rejects(e.t.mutation(api.shipments.updateStatus,{id:e.shipmentId,status:"arrived"}),/استخدم عملية استلام/);assert.equal((await state(e)).receipts.length,0);});
test("PUR-11 supplier list redacts legacy balance",async()=>{const e=await setup({permissions:["view_suppliers"]});const rows=await e.t.query(api.suppliers.list,{});assert.equal("balance" in rows[0],false);});
test("PUR-12 legacy review identifies unposted arrivals without migrating",async()=>{const e=await setup({status:"arrived"});const review=await e.t.query(api.suppliers.legacyReview,{});assert.equal(review.arrivedWithoutPurchaseReceiptCount,1);assert.equal((await state(e)).ledger.length,0);});
