import test from "node:test"; import assert from "node:assert/strict"; import { readFile } from "node:fs/promises";
const source=await readFile("src/components/SupplierPaymentsPage.tsx","utf8");
const has=(value:string)=>assert.ok(source.includes(value),value);
test("UI-01 uses supplierPayments.create mutation",()=>has("api.supplierPayments.create"));
test("UI-02 uses supplierPayments.reverse mutation",()=>has("api.supplierPayments.reverse"));
test("UI-03 executes the protected supplierPayments.print query",()=>{has("useQuery(api.supplierPayments.print");has("canPrint && printPaymentId")});
test("UI-04 gates disbursement picker on both permissions",()=>has("canRecord && canDisburse ? {} : \"skip\""));
test("UI-05 skips ledger list without ledger permission",()=>has("canLedger && effectiveBranchId ? { branchId: effectiveBranchId } : \"skip\""));
test("UI-06 skips payment queries without a branch",()=>{has("supplierId && effectiveBranchId && canRecord");has("supplierId && effectiveBranchId && canLedger")});
test("UI-07 sends branchId to create mutation",()=>has("branchId: effectiveBranchId || undefined"));
test("UI-08 filters disbursement accounts by selected branch",()=>has("accounts.filter(account => account.branchId === effectiveBranchId)"));
test("UI-09 never displays account balances",()=>{for(const token of ["currentBalance","availableBalance","pendingBalance"])assert.equal(source.includes(token),false)});
test("UI-10 keeps create request stable while retrying",()=>{has("requestId: createRequest.current");has("if (busy")});
test("UI-11 rotates create request only after success",()=>assert.ok(source.indexOf("await createPayment")<source.indexOf("createRequest.current = requestId()")));
test("UI-12 keeps reversal request stable while retrying",()=>has("requestId: reverseRequest.current"));
test("UI-13 prevents double create and reversal submission",()=>{has("if (busy || !supplierId");has("if (busy || !reversePayment)")});
test("UI-14 displays normalized backend errors",()=>has("toast.error(getErrorMessage(error))"));
test("UI-15 print handler has a final permission guard",()=>has("if (!canPrint) { toast.error(\"ليس لديك صلاحية طباعة سندات الموردين\")"));
test("UI-16 sends no denormalized or total fields",()=>{for(const token of ["totalAmount:","supplierName:","receiptNumber:"])assert.equal(source.includes(token),false)});
test("UI-17 contains no unsafe TypeScript escape",()=>{assert.equal(source.includes("as " + "any"),false);assert.equal(source.includes("@ts" + "-ignore"),false)});
test("UI-18 prints real voucher fields instead of a payment link",()=>{for(const token of ["printDto.paymentNumber","printDto.supplierName","printDto.allocations","الحساب المصروف منه","توقيع المستلم","توقيع المراجع"])has(token);assert.equal(source.includes("#supplier-payment="),false)});
