import { randomUUID } from 'node:crypto'
import type { PoolClient } from 'pg'

export const POSTING_OPERATION_TYPES = [
  'POST',
  'CORRECTION',
  'REVERSAL',
  'DELETE_REVERSAL',
] as const

export type PostingOperationType = (typeof POSTING_OPERATION_TYPES)[number]

const POSTING_OPERATION_TYPE_SET = new Set<string>(POSTING_OPERATION_TYPES)

export interface CreatePostingBatchInput {
  branchId: string
  sourceType: string
  sourceId: string
  operationType: PostingOperationType
  documentVersion: number
  reversesPostingBatchId?: string | null
  createdBy: string
}

export interface PostingBatch {
  id: string
  branchId: string
  sourceType: string
  sourceId: string
  operationType: PostingOperationType
  documentVersion: number
  reversesPostingBatchId: string | null
  postedAt: Date
  createdBy: string
}

interface StoredPostingBatchRow {
  id: string
  branch_id: string
  source_type: string
  source_id: string
  operation_type: PostingOperationType
  document_version: number
  reverses_posting_batch_id: string | null
  posted_at: Date
  created_by: string
}

interface ReferencedPostingBatchRow {
  id: string
  branch_id: string
  source_type: string
  source_id: string
}

export type PostingBatchReferenceErrorReason =
  | 'REFERENCE_REQUIRED'
  | 'REFERENCE_NOT_FOUND'
  | 'REFERENCE_SCOPE_MISMATCH'
  | 'POST_CANNOT_REFERENCE_REVERSAL'

export class PostingBatchReferenceError extends Error {
  readonly code = 'POSTING_BATCH_REFERENCE_ERROR'

  constructor(
    readonly reason: PostingBatchReferenceErrorReason,
    readonly referenceId: string | null,
  ) {
    super(`Posting batch reference error: ${reason}`)
    this.name = 'PostingBatchReferenceError'
  }
}

function requireNonBlank(name: string, value: string): void {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new TypeError(`${name} must be a non-empty string`)
  }
}

function validateInput(input: CreatePostingBatchInput): void {
  requireNonBlank('Posting batch branchId', input.branchId)
  requireNonBlank('Posting batch sourceType', input.sourceType)
  requireNonBlank('Posting batch sourceId', input.sourceId)
  requireNonBlank('Posting batch createdBy', input.createdBy)

  if (!POSTING_OPERATION_TYPE_SET.has(input.operationType)) {
    throw new TypeError(
      `Posting batch operationType must be one of ${POSTING_OPERATION_TYPES.join(', ')}`,
    )
  }

  if (!Number.isInteger(input.documentVersion) || input.documentVersion < 1) {
    throw new RangeError(
      'Posting batch documentVersion must be a positive integer',
    )
  }

  const reversalReference = input.reversesPostingBatchId ?? null

  if (input.operationType === 'POST' && reversalReference !== null) {
    throw new PostingBatchReferenceError(
      'POST_CANNOT_REFERENCE_REVERSAL',
      reversalReference,
    )
  }

  if (
    (input.operationType === 'REVERSAL' ||
      input.operationType === 'DELETE_REVERSAL') &&
    reversalReference === null
  ) {
    throw new PostingBatchReferenceError('REFERENCE_REQUIRED', null)
  }
}

function mapPostingBatch(row: StoredPostingBatchRow): PostingBatch {
  return {
    id: row.id,
    branchId: row.branch_id,
    sourceType: row.source_type,
    sourceId: row.source_id,
    operationType: row.operation_type,
    documentVersion: row.document_version,
    reversesPostingBatchId: row.reverses_posting_batch_id,
    postedAt: row.posted_at,
    createdBy: row.created_by,
  }
}

async function lockAndValidateReference(
  client: PoolClient,
  input: CreatePostingBatchInput,
): Promise<void> {
  const referenceId = input.reversesPostingBatchId ?? null
  if (referenceId === null) return

  requireNonBlank('Posting batch reversesPostingBatchId', referenceId)

  const result = await client.query<ReferencedPostingBatchRow>(
    `SELECT id, branch_id, source_type, source_id
       FROM posting_batches
      WHERE id = $1
      FOR UPDATE`,
    [referenceId],
  )

  const referenced = result.rows[0]
  if (!referenced) {
    throw new PostingBatchReferenceError('REFERENCE_NOT_FOUND', referenceId)
  }

  if (
    referenced.branch_id !== input.branchId ||
    referenced.source_type !== input.sourceType ||
    referenced.source_id !== input.sourceId
  ) {
    throw new PostingBatchReferenceError(
      'REFERENCE_SCOPE_MISMATCH',
      referenceId,
    )
  }
}

/**
 * Creates the canonical trace row for one business posting.
 *
 * The caller owns the business transaction. This service intentionally accepts
 * only an existing PoolClient so the posting batch and its inventory/financial/
 * ledger/journal effects can commit or roll back atomically.
 *
 * posted_at is always generated by PostgreSQL at execution time; callers cannot
 * backdate the posting order through this service.
 */
export class PostingBatchService {
  async create(
    client: PoolClient,
    input: CreatePostingBatchInput,
  ): Promise<PostingBatch> {
    validateInput(input)
    await lockAndValidateReference(client, input)

    const id = randomUUID()
    const result = await client.query<StoredPostingBatchRow>(
      `INSERT INTO posting_batches
        (id,branch_id,source_type,source_id,operation_type,document_version,
         reverses_posting_batch_id,posted_at,created_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7,clock_timestamp(),$8)
       RETURNING
         id,
         branch_id,
         source_type,
         source_id,
         operation_type,
         document_version,
         reverses_posting_batch_id,
         posted_at,
         created_by`,
      [
        id,
        input.branchId,
        input.sourceType,
        input.sourceId,
        input.operationType,
        input.documentVersion,
        input.reversesPostingBatchId ?? null,
        input.createdBy,
      ],
    )

    const row = result.rows[0]
    if (!row) {
      throw new Error(
        'Posting batch creation invariant failed: no row returned',
      )
    }

    return mapPostingBatch(row)
  }
}
