/**
 * Single Source of Truth for all permissions and role-permission mappings.
 * Backend modules MUST use the exact permission strings defined here.
 * Frontend components import the same list for UI gating.
 */

export const PERMISSIONS = [
  // ── View ──
  "view_products",
  "view_customers",
  "view_orders",
  "view_invoices",
  "view_repairs",
  "view_shipments",
  "view_deliveries",
  "view_suppliers",
  "view_expenses",
  "view_leads",
  "view_branches",
  "view_employees",
  "view_reports",
  "view_audit_logs",
  "view_prices",
  "view_profits",
  "view_finance",
  "view_supplier_ledger",
  "view_customer_ledger",
  "view_general_ledger", "initialize_general_ledger", "manage_chart_of_accounts",
  "post_manual_journals", "reverse_journal_entries", "close_accounting_periods",
  "reopen_accounting_periods", "print_general_ledger",
  "initialize_customer_ledger",
  "print_customer_statements",
  "post_purchase_receipts",
  "manage_financial_accounts",
  "initialize_finance",
  "record_collections",
  "record_disbursements",
  "record_supplier_payments",
  "reverse_supplier_payments",
  "print_supplier_payments",
  "transfer_funds",
  "settle_clearing_accounts",
  "refund_collections",
  "reverse_financial_transactions",
  "view_financial_reports",
  "view_sales_returns", "create_sales_returns", "print_credit_notes",
  "view_purchase_returns", "create_purchase_returns", "reverse_purchase_returns", "print_purchase_returns", "record_supplier_refunds",
  "confirm_cod_deliveries", "view_cod_settlements", "settle_cod_collections", "reverse_cod_collections", "print_cod_settlements",
  // ── Create ──
  "create_products",
  "create_customers",
  "create_orders",
  "create_invoices",
  "create_repairs",
  "create_shipments",
  "create_deliveries",
  "create_suppliers",
  "create_expenses",
  "create_leads",
  // ── Edit ──
  "edit_products",
  "edit_customers",
  "edit_orders",
  "edit_invoices",
  "edit_repairs",
  "edit_shipments",
  "edit_deliveries",
  "edit_suppliers",
  "edit_expenses",
  "edit_leads",
  // ── Delete ──
  "delete_products",
  "delete_customers",
  "delete_orders",
  "delete_invoices",
  "delete_repairs",
  "delete_shipments",
  "delete_deliveries",
  "delete_suppliers",
  "delete_expenses",
  "delete_leads",
  // ── Admin-only ──
  "manage_users",
  "manage_settings",
  "manage_branches",
  // ── Other ──
  "export_data",
  "print_invoices",
  "print_orders",
  "print_repairs",
  "print_shipping",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export function isPermission(value: string): value is Permission {
  return PERMISSIONS.includes(value as Permission);
}

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [...PERMISSIONS],
  manager: [
    "view_general_ledger", "print_general_ledger",
    "view_products", "view_customers", "view_orders", "view_invoices",
    "view_repairs", "view_shipments", "view_deliveries", "view_suppliers",
    "view_expenses", "view_leads", "view_branches", "view_reports",
    "view_prices", "view_profits",
    "create_products", "create_customers", "create_orders", "create_invoices",
    "create_repairs", "create_shipments", "create_deliveries", "create_suppliers",
    "create_expenses", "create_leads",
    "edit_products", "edit_customers", "edit_orders", "edit_invoices",
    "edit_repairs", "edit_shipments", "edit_deliveries", "edit_suppliers",
    "edit_expenses", "edit_leads",
    "export_data", "print_invoices", "print_orders", "print_repairs", "print_shipping",
    "view_finance", "record_collections", "record_disbursements", "transfer_funds", "view_financial_reports",
    "view_sales_returns", "create_sales_returns", "print_credit_notes",
    "view_supplier_ledger", "post_purchase_receipts", "record_supplier_payments", "print_supplier_payments",
    "view_customer_ledger", "print_customer_statements",
    "view_purchase_returns", "create_purchase_returns", "print_purchase_returns", "record_supplier_refunds",
    "confirm_cod_deliveries", "view_cod_settlements", "settle_cod_collections", "print_cod_settlements",
  ],
  sales: [
    "view_products", "view_customers", "view_orders", "view_invoices",
    "view_prices",
    "create_orders", "create_invoices", "create_customers",
    "edit_orders",
    "print_invoices", "print_orders",
    "record_collections",
  ],
  customer_service: [
    "view_customers", "view_orders", "view_repairs",
    "create_customers", "edit_customers",
    "create_orders", "edit_orders",
    "create_repairs",
    "view_prices", "print_orders",
  ],
  technician: [
    "view_repairs", "view_products", "view_prices",
    "create_repairs", "edit_repairs",
    "print_repairs",
  ],
  accountant: [
    "view_general_ledger", "initialize_general_ledger", "manage_chart_of_accounts", "post_manual_journals", "reverse_journal_entries", "close_accounting_periods", "reopen_accounting_periods", "print_general_ledger",
    "view_products", "view_customers", "view_invoices", "view_expenses",
    "view_reports", "view_prices", "view_profits",
    "create_expenses", "edit_expenses",
    "export_data",
    "view_finance", "manage_financial_accounts", "initialize_finance", "record_collections",
    "record_disbursements", "transfer_funds", "settle_clearing_accounts",
    "refund_collections", "reverse_financial_transactions", "view_financial_reports",
    "view_sales_returns", "create_sales_returns", "print_credit_notes",
    "view_supplier_ledger", "post_purchase_receipts", "record_supplier_payments", "reverse_supplier_payments", "print_supplier_payments",
    "view_customer_ledger", "initialize_customer_ledger", "print_customer_statements",
    "view_purchase_returns", "create_purchase_returns", "reverse_purchase_returns", "print_purchase_returns", "record_supplier_refunds",
    "view_cod_settlements", "settle_cod_collections", "reverse_cod_collections", "print_cod_settlements",
  ],
  shipping: [
    "view_orders", "view_shipments", "view_deliveries",
    "create_shipments", "edit_shipments",
    "create_deliveries", "edit_deliveries",
    "print_shipping", "print_orders",
    "post_purchase_receipts",
    "confirm_cod_deliveries", "print_cod_settlements",
  ],
  viewer: [
    "view_products", "view_customers", "view_orders",
    "view_repairs", "view_invoices",
  ],
};

export const ROLES = {
  admin:            { label: "مدير النظام",      color: "purple" },
  manager:          { label: "مدير فرع",          color: "indigo" },
  sales:            { label: "موظف مبيعات",       color: "blue" },
  customer_service: { label: "خدمة العملاء",      color: "cyan" },
  technician:       { label: "فني صيانة",         color: "amber" },
  accountant:       { label: "محاسب",             color: "emerald" },
  shipping:         { label: "موظف شحن",          color: "orange" },
  viewer:           { label: "مشاهد فقط",         color: "slate" },
} as const;

export type Role = keyof typeof ROLES;
