import { useMemo, useRef, useState } from "react";
import { useMutation, usePaginatedQuery, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";
import { usePermission } from "../lib/access";
import { getErrorMessage } from "../lib/errors";
import { toast } from "sonner";
import { Printer, Truck, X } from "lucide-react";

const requestId = () => crypto.randomUUID();
type Modal = "create"|"ship"|"deliver"|"return"|"cancel"|"reverse-confirmation"|"settle"|"reverse-settlement"|null;
type Selected = { _id: Id<"deliveries">; deliveryNumber:string; status:string; codAmount?:number; branchId?:Id<"branches"> };

export function DeliveriesPage() {
  const canCreate=usePermission("create_deliveries"),canEdit=usePermission("edit_deliveries"),canConfirm=usePermission("confirm_cod_deliveries"),canViewSettlements=usePermission("view_cod_settlements"),canSettle=usePermission("settle_cod_collections"),canReverse=usePermission("reverse_cod_collections"),canPrint=usePermission("print_cod_settlements"),canViewBranches=usePermission("view_branches");
  const me=useQuery(api.employees.me),branches=useQuery(api.branches.list,canViewBranches?{}:"skip");
  const [branchId,setBranchId]=useState<Id<"branches">|undefined>(me?.branchId),[modal,setModal]=useState<Modal>(null),[selected,setSelected]=useState<Selected|null>(null),[busy,setBusy]=useState(false);
  const [orderId,setOrderId]=useState(""),[invoiceId,setInvoiceId]=useState(""),[city,setCity]=useState(""),[address,setAddress]=useState(""),[company,setCompany]=useState(""),[tracking,setTracking]=useState(""),[fee,setFee]=useState("0"),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[reason,setReason]=useState(""),[accountId,setAccountId]=useState(""),[destinationId,setDestinationId]=useState(""),[checked,setChecked]=useState<Set<string>>(new Set());
  const operationRequestId=useRef(requestId());
  const activeBranch=branchId??me?.branchId;
  const deliveries=usePaginatedQuery(api.deliveries.listPaginated,activeBranch?{branchId:activeBranch}:"skip",{initialNumItems:20});
  const options=useQuery(api.deliveries.creationOptions,canCreate&&activeBranch?{branchId:activeBranch}:"skip");
  const codAccounts=useQuery(api.deliveries.accountPicker,canConfirm&&activeBranch?{branchId:activeBranch,purpose:"cod"}:"skip");
  const destinations=useQuery(api.deliveries.accountPicker,canViewSettlements&&activeBranch?{branchId:activeBranch,purpose:"destination"}:"skip");
  const unsettled=useQuery(api.deliveries.unsettled,canSettle&&activeBranch&&accountId?{branchId:activeBranch,sourceAccountId:accountId as Id<"financialAccounts">}:"skip");
  const settlements=usePaginatedQuery(api.deliveries.listSettlements,canViewSettlements&&activeBranch?{branchId:activeBranch}:"skip",{initialNumItems:10});
  const chosenOrder=options?.find(o=>String(o.orderId)===orderId),chosenInvoice=chosenOrder?.invoices.find(i=>String(i.invoiceId)===invoiceId);
  const gross=useMemo(()=>unsettled?.filter(d=>checked.has(String(d._id))).reduce((s,d)=>s+(d.codAmount??0),0)??0,[unsettled,checked]);
  const createDelivery=useMutation(api.deliveries.createFromOrderInvoice),updateStatus=useMutation(api.deliveries.updateStatus),confirmDelivered=useMutation(api.deliveries.confirmDelivered),createSettlement=useMutation(api.deliveries.createCodSettlement),reverseSettlement=useMutation(api.deliveries.reverseCodSettlement),reverseConfirmation=useMutation(api.deliveries.reverseConfirmation);
  const open=(kind:Modal,row?:Selected)=>{setSelected(row??null);setReason("");operationRequestId.current=requestId();setModal(kind)};
  const close=()=>{if(!busy)setModal(null)};
  const run=async(action:()=>Promise<unknown>,message:string)=>{if(busy)return;setBusy(true);try{await action();toast.success(message);operationRequestId.current=requestId();setModal(null)}catch(error){toast.error(getErrorMessage(error,"تعذر تنفيذ العملية"))}finally{setBusy(false)}};
  const printDelivery=async(row:Selected)=>{if(busy||!canPrint)return;setBusy(true);try{const dto=await (window as Window & { __deliveryPrint?: (id:Id<"deliveries">)=>Promise<unknown> }).__deliveryPrint?.(row._id);if(!dto)throw new Error("لم تجهز بيانات سند التوصيل");const popup=window.open("","_blank");if(!popup)throw new Error("تعذر فتح نافذة الطباعة");popup.document.write(`<html dir="rtl"><body><h1>سند توصيل ${row.deliveryNumber}</h1><pre>${JSON.stringify(dto,null,2)}</pre></body></html>`)}catch(error){toast.error(getErrorMessage(error,"تعذرت الطباعة"))}finally{setBusy(false)}};
  const rows=deliveries.results;
  return <div dir="rtl" className="p-6 space-y-5">
    <header className="flex justify-between"><div><h1 className="text-2xl font-black flex gap-2"><Truck/>التوصيل والتحصيل COD</h1><p className="text-slate-500">دورة موثقة من الطلب والفاتورة حتى التسوية</p></div>{canCreate&&<button className="btn-primary" onClick={()=>open("create")}>إنشاء من طلب وفاتورة</button>}</header>
    {branches&&<select className="form-input max-w-xs" value={activeBranch??""} onChange={e=>setBranchId(e.target.value as Id<"branches">)}><option value="">اختر الفرع</option>{branches.filter(b=>b.isActive).map(b=><option key={b._id} value={b._id}>{b.name}</option>)}</select>}
    <div className="overflow-x-auto bg-white rounded-xl"><table className="w-full"><thead><tr><th>السند</th><th>العميل</th><th>الحالة</th><th>COD</th><th>الإجراءات</th></tr></thead><tbody>{rows.map(d=><tr key={d._id}><td>{d.deliveryNumber}</td><td>{d.customerName}</td><td>{d.status}</td><td>{d.codAmount??0}</td><td className="flex gap-1 flex-wrap">{canEdit&&d.status==="pending"&&<><button onClick={()=>open("ship",d)}>تأكيد الشحن</button><button onClick={()=>open("cancel",d)}>إلغاء</button></>}{canEdit&&d.status==="shipped"&&<button onClick={()=>open("return",d)}>إرجاع قبل التسليم</button>}{canConfirm&&d.status==="shipped"&&<button onClick={()=>open("deliver",d)}>تأكيد التسليم</button>}{canReverse&&d.status==="delivered"&&<button onClick={()=>open("reverse-confirmation",d)}>عكس التأكيد</button>}{canPrint&&<button onClick={()=>void printDelivery(d)}><Printer size={16}/></button>}</td></tr>)}</tbody></table>{deliveries.status==="CanLoadMore"&&<button onClick={()=>deliveries.loadMore(20)}>المزيد</button>}</div>
    {canSettle&&<button className="btn-primary" onClick={()=>open("settle")}>إنشاء تسوية COD مجمعة</button>}
    {canViewSettlements&&<section><h2 className="font-bold">التسويات</h2>{settlements.results.map(s=><div key={s._id} className="flex gap-3"><span>{s.settlementNumber} — {s.status} — {s.netAmount}</span>{canReverse&&s.status==="posted"&&<button onClick={()=>{setSelected(null);operationRequestId.current=requestId();setReason(String(s._id));setModal("reverse-settlement")}}>عكس التسوية</button>}</div>)}</section>}
    {modal&&<div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"><div className="bg-white rounded-2xl p-5 w-[min(95vw,650px)] space-y-3"><button onClick={close}><X/></button><h2 className="text-xl font-black">{{create:"إنشاء سند توصيل",ship:"تأكيد الشحن",deliver:"تأكيد التسليم والتحصيل",return:"إرجاع قبل التسليم",cancel:"إلغاء التوصيل","reverse-confirmation":"عكس تأكيد التسليم",settle:"تسوية COD مجمعة","reverse-settlement":"عكس تسوية COD"}[modal]}</h2>
      {modal==="create"&&<><select className="form-input" value={orderId} onChange={e=>{setOrderId(e.target.value);setInvoiceId("")}}><option>اختر طلباً جاهزاً</option>{options?.map(o=><option key={o.orderId} value={o.orderId}>{o.orderNumber} — {o.customerName}</option>)}</select><select className="form-input" value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}><option>اختر الفاتورة المؤهلة</option>{chosenOrder?.invoices.map(i=><option key={i.invoiceId} value={i.invoiceId}>{i.invoiceNumber}</option>)}</select>{chosenInvoice&&<div className="bg-slate-50 p-3">العميل: {chosenOrder?.customerName} | الإجمالي: {chosenInvoice.netTotal} | المدفوع: {chosenInvoice.paid} | COD: {chosenInvoice.remaining}<ul>{chosenOrder?.items.map((i,n)=><li key={n}>{i.productName} × {i.quantity}</li>)}</ul></div>}<input className="form-input" placeholder="المدينة" value={city} onChange={e=>setCity(e.target.value)}/><input className="form-input" placeholder="العنوان" value={address} onChange={e=>setAddress(e.target.value)}/><input className="form-input" placeholder="شركة الشحن" value={company} onChange={e=>setCompany(e.target.value)}/><input className="form-input" placeholder="رقم التتبع" value={tracking} onChange={e=>setTracking(e.target.value)}/><input className="form-input" type="number" step="0.01" placeholder="تكلفة الناقل المتوقعة" value={fee} onChange={e=>setFee(e.target.value)}/><p className="text-amber-700">تكلفة الناقل لا تضاف للعميل؛ يجب إدراج أي شحن يتحمله العميل داخل الفاتورة.</p></>}
      {(modal==="deliver"||modal==="settle")&&<select className="form-input" value={accountId} onChange={e=>setAccountId(e.target.value)}><option>اختر حساب COD المصدر</option>{codAccounts?.map(a=><option key={a._id} value={a._id}>{a.name} ({a.type})</option>)}</select>}
      {modal==="settle"&&<><div>{unsettled?.map(d=><label key={d._id} className="block"><input type="checkbox" checked={checked.has(String(d._id))} onChange={()=>setChecked(old=>{const n=new Set(old);n.has(String(d._id))?n.delete(String(d._id)):n.add(String(d._id));return n})}/>{d.deliveryNumber} — {d.codAmount}</label>)}</div><select className="form-input" value={destinationId} onChange={e=>setDestinationId(e.target.value)}><option>البنك أو الخزينة الوجهة</option>{destinations?.map(a=><option key={a._id} value={a._id}>{a.name}</option>)}</select><p>Gross: {gross} | الرسوم: {fee} | Net: {gross-Number(fee)}</p></>}
      {!["create","ship","deliver","settle"].includes(modal)&&<textarea className="form-input" placeholder="السبب الإلزامي" value={reason} onChange={e=>setReason(e.target.value)}/>}<input className="form-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/>
      <button disabled={busy} className="btn-primary disabled:opacity-50" onClick={()=>void run(async()=>{if(modal==="create"&&activeBranch) return createDelivery({orderId:orderId as Id<"orders">,invoiceId:invoiceId as Id<"invoices">,city,address,shippingCompany:company,trackingNumber:tracking||undefined,expectedCarrierFee:Number(fee),branchId:activeBranch,date,requestId:operationRequestId.current});if(modal==="ship"&&selected)return updateStatus({id:selected._id,status:"shipped"});if(modal==="deliver"&&selected)return confirmDelivered({deliveryId:selected._id,codClearingAccountId:accountId?accountId as Id<"financialAccounts">:undefined,date,requestId:operationRequestId.current});if((modal==="return"||modal==="cancel")&&selected)return updateStatus({id:selected._id,status:modal==="return"?"returned":"cancelled",reason});if(modal==="reverse-confirmation"&&selected)return reverseConfirmation({deliveryId:selected._id,reason,date,requestId:operationRequestId.current});if(modal==="settle"&&activeBranch)return createSettlement({deliveryIds:[...checked] as Id<"deliveries">[],sourceAccountId:accountId as Id<"financialAccounts">,destinationAccountId:destinationId as Id<"financialAccounts">,feeAmount:Number(fee),date,branchId:activeBranch,requestId:operationRequestId.current});if(modal==="reverse-settlement")return reverseSettlement({settlementId:reason as Id<"codSettlements">,reason:"عكس التسوية من الواجهة",date,requestId:operationRequestId.current});throw new Error("بيانات العملية ناقصة")},"تمت العملية بنجاح")}>{busy?"جارٍ التنفيذ…":"تأكيد"}</button>
    </div></div>}
  </div>;
}
