import { useMemo, useRef, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Doc, Id } from "../../convex/_generated/dataModel";
import { usePermission } from "../lib/access";
import { getErrorMessage } from "../lib/errors";
import { toast } from "sonner";
import { Printer, RotateCcw } from "lucide-react";

export function SalesReturnsPanel({ invoices }: { invoices: Doc<"invoices">[] }) {
  const canView = usePermission("view_sales_returns"), canCreate = usePermission("create_sales_returns"), canPrint = usePermission("print_credit_notes"), canRefund = usePermission("refund_collections");
  const notes = useQuery(api.salesReturns.list, canView ? {} : "skip");
  const accounts = useQuery(api.finance.collectionAccountPicker, canCreate && canRefund ? {} : "skip") ?? [];
  const createReturn = useMutation(api.salesReturns.create);
  const [invoice, setInvoice] = useState<Doc<"invoices"> | null>(null), [quantities, setQuantities] = useState<Record<string, number>>({}), [reason, setReason] = useState(""), [date, setDate] = useState(new Date().toISOString().slice(0, 10)), [accountId, setAccountId] = useState<Id<"financialAccounts"> | "">("");
  const [busy, setBusy] = useState(false), [printId, setPrintId] = useState<Id<"salesReturns"> | null>(null); const requestId = useRef(crypto.randomUUID());
  const printable = useQuery(api.salesReturns.getForPrint, canPrint && printId ? { id: printId } : "skip");
  const preview = useMemo(() => !invoice ? 0 : invoice.items.reduce((sum, item) => sum + ((item.lineNetTotal ?? item.total) * (quantities[String(item.productId)] ?? 0) / item.quantity), 0), [invoice, quantities]);
  const debtReduction = Math.min(invoice?.remaining ?? 0, preview), cashRefund = Math.max(0, preview - debtReduction);
  const start = (value: Doc<"invoices">) => { setInvoice(value); setQuantities({}); setReason(""); setAccountId(""); requestId.current = crypto.randomUUID(); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!invoice || busy) return; setBusy(true); try { await createReturn({ invoiceId: invoice._id, items: invoice.items.map(item => ({ productId: item.productId, quantity: quantities[String(item.productId)] ?? 0 })).filter(item => item.quantity > 0), reason, date, requestId: requestId.current, accountId: accountId || undefined }); toast.success("تم إنشاء الإشعار الدائن وإعادة المخزون"); setInvoice(null); requestId.current = crypto.randomUUID(); } catch (error) { toast.error(getErrorMessage(error, "تعذر إنشاء المرتجع")); } finally { setBusy(false); } };
  if (!canView && !canCreate) return null;
  return <section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4" dir="rtl">
    <h2 className="flex items-center gap-2 text-lg font-black"><RotateCcw className="h-5 w-5 text-indigo-600"/> الإشعارات الدائنة ومرتجعات البيع</h2>
    {notes === undefined && canView ? <p className="text-sm text-slate-500">جارٍ تحميل الإشعارات...</p> : notes?.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-center text-sm text-slate-500">لا توجد إشعارات دائنة بعد.</p> : notes?.map(note => <div key={note._id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><div><b>{note.creditNoteNumber}</b> — {note.invoiceNumber}<p>{note.totalCredit.toLocaleString("ar-EG")} ج.م · {note.reason}</p></div>{canPrint && <button aria-label="طباعة إشعار دائن" onClick={() => setPrintId(note._id)} className="rounded-lg p-2 hover:bg-white"><Printer className="h-4 w-4"/></button>}</div>)}
    {canCreate && <div><p className="mb-2 text-sm font-bold">ابدأ مرتجعاً من فاتورة مؤهلة:</p><div className="flex flex-wrap gap-2">{invoices.filter(value => value.status !== "cancelled" && (value.netTotal ?? value.total) > 0).map(value => <button key={value._id} onClick={() => start(value)} className="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">{value.invoiceNumber}</button>)}</div></div>}
    {invoice && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><h3 className="text-xl font-black">مرتجع الفاتورة {invoice.invoiceNumber}</h3><p className="text-sm text-slate-500">اختر الكميات المتاحة؛ الحساب المعروض Preview والخادم يعيد الحساب النهائي.</p>{invoice.items.map(item => <label key={String(item.productId)} className="my-3 grid grid-cols-3 items-center gap-3 rounded-xl bg-slate-50 p-3"><span>{item.productName}</span><span className="text-xs">الأصلية: {item.quantity}</span><input aria-label={`كمية إرجاع ${item.productName}`} className="form-input" type="number" min="0" max={item.quantity} step="1" value={quantities[String(item.productId)] ?? 0} onChange={event => setQuantities(value => ({ ...value, [String(item.productId)]: Number(event.target.value) }))}/></label>)}<label className="form-label">سبب المرتجع *</label><textarea className="form-input" required value={reason} onChange={event => setReason(event.target.value)}/><label className="form-label mt-3">تاريخ العملية</label><input className="form-input" type="date" required value={date} onChange={event => setDate(event.target.value)}/><div className="my-4 grid grid-cols-3 gap-2 rounded-xl bg-indigo-50 p-3 text-center text-sm"><div>الائتمان<br/><b>{preview.toFixed(2)}</b></div><div>خفض المديونية<br/><b>{debtReduction.toFixed(2)}</b></div><div>رد نقدي<br/><b>{cashRefund.toFixed(2)}</b></div></div>{cashRefund > 0 && <select required className="form-input" value={accountId} onChange={event => setAccountId(event.target.value as Id<"financialAccounts">)}><option value="">اختر حساب الاسترداد</option>{accounts.map(account => <option key={account._id} value={account._id}>{account.name}</option>)}</select>}<div className="mt-5 flex gap-3"><button disabled={busy || !reason.trim()} className="btn-primary flex-1">{busy ? "جارٍ التنفيذ..." : "إنشاء الإشعار الدائن"}</button><button type="button" disabled={busy} className="btn-secondary" onClick={() => setInvoice(null)}>إلغاء</button></div></form></div>}
    {printId && printable && <div className="fixed inset-0 z-50 bg-white p-8 print:p-0"><div className="mx-auto max-w-2xl border p-8"><h1 className="text-center text-2xl font-black">إشعار دائن</h1><p>رقم: {printable.creditNoteNumber}</p><p>الفاتورة: {printable.invoiceNumber}</p><p>العميل: {printable.customerName}</p><p>السبب: {printable.reason}</p><p className="mt-5 text-xl font-black">الإجمالي: {printable.totalCredit} ج.م</p><button className="btn-primary mt-6 print:hidden" onClick={() => window.print()}>طباعة</button><button className="btn-secondary mr-2 print:hidden" onClick={() => setPrintId(null)}>إغلاق</button></div></div>}
  </section>;
}
