import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, usePaginatedQuery, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";
import { usePermission } from "../lib/access";
import { getErrorMessage } from "../lib/errors";
import { toast } from "sonner";

const requestId = () => crypto.randomUUID();
export function SupplierPaymentsPage() {
  const canRecord = usePermission("record_supplier_payments"), canDisburse = usePermission("record_disbursements"), canReverse = usePermission("reverse_supplier_payments"), canReverseFinance = usePermission("reverse_financial_transactions"), canPrint = usePermission("print_supplier_payments"), canLedger = usePermission("view_supplier_ledger");
  const me = useQuery(api.employees.me);
  const branches = useQuery(api.branches.list, me?.role === "admin" ? {} : "skip") ?? [];
  const suppliers = useQuery(api.supplierPayments.supplierOptions, canRecord ? {} : "skip") ?? [];
  const accounts = useQuery(api.finance.disbursementAccountPicker, canRecord && canDisburse ? {} : "skip") ?? [];
  const [selectedBranchId, setSelectedBranchId] = useState<Id<"branches"> | "">("");
  const effectiveBranchId = me?.role === "admin" ? selectedBranchId : (me?.branchId ?? "");
  const [supplierId, setSupplierId] = useState<Id<"suppliers"> | "">(""), [accountId, setAccountId] = useState<Id<"financialAccounts"> | "">(""), [date, setDate] = useState(new Date().toISOString().slice(0, 10)), [notes, setNotes] = useState("");
  const [amounts, setAmounts] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [reversePayment, setReversePayment] = useState<Id<"supplierPayments"> | null>(null), [reason, setReason] = useState("");
  const createRequest = useRef(requestId()), reverseRequest = useRef(requestId());
  const receipts = useQuery(api.supplierPayments.openPurchaseReceipts, supplierId && effectiveBranchId && canRecord ? { supplierId, branchId: effectiveBranchId } : "skip") ?? [];
  const balance = useQuery(api.supplierPayments.supplierBalance, supplierId && effectiveBranchId && canLedger ? { supplierId, branchId: effectiveBranchId } : "skip");
  const payments = usePaginatedQuery(api.supplierPayments.list, canLedger && effectiveBranchId ? { branchId: effectiveBranchId } : "skip", { initialNumItems: 20 });
  const filteredAccounts = accounts.filter(account => account.branchId === effectiveBranchId);
  const [printPaymentId, setPrintPaymentId] = useState<Id<"supplierPayments"> | null>(null);
  const printDto = useQuery(api.supplierPayments.print, canPrint && printPaymentId ? { paymentId: printPaymentId } : "skip");
  const createPayment = useMutation(api.supplierPayments.create), reverse = useMutation(api.supplierPayments.reverse);
  const total = useMemo(() => Object.values(amounts).reduce((sum, value) => sum + (Number(value) || 0), 0), [amounts]);
  const submit = async () => { if (busy || !supplierId || !accountId) return; const allocations = receipts.filter(r => Number(amounts[r._id]) > 0).map(r => ({ purchaseReceiptId: r._id, amount: Number(amounts[r._id]) })); if (!confirm(`تأكيد صرف ${total.toFixed(2)} ج.م من الخزينة وخفض رصيد المورد بالقيمة نفسها؟`)) return; setBusy(true); try { await createPayment({ supplierId, branchId: effectiveBranchId || undefined, accountId, date, notes: notes || undefined, requestId: createRequest.current, allocations }); toast.success("تم تسجيل دفعة المورد"); createRequest.current = requestId(); setAmounts({}); setNotes(""); } catch (error) { toast.error(getErrorMessage(error)); } finally { setBusy(false); } };
  const submitReverse = async () => { if (busy || !reversePayment) return; setBusy(true); try { await reverse({ paymentId: reversePayment, reason, date, requestId: reverseRequest.current }); toast.success("تم عكس الدفعة"); reverseRequest.current = requestId(); setReversePayment(null); setReason(""); } catch (error) { toast.error(getErrorMessage(error)); } finally { setBusy(false); } };
  const handlePrint = (paymentId: Id<"supplierPayments">) => { if (!canPrint) { toast.error("ليس لديك صلاحية طباعة سندات الموردين"); return; } setPrintPaymentId(paymentId); };
  useEffect(() => { if (!canPrint || !printPaymentId || !printDto) return; const escape = (value: string | number | undefined) => String(value ?? "—").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" })[character] ?? character); const rows = printDto.allocations.map(row => `<tr><td>${escape(row.receiptNumber)}</td><td>${escape(row.amount.toFixed(2))} ج.م</td></tr>`).join(""); const reversed = printDto.status === "reversed" ? `<p><b>سبب العكس:</b> ${escape(printDto.reversalReason)}</p><p><b>تاريخ العكس:</b> ${escape(printDto.reversalDate)}</p>` : ""; const popup = window.open("", "_blank"); if (!popup) { toast.error("تعذر فتح نافذة الطباعة"); return; } popup.document.body.innerHTML = `<!doctype html><html dir="rtl" lang="ar"><head><title>سند ${escape(printDto.paymentNumber)}</title><style>body{font-family:Tahoma;padding:32px;color:#111}h1{text-align:center}header{text-align:center}table{width:100%;border-collapse:collapse;margin:24px 0}td,th{border:1px solid #555;padding:9px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px}.signatures{display:flex;justify-content:space-between;margin-top:70px}</style></head><body><header><h2>متجر ERP</h2><h1>سند دفع مورد</h1></header><div class="meta"><p><b>رقم السند:</b> ${escape(printDto.paymentNumber)}</p><p><b>التاريخ:</b> ${escape(printDto.date)}</p><p><b>المورد:</b> ${escape(printDto.supplierName)}</p><p><b>الفرع:</b> ${escape(printDto.branchName)}</p><p><b>الحساب المصروف منه:</b> ${escape(printDto.accountName)}</p><p><b>أنشأه:</b> ${escape(printDto.createdBy)}</p></div><table><thead><tr><th>مستند الشراء</th><th>المبلغ الموزع</th></tr></thead><tbody>${rows}</tbody></table><h3>إجمالي الدفعة: ${escape(printDto.amount.toFixed(2))} ج.م</h3><p><b>الملاحظات:</b> ${escape(printDto.notes)}</p><p><b>حالة السند:</b> ${printDto.status === "posted" ? "مرحل" : "معكوس"}</p>${reversed}<div class="signatures"><span>توقيع المستلم: ................</span><span>توقيع المراجع: ................</span></div></body></html>`; popup.document.close(); popup.focus(); popup.print(); setPrintPaymentId(null); }, [canPrint, printDto, printPaymentId]);
  return <div className="p-6 space-y-6" dir="rtl"><h1 className="text-2xl font-black">مدفوعات الموردين</h1>
    {canRecord && canDisburse && <section className="card p-5 space-y-4"><div className="grid md:grid-cols-5 gap-3">{me?.role === "admin" && <select className="form-input" value={selectedBranchId} onChange={e => { setSelectedBranchId(e.target.value as Id<"branches">); setAccountId(""); }}><option value="">اختر الفرع</option>{branches.map(branch => <option key={branch._id} value={branch._id}>{branch.name}</option>)}</select>}<select className="form-input" value={supplierId} onChange={e => setSupplierId(e.target.value as Id<"suppliers">)}><option value="">اختر المورد</option>{suppliers.map(s => <option key={s._id} value={s._id}>{s.name}</option>)}</select><select className="form-input" value={accountId} onChange={e => setAccountId(e.target.value as Id<"financialAccounts">)}><option value="">حساب الصرف</option>{filteredAccounts.map(a => <option key={a._id} value={a._id}>{a.name} — {branches.find(branch => branch._id === a.branchId)?.name ?? "الفرع الحالي"}</option>)}</select><input className="form-input" type="date" value={date} onChange={e => setDate(e.target.value)}/><input className="form-input" placeholder="ملاحظات" value={notes} onChange={e => setNotes(e.target.value)}/></div>{balance && <p>رصيد المورد: <b>{balance.balance.toFixed(2)} ج.م</b></p>}<div className="overflow-auto"><table className="data-table"><thead><tr><th>المستند</th><th>المتبقي</th><th>التوزيع</th></tr></thead><tbody>{receipts.map(r => <tr key={r._id}><td>{r.receiptNumber}</td><td>{r.remainingAmount}</td><td><input type="number" min="0" max={r.remainingAmount} step="0.01" className="form-input" value={amounts[r._id] ?? ""} onChange={e => setAmounts(x => ({ ...x, [r._id]: e.target.value }))}/></td></tr>)}</tbody></table></div><div className="flex justify-between"><b>الإجمالي: {total.toFixed(2)} ج.م</b><button disabled={busy || !effectiveBranchId || !supplierId || !accountId || total <= 0 || receipts.every(receipt => Number(amounts[receipt._id]) <= 0)} className="btn-primary" onClick={() => void submit()}>{busy ? "جاري الحفظ..." : "تسجيل الدفعة"}</button></div></section>}
    <section className="card p-5"><h2 className="font-bold mb-3">سجل سندات الدفع</h2><table className="data-table"><thead><tr><th>الرقم</th><th>المورد</th><th>المبلغ</th><th>الحالة</th><th/></tr></thead><tbody>{payments.results.map(p => <tr key={p._id}><td>{p.paymentNumber}</td><td>{p.supplierName}</td><td>{p.amount}</td><td>{p.status === "posted" ? "مرحل" : "معكوس"}</td><td>{canPrint && <button onClick={() => handlePrint(p._id)}>طباعة</button>} {p.status === "posted" && canReverse && canReverseFinance && <button onClick={() => { setReversePayment(p._id); reverseRequest.current = requestId(); }}>عكس</button>}</td></tr>)}</tbody></table>{payments.status === "CanLoadMore" && <button onClick={() => payments.loadMore(20)}>تحميل المزيد</button>}</section>
    {reversePayment && <div className="fixed inset-0 bg-black/50 grid place-items-center"><div className="bg-white p-6 rounded-xl space-y-3"><h2>عكس دفعة المورد</h2><input className="form-input" placeholder="سبب العكس" value={reason} onChange={e => setReason(e.target.value)}/><input className="form-input" type="date" value={date} onChange={e => setDate(e.target.value)}/><button disabled={busy || !reason.trim()} className="btn-primary" onClick={() => void submitReverse()}>تأكيد العكس</button><button onClick={() => setReversePayment(null)}>إلغاء</button></div></div>}
  </div>;
}
