import { useMemo, useState } from "react";
import { useMutation, usePaginatedQuery, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";
import { usePermission } from "../lib/access";
import { toast } from "sonner";

const labels: Record<string, string> = { cash: "نقدي", instapay: "Instapay", vodafone_cash: "Vodafone Cash", fawry_clearing: "Fawry (معلق)", paymob_clearing: "Paymob (معلق)", card_clearing: "بطاقات (معلق)", bank: "بنك", other: "أخرى" };

export function TreasuryPage() {
  const accounts = useQuery(api.finance.accounts, {});
  const canManage = usePermission("manage_financial_accounts");
  const canInitialize = usePermission("initialize_finance");
  const createAccount = useMutation(api.finance.createAccount);
  const configure = useMutation(api.finance.configureInitialization);
  const confirmInitialization = useMutation(api.finance.confirmInitialization);
  const postOpeningBalance = useMutation(api.finance.postOpeningBalance);
  const transferFunds = useMutation(api.finance.transferFunds);
  const settleClearingAccount = useMutation(api.finance.settleClearingAccount);
  const reverseTransaction = useMutation(api.finance.reverseTransaction);
  const initialization = useQuery(api.finance.initializationStatus, {});
  const reportDate = new Date().toISOString().slice(0, 10);
  const branches = useQuery(api.branches.list, canManage ? {} : "skip");
  const [branchId, setBranchId] = useState(""); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [type, setType] = useState<keyof typeof labels>("cash");
  const [cutoverDate, setCutoverDate] = useState(new Date().toISOString().slice(0, 10));
  const selectedBranch = useMemo(() => branchId as Id<"branches">, [branchId]);
  const dailySummary = useQuery(api.finance.dailySummary, branchId ? { branchId: selectedBranch, date: reportDate } : "skip");
  const collectionSummary = useQuery(api.finance.collectionSummary, branchId ? { branchId: selectedBranch, date: reportDate } : "skip");
  const { results, status, loadMore } = usePaginatedQuery(api.finance.ledger, branchId ? { branchId: selectedBranch } : "skip", { initialNumItems: 25 });
  const add = async () => { try { await createAccount({ branchId: selectedBranch, name, code, type }); setName(""); setCode(""); toast.success("تم إنشاء الحساب برصيد صفر"); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر إنشاء الحساب"); } };
  const opening = async (accountId: Id<"financialAccounts">) => { const amount = Number(prompt("الرصيد الافتتاحي (يسمح بصفر)") ?? ""); if (!Number.isFinite(amount) || amount < 0) return; try { await postOpeningBalance({ accountId, amount, date: cutoverDate, requestId: crypto.randomUUID() }); toast.success("تم تسجيل الرصيد الافتتاحي"); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر التسجيل"); } };
  const transfer = async () => { if (!accounts || accounts.length < 2) return toast.error("يلزم حسابان"); const amount = Number(prompt("مبلغ التحويل")); if (!amount) return; try { await transferFunds({ sourceAccountId: accounts[0]._id, destinationAccountId: accounts[1]._id, amount, date: new Date().toISOString().slice(0, 10), requestId: crypto.randomUUID() }); toast.success("تم التحويل"); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر التحويل"); } };
  const settle = async () => { const source = accounts?.find(a => ["paymob_clearing", "fawry_clearing", "card_clearing"].includes(a.type)); const destination = accounts?.find(a => a.branchId === source?.branchId && ["cash", "bank"].includes(a.type)); const grossAmount = Number(prompt("إجمالي التسوية")); const feeAmount = Number(prompt("الرسوم") ?? 0); if (!source || !destination || !grossAmount) return toast.error("اختر حساب تسوية ووجهة صالحين"); try { await settleClearingAccount({ sourceAccountId: source._id, destinationAccountId: destination._id, grossAmount, feeAmount, settlementDate: new Date().toISOString().slice(0, 10), requestId: crypto.randomUUID() }); toast.success(`تمت التسوية، الصافي ${grossAmount - feeAmount}`); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر التسوية"); } };
  return <div className="p-6 space-y-6" dir="rtl">
    <div><h1 className="text-2xl font-bold text-slate-900">الخزائن والحسابات</h1><p className="text-sm text-slate-500">دفتر مالي غير قابل للحذف، والأرصدة محسوبة من الحركات الذرية.</p></div>
    {canInitialize && <section className="card p-5"><h2 className="font-bold mb-3">تهيئة النظام المالي — {initialization?.state === "initialized" ? "مفعل" : initialization?.state === "configuring" ? "تحت الإعداد" : "غير مهيأ"}</h2><div className="flex flex-wrap gap-2"><input type="date" disabled={initialization?.state === "initialized"} className="input" value={cutoverDate} onChange={e => setCutoverDate(e.target.value)} /><button className="btn-secondary" onClick={() => void configure({ cutoverDate, defaultClearingDelayDays: 1 })}>حفظ تاريخ القطع</button><button className="btn-primary" onClick={() => { if (window.confirm("التأكيد نهائي ولا يمكن بعده تعديل تاريخ القطع أو الأرصدة الافتتاحية")) void confirmInitialization(); }}>تأكيد التشغيل نهائياً</button></div><p className="text-xs text-amber-700 mt-2">متبقٍ {initialization?.openingBalancesRemaining ?? 0} أرصدة افتتاحية. أنشئ خزينة نقدية لكل فرع وسجّل رصيد كل حساب حتى إن كان صفراً.</p></section>}
    {canManage && <section className="card p-5"><h2 className="font-bold mb-3">إنشاء حساب</h2><div className="grid md:grid-cols-5 gap-2"><select className="input" value={branchId} onChange={e => setBranchId(e.target.value)}><option value="">اختر الفرع</option>{branches?.map(b => <option key={b._id} value={b._id}>{b.name}</option>)}</select><input className="input" placeholder="اسم الحساب" value={name} onChange={e => setName(e.target.value)} /><input className="input" placeholder="الكود" value={code} onChange={e => setCode(e.target.value)} /><select className="input" value={type} onChange={e => setType(e.target.value as keyof typeof labels)}>{Object.entries(labels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><button className="btn-primary" disabled={!branchId || !name || !code} onClick={() => void add()}>إنشاء حساب</button></div><div className="flex gap-2 mt-3"><button className="btn-secondary" onClick={() => void transfer()}>تحويل بين الحسابات</button><button className="btn-secondary" onClick={() => void settle()}>تسوية حساب وسيط</button></div></section>}
    <section className="card overflow-hidden"><div className="p-4 font-bold">الحسابات</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3">الحساب</th><th>النوع</th><th>الرصيد الحالي</th><th>المتاح</th><th>المعلق</th><th>الحالة</th><th>الافتتاحي</th></tr></thead><tbody>{accounts?.map(a => <tr key={a._id} className="border-t"><td className="p-3 font-medium">{a.name}</td><td>{labels[a.type]}</td><td>{a.currentBalance.toFixed(2)}</td><td>{a.availableBalance.toFixed(2)}</td><td>{a.pendingBalance.toFixed(2)}</td><td>{a.isActive ? "نشط" : "معطل"}</td><td>{a.openingBalancePostedAt ? "مسجل" : <button className="btn-secondary text-xs" onClick={() => void opening(a._id)}>تسجيل رصيد افتتاحي</button>}</td></tr>)}</tbody></table></div></section>
    {dailySummary && collectionSummary && <section className="grid md:grid-cols-2 gap-4"><div className="card p-4"><h2 className="font-bold">ملخص اليوم</h2><p>أول اليوم: {dailySummary.openingBalance.toFixed(2)}</p><p className="text-emerald-700">الداخل: {dailySummary.incoming.toFixed(2)}</p><p className="text-red-700">الخارج: {dailySummary.outgoing.toFixed(2)}</p><p>آخر اليوم: {dailySummary.closingBalance.toFixed(2)}</p><p>المعلق: {dailySummary.pending.toFixed(2)} — المتاح: {dailySummary.availableForSettlement.toFixed(2)}</p></div><div className="card p-4"><h2 className="font-bold">ملخص التحصيل</h2><p>التحصيل: {collectionSummary.totalCollections.toFixed(2)}</p><p>الاسترداد: {collectionSummary.totalRefunds.toFixed(2)}</p><p className="font-bold">الصافي: {collectionSummary.netCollections.toFixed(2)}</p></div></section>}
    <section className="card overflow-hidden"><div className="p-4 flex justify-between"><span className="font-bold">دفتر الحركة</span><span className="text-xs text-slate-500">اختر فرعاً لعرض السجل المفهرس</span></div><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3">التاريخ</th><th>الحساب</th><th>النوع</th><th>الداخل</th><th>الخارج</th><th>الرصيد بعد</th><th>إجراء</th></tr></thead><tbody>{results.map(m => <tr key={m._id} className="border-t"><td className="p-3">{m.date}</td><td>{m.accountName}</td><td>{m.transactionType}</td><td className="text-emerald-600">{m.incoming ? m.incoming.toFixed(2) : "—"}</td><td className="text-red-600">{m.outgoing ? m.outgoing.toFixed(2) : "—"}</td><td>{m.balanceAfter.toFixed(2)}</td><td>{["opening_balance","account_transfer","paymob_settlement","clearing_settlement"].includes(m.transactionType) && <button className="text-xs text-red-700" onClick={() => { const reason=prompt("سبب العكس")?.trim(); if(reason) void reverseTransaction({ transactionId:m.transactionId, reason, date:new Date().toISOString().slice(0,10), requestId:crypto.randomUUID() }); }}>عكس</button>}</td></tr>)}</tbody></table>{status === "CanLoadMore" && <button className="m-4 btn-secondary" onClick={() => loadMore(25)}>تحميل المزيد</button>}</section>
  </div>;
}
