const roundMoney = (value: number) => Math.round((value + Number.EPSILON) * 100) / 100;
export type PurchaseReturnInputItem = { receiptItemIndex: number; quantity: number };
export const hasMoneyPrecision = (value: number) => Number.isFinite(value) && Math.abs(value * 100 - Math.round(value * 100)) < 1e-7;
export function canonicalPurchaseReturnItems(items: readonly PurchaseReturnInputItem[]) { if (!items.length) throw new Error("يجب اختيار بند واحد على الأقل"); const result = items.map(item => { if (!Number.isInteger(item.receiptItemIndex) || item.receiptItemIndex < 0) throw new Error("رقم بند مستند الشراء غير صالح"); if (!Number.isInteger(item.quantity) || item.quantity <= 0) throw new Error("كمية المرتجع يجب أن تكون عدداً صحيحاً أكبر من صفر"); return { ...item }; }).sort((a,b) => a.receiptItemIndex-b.receiptItemIndex); if (result.some((item,index) => index > 0 && result[index-1].receiptItemIndex === item.receiptItemIndex)) throw new Error("لا يجوز تكرار بند مستند الشراء"); return result; }
export function cumulativeGoodsCredit(lineTotal:number, originalQuantity:number, returnedQuantity:number) { if (!hasMoneyPrecision(lineTotal)||lineTotal<0||!Number.isInteger(originalQuantity)||originalQuantity<=0||!Number.isInteger(returnedQuantity)||returnedQuantity<0||returnedQuantity>originalQuantity) throw new Error("بيانات بند الشراء التاريخية غير صالحة"); return returnedQuantity===originalQuantity?lineTotal:roundMoney(lineTotal*returnedQuantity/originalQuantity); }
export const incrementalGoodsCredit=(lineTotal:number, originalQuantity:number, before:number, quantity:number)=>roundMoney(cumulativeGoodsCredit(lineTotal,originalQuantity,before+quantity)-cumulativeGoodsCredit(lineTotal,originalQuantity,before));
export function availableSupplierFreight(original:number, returned:number) { if(!hasMoneyPrecision(original)||!hasMoneyPrecision(returned)||original<0||returned<0||returned>original) throw new Error("رصيد شحن المورد غير متسق"); return roundMoney(original-returned); }
export function totalPurchaseCredit(goods:number, freight:number) { if(!hasMoneyPrecision(goods)||!hasMoneyPrecision(freight)||goods<0||freight<0) throw new Error("قيمة الخصم غير صالحة"); return roundMoney(goods+freight); }
export function splitPurchaseCredit(remaining:number,totalCredit:number) { if(!hasMoneyPrecision(remaining)||!hasMoneyPrecision(totalCredit)||remaining<0||totalCredit<0) throw new Error("قيم مستند الشراء غير متسقة"); const debtReduction=roundMoney(Math.min(remaining,totalCredit)); return {debtReduction,cashRefund:roundMoney(totalCredit-debtReduction)}; }
export function inventoryValueForPurchaseReturn(stock:number,value:number,quantity:number) { if(!Number.isInteger(stock)||stock<0||!hasMoneyPrecision(value)||value<0) throw new Error("رصيد أو قيمة المخزون غير صالح"); if(!Number.isInteger(quantity)||quantity<=0||quantity>stock) throw new Error("مخزون المنتج لا يكفي للمرتجع"); return quantity===stock?value:roundMoney(value*quantity/stock); }
export function purchaseReceiptAfterCredit(payable:number,paid:number,remaining:number,totalCredit:number) { if(![payable,paid,remaining,totalCredit].every(hasMoneyPrecision)||payable<0||paid<0||remaining<0||totalCredit<0||roundMoney(paid+remaining)!==payable) throw new Error("مستند الشراء غير متسق ويحتاج مراجعة يدوية"); const {debtReduction,cashRefund}=splitPurchaseCredit(remaining,totalCredit); const netPayableAmount=roundMoney(payable-totalCredit),paidAmount=roundMoney(paid-cashRefund),remainingAmount=roundMoney(remaining-debtReduction); if(netPayableAmount<0||paidAmount<0||remainingAmount<0||roundMoney(paidAmount+remainingAmount)!==netPayableAmount) throw new Error("الخصم يتجاوز صافي مستند الشراء"); return {netPayableAmount,paidAmount,remainingAmount,debtReduction,cashRefund,status:remainingAmount===0?"paid" as const:paidAmount===0?"unpaid" as const:"partial" as const}; }
export function purchaseReceiptAfterReversal(net:number,paid:number,remaining:number,total:number,debt:number,cash:number) { if(roundMoney(paid+remaining)!==net) throw new Error("مستند الشراء غير متسق ويحتاج مراجعة يدوية"); const netPayableAmount=roundMoney(net+total),paidAmount=roundMoney(paid+cash),remainingAmount=roundMoney(remaining+debt); if(roundMoney(paidAmount+remainingAmount)!==netPayableAmount) throw new Error("تعذر عكس قيم مستند الشراء"); return {netPayableAmount,paidAmount,remainingAmount,status:remainingAmount===0?"paid" as const:paidAmount===0?"unpaid" as const:"partial" as const}; }
