import assert from "node:assert/strict";
import test from "node:test";
import { Pool } from "pg";
import { runMigrations } from "../../scripts/database/migrations.mjs";
import { RoleCatalogService } from "../infrastructure/authorization/role-catalog-service.ts";
import { withTransaction } from "../infrastructure/database/transaction.ts";
import { CashDocumentPostingService } from "../infrastructure/finance/cash-document-posting-service.ts";
import { CustomerAdvanceError, CustomerAdvanceService } from "../infrastructure/finance/customer-advance-service.ts";
import { TREASURY_PERMISSIONS } from "../infrastructure/finance/treasury-service.ts";
import { IdempotencyConflictError } from "../infrastructure/idempotency/idempotency-service.ts";
import { cleanupDatabase, MIGRATIONS } from "./postgresql-schema-test-support.mjs";
const url=process.env.ERP_TEST_DATABASE_URL;
const I={co:"ca050000-0000-4000-8000-000000000001",br:"ca050000-0000-4000-8000-000000000002",wh:"ca050000-0000-4000-8000-000000000003",user:"ca050000-0000-4000-8000-000000000004",perm:"ca050000-0000-4000-8000-000000000005",cp:"ca050000-0000-4000-8000-000000000006",cp2:"ca050000-0000-4000-8000-000000000007",pl:"ca050000-0000-4000-8000-000000000008",tr:"ca050000-0000-4000-8000-000000000009",order:"ca050000-0000-4000-8000-000000000010",order2:"ca050000-0000-4000-8000-000000000011",inv1:"ca050000-0000-4000-8000-000000000012",inv2:"ca050000-0000-4000-8000-000000000013",inv3:"ca050000-0000-4000-8000-000000000014",invOther:"ca050000-0000-4000-8000-000000000015"};
const createInput=(key,amount="100")=>({idempotencyKey:key,idempotencyExpiresAt:new Date("2030-01-01T00:00:00Z"),actorUserId:I.user,branchId:I.br,treasuryId:I.tr,salesOrderId:I.order,amount,occurredAt:new Date("2026-10-02T10:00:00Z")});
const applyInput=(key,advanceId,salesInvoiceId,amount)=>({idempotencyKey:key,idempotencyExpiresAt:new Date("2030-01-01T00:00:00Z"),actorUserId:I.user,advanceId,salesInvoiceId,amount});
const reverseInput=(key,advanceId,salesInvoiceId)=>({idempotencyKey:key,idempotencyExpiresAt:new Date("2030-01-01T00:00:00Z"),actorUserId:I.user,advanceId,salesInvoiceId});
test("09.05 Customer Advances are atomic, no-double-consumption, append-only and cash-neutral on apply/reverse",{skip:url===undefined},async()=>{
 assert.ok(url);await cleanupDatabase(url);const pool=new Pool({connectionString:url,max:20,application_name:"erp-0905"});const db={transaction(w,o){return withTransaction(pool,w,o)}};const roles=new RoleCatalogService(db),service=new CustomerAdvanceService(db),cash=new CashDocumentPostingService(db);
 try{
  assert.deepEqual((await runMigrations({databaseUrl:url})).applied,MIGRATIONS);
  const role=(await roles.ensureDefaultRoles()).find(x=>x.roleKey==="ACCOUNTANT");assert.ok(role);
  await pool.query("INSERT INTO companies(id,name,base_currency_code,default_language,timezone,is_active,created_at,updated_at) VALUES($1,'0905','EGP','ar-EG','Africa/Cairo',true,now(),now())",[I.co]);
  await pool.query("INSERT INTO branches(id,company_id,name,code,is_active,created_at,updated_at) VALUES($1,$2,'A','A',true,now(),now())",[I.br,I.co]);
  await pool.query("INSERT INTO warehouses(id,branch_id,name,code,is_active,created_at,updated_at) VALUES($1,$2,'WH','WH',true,now(),now())",[I.wh,I.br]);
  await pool.query("INSERT INTO permissions(id,permission_key,module,description_key) VALUES($1,$2,'finance','permissions.finance.accounts.manage') ON CONFLICT(permission_key) DO NOTHING",[I.perm,TREASURY_PERMISSIONS.manage]);
  const p=await pool.query("SELECT id FROM permissions WHERE permission_key=$1",[TREASURY_PERMISSIONS.manage]);await pool.query("INSERT INTO role_permissions(role_id,permission_id,is_allowed) VALUES($1,$2,true) ON CONFLICT(role_id,permission_id) DO UPDATE SET is_allowed=true",[role.id,p.rows[0].id]);
  await pool.query("INSERT INTO users(id,name,username,email,password_hash,role_id,default_branch_id,branch_scope_mode,preferred_language,is_active,created_at,updated_at) VALUES($1,'U','advance-u','advance-u@example.test','x',$2,$3,'ALL','ar-EG',true,now(),now())",[I.user,role.id,I.br]);
  await pool.query("INSERT INTO counterparties(id,name,phone,normalized_phone,address,notes,is_active,created_at,updated_at) VALUES($1,'C1',NULL,NULL,NULL,NULL,true,now(),now()),($2,'C2',NULL,NULL,NULL,NULL,true,now(),now())",[I.cp,I.cp2]);await pool.query("INSERT INTO counterparty_roles(counterparty_id,role) VALUES($1,'CUSTOMER'),($2,'CUSTOMER')",[I.cp,I.cp2]);
  await pool.query("INSERT INTO price_lists(id,name,is_active,created_at,updated_at) VALUES($1,'Retail',true,now(),now())",[I.pl]);await pool.query("INSERT INTO treasuries(id,branch_id,name,is_active,notes,created_at) VALUES($1,$2,'Cash',true,NULL,now())",[I.tr,I.br]);
  const orderSql="INSERT INTO sales_orders(id,branch_id,document_number,counterparty_id,warehouse_id,price_list_id,status,delivery_method,sales_user_id,customer_service_user_id,customer_notes,internal_notes,source_quote_id,version,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,'PENDING','PICKUP',$7,$7,NULL,NULL,NULL,0,now(),now())";
  await pool.query(orderSql,[I.order,I.br,1,I.cp,I.wh,I.pl,I.user]);await pool.query(orderSql,[I.order2,I.br,2,I.cp2,I.wh,I.pl,I.user]);
  const invoiceSql="INSERT INTO sales_invoices(id,branch_id,document_number,document_date,document_version,counterparty_id,warehouse_id,price_list_id,source_sales_order_id,source_delivery_id,subtotal,discount_total,tax_total,grand_total,paid_total,due_total,payment_status,seller_user_id,customer_notes,internal_notes,posted_at,created_by,updated_at,deleted_at,deleted_by,delete_reason) VALUES($1,$2,$3,CURRENT_DATE,1,$4,$5,$6,$7,NULL,100,0,0,100,0,100,'UNPAID',$8,NULL,NULL,now(),$8,now(),NULL,NULL,NULL)";
  await pool.query(invoiceSql,[I.inv1,I.br,1,I.cp,I.wh,I.pl,I.order,I.user]);await pool.query(invoiceSql,[I.inv2,I.br,2,I.cp,I.wh,I.pl,I.order,I.user]);await pool.query(invoiceSql,[I.inv3,I.br,3,I.cp,I.wh,I.pl,I.order,I.user]);await pool.query(invoiceSql,[I.invOther,I.br,4,I.cp2,I.wh,I.pl,I.order2,I.user]);

  const created=await service.create(createInput("create-1","100"));assert.equal(created.state,"EXECUTED");const advance=created.value.advance;assert.equal(advance.originalAmount,"100.0000");assert.equal(advance.remainingAmountProjection,"100.0000");assert.equal(created.value.receipt.document.counterpartyId,I.cp);assert.equal(created.value.receipt.financial.movement.direction,"IN");
  const counts=await pool.query("SELECT (SELECT count(*)::int FROM receipts) receipts,(SELECT count(*)::int FROM financial_movements) movements,(SELECT count(*)::int FROM customer_advances) advances,(SELECT count(*)::int FROM journal_entries) journals,(SELECT count(*)::int FROM customer_ledger_entries) ledgers");assert.deepEqual(counts.rows[0],{receipts:1,movements:1,advances:1,journals:0,ledgers:0});assert.equal((await pool.query("SELECT current_balance::text b FROM treasury_balance_positions WHERE treasury_id=$1",[I.tr])).rows[0].b,"100.0000");
  const replay=await service.create(createInput("create-1","100"));assert.equal(replay.state,"REPLAYED");assert.equal(replay.resultReference,advance.id);await assert.rejects(()=>service.create(createInput("create-1","101")),IdempotencyConflictError);
  await assert.rejects(()=>service.apply(applyInput("bad-context",advance.id,I.invOther,"10")),(e)=>e instanceof CustomerAdvanceError&&e.reason==="SALES_INVOICE_CONTEXT_MISMATCH");

  const beforeCash=(await pool.query("SELECT count(*)::int c FROM financial_movements")).rows[0].c;const applied1=await service.apply(applyInput("apply-1",advance.id,I.inv1,"60"));assert.equal(applied1.value.advance.remainingAmountProjection,"40.0000");assert.equal((await pool.query("SELECT count(*)::int c FROM financial_movements")).rows[0].c,beforeCash);
  await service.apply(applyInput("apply-2",advance.id,I.inv2,"40"));assert.equal((await pool.query("SELECT remaining_amount_projection::text r FROM customer_advances WHERE id=$1",[advance.id])).rows[0].r,"0.0000");await assert.rejects(()=>service.apply(applyInput("over",advance.id,I.inv3,"1")),(e)=>e instanceof CustomerAdvanceError&&e.reason==="INSUFFICIENT_ADVANCE_BALANCE");
  const reversed=await service.reverseApplication(reverseInput("reverse-1",advance.id,I.inv1));assert.equal(reversed.value.application.operation,"REVERSAL");assert.equal(reversed.value.advance.remainingAmountProjection,"60.0000");const reapplied=await service.apply(applyInput("reapply-1",advance.id,I.inv1,"50"));assert.equal(reapplied.value.advance.remainingAmountProjection,"10.0000");
  const history=await pool.query("SELECT amount::text amount FROM advance_applications WHERE advance_id=$1 AND sales_invoice_id=$2 ORDER BY applied_at,id",[advance.id,I.inv1]);assert.deepEqual(history.rows.map(r=>r.amount),["60.0000","60.0000","50.0000"]);
  await assert.rejects(()=>pool.query("UPDATE advance_applications SET amount=1 WHERE id=$1",[reapplied.value.application.id]),/immutable/);await assert.rejects(()=>pool.query("DELETE FROM advance_applications WHERE id=$1",[reapplied.value.application.id]),/immutable/);await assert.rejects(()=>pool.query("UPDATE customer_advances SET original_amount=1 WHERE id=$1",[advance.id]),/source context mismatch|immutable/);await assert.rejects(()=>pool.query("DELETE FROM customer_advances WHERE id=$1",[advance.id]),/immutable/);

  const second=await service.create(createInput("create-2","50"));const race=await Promise.allSettled([service.apply(applyInput("race-a",second.value.advance.id,I.inv2,"40")),service.apply(applyInput("race-b",second.value.advance.id,I.inv3,"40"))]);assert.equal(race.filter(x=>x.status==="fulfilled").length,1);assert.equal(race.filter(x=>x.status==="rejected"&&x.reason instanceof CustomerAdvanceError&&x.reason.reason==="INSUFFICIENT_ADVANCE_BALANCE").length,1);assert.equal((await pool.query("SELECT remaining_amount_projection::text r FROM customer_advances WHERE id=$1",[second.value.advance.id])).rows[0].r,"10.0000");

  const posted=await cash.postReceipt({idempotencyKey:"standalone",idempotencyExpiresAt:new Date("2030-01-01T00:00:00Z"),actorUserId:I.user,branchId:I.br,treasuryId:I.tr,counterpartyId:I.cp,amount:"25",occurredAt:new Date("2026-10-02T11:00:00Z")});const duplicateRace=await Promise.allSettled([pool.query("INSERT INTO customer_advances(id,counterparty_id,sales_order_id,receipt_id,original_amount,remaining_amount_projection,created_at) VALUES('ca050000-0000-4000-8000-000000000090',$1,$2,$3,25,25,now())",[I.cp,I.order,posted.value.document.id]),pool.query("INSERT INTO customer_advances(id,counterparty_id,sales_order_id,receipt_id,original_amount,remaining_amount_projection,created_at) VALUES('ca050000-0000-4000-8000-000000000091',$1,$2,$3,25,25,now())",[I.cp,I.order,posted.value.document.id])]);assert.equal(duplicateRace.filter(x=>x.status==="fulfilled").length,1);assert.equal(duplicateRace.filter(x=>x.status==="rejected"&&x.reason?.code==="23505").length,1);

  const beforeForced={receipts:Number((await pool.query("SELECT count(*) c FROM receipts")).rows[0].c),movements:Number((await pool.query("SELECT count(*) c FROM financial_movements")).rows[0].c),advances:Number((await pool.query("SELECT count(*) c FROM customer_advances")).rows[0].c),balance:(await pool.query("SELECT current_balance::text b FROM treasury_balance_positions WHERE treasury_id=$1",[I.tr])).rows[0].b};
  await pool.query("CREATE FUNCTION public.test_0905_fail_advance() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced 09.05 advance failure'; END; $$; CREATE TRIGGER test_0905_fail_advance BEFORE INSERT ON public.customer_advances FOR EACH ROW EXECUTE FUNCTION public.test_0905_fail_advance();");await assert.rejects(()=>service.create(createInput("forced-failure","5")),/forced 09.05 advance failure/);await pool.query("DROP TRIGGER test_0905_fail_advance ON public.customer_advances");await pool.query("DROP FUNCTION public.test_0905_fail_advance()");
  assert.equal(Number((await pool.query("SELECT count(*) c FROM receipts")).rows[0].c),beforeForced.receipts);assert.equal(Number((await pool.query("SELECT count(*) c FROM financial_movements")).rows[0].c),beforeForced.movements);assert.equal(Number((await pool.query("SELECT count(*) c FROM customer_advances")).rows[0].c),beforeForced.advances);assert.equal((await pool.query("SELECT current_balance::text b FROM treasury_balance_positions WHERE treasury_id=$1",[I.tr])).rows[0].b,beforeForced.balance);

  await pool.query("ALTER TABLE customer_advances DISABLE TRIGGER bt_customer_advances__projection_guard");await pool.query("UPDATE customer_advances SET remaining_amount_projection=0 WHERE id=$1",[advance.id]);await pool.query("ALTER TABLE customer_advances ENABLE TRIGGER bt_customer_advances__projection_guard");
  const rebuilt=await service.rebuildProjection({idempotencyKey:"rebuild-1",idempotencyExpiresAt:new Date("2030-01-01T00:00:00Z"),actorUserId:I.user,advanceId:advance.id});assert.equal(rebuilt.value.advance.remainingAmountProjection,"10.0000");assert.equal(rebuilt.value.effectiveApplied,"90.0000");
  await pool.query("UPDATE sales_orders SET status='CANCELLED' WHERE id=$1",[I.order]);assert.equal((await pool.query("SELECT count(*)::int c FROM disbursements")).rows[0].c,0);
  const adr=await pool.query("SELECT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advance_applications' AND column_name='posting_batch_id') has_column,EXISTS(SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='advance_applications' AND indexdef ILIKE '%posting_batch_id%') has_index");assert.deepEqual(adr.rows[0],{has_column:false,has_index:false});
  assert.equal((await pool.query("SELECT count(*)::int c FROM financial_movements")).rows[0].c,3);assert.equal((await pool.query("SELECT count(*)::int c FROM journal_entries")).rows[0].c,0);assert.equal((await pool.query("SELECT count(*)::int c FROM customer_ledger_entries")).rows[0].c,0);assert.deepEqual((await runMigrations({databaseUrl:url,verifyOnly:true})).skipped,MIGRATIONS);
 }finally{await pool.end().catch(()=>{});await cleanupDatabase(url).catch(()=>{})}
});
