import assert from "node:assert/strict";
import test from "node:test";
import pg from "pg";
import { runMigrations } from "../../scripts/database/migrations.mjs";
const { Client }=pg;const databaseUrl=process.env.ERP_TEST_DATABASE_URL;
const CORE_TABLES=["companies","company_phones","company_settings","branches","branch_settings","warehouses","users","auth_sessions","roles","permissions","role_permissions","user_permission_overrides","user_branch_access","document_sequences","idempotency_keys","posting_batches","audit_logs","outbox_events","document_tombstones"];
const COUNTERPARTY_TABLES=["counterparties","counterparty_roles","customer_profiles","supplier_profiles","customer_ledger_entries","supplier_ledger_entries"];
const PRODUCT_TABLES=["product_categories","products","product_variants","units","product_units","variant_barcodes","attributes","attribute_values","product_attributes","variant_attribute_values","price_lists","price_list_items","reorder_levels"];
const INVENTORY_TABLES=["serial_numbers","batches","inventory_movements","inventory_movement_lines","inventory_line_serials","inventory_line_batches","inventory_stock_positions","variant_warehouse_cost_projection","batch_stock_positions","stock_reservations","stock_transfers","stock_transfer_lines","stocktake_sessions","stocktake_lines","stocktake_line_serials","stocktake_line_batches","inventory_adjustments","inventory_adjustment_lines","inventory_adjustment_line_serials","inventory_adjustment_line_batches"];
const SALES_TABLES=["sales_quotes","sales_quote_lines","sales_orders","sales_order_lines","sales_order_status_history","sales_order_shipping_details","sales_order_deliveries","sales_order_delivery_lines","sales_invoices","sales_invoice_lines","sales_returns","sales_return_lines"];
const TARGET_TABLES=PRODUCT_TABLES;
const EXPECTED_COLUMNS={"product_categories":[["id","uuid",true],["name","text",true],["parent_id","uuid",false],["is_active","boolean",true]],"products":[["id","uuid",true],["name","text",true],["category_id","uuid",true],["product_type","text",true],["base_unit_id","uuid",true],["tracking_serial","boolean",true],["tracking_batch","boolean",true],["tracking_expiry","boolean",true],["is_active","boolean",true],["created_at","timestamp with time zone",true],["updated_at","timestamp with time zone",true]],"product_variants":[["id","uuid",true],["product_id","uuid",true],["name","text",true],["sku","text",false],["is_default","boolean",true],["combination_signature","text",true],["minimum_selling_price","numeric(18,4)",false],["is_active","boolean",true],["created_at","timestamp with time zone",true],["updated_at","timestamp with time zone",true]],"units":[["id","uuid",true],["name","text",true],["symbol","text",true],["allows_fraction","boolean",true],["is_active","boolean",true]],"product_units":[["id","uuid",true],["product_id","uuid",true],["unit_id","uuid",true],["conversion_to_base","numeric(18,6)",true],["is_sellable","boolean",true],["is_purchasable","boolean",true]],"variant_barcodes":[["id","uuid",true],["variant_id","uuid",true],["product_unit_id","uuid",true],["barcode","text",true],["is_primary","boolean",true]],"attributes":[["id","uuid",true],["name","text",true],["attribute_type","text",true],["usage_type","text",true],["is_active","boolean",true]],"attribute_values":[["id","uuid",true],["attribute_id","uuid",true],["value","text",true],["sort_order","integer",true]],"product_attributes":[["product_id","uuid",true],["attribute_id","uuid",true]],"variant_attribute_values":[["variant_id","uuid",true],["attribute_value_id","uuid",true]],"price_lists":[["id","uuid",true],["name","text",true],["is_active","boolean",true],["created_at","timestamp with time zone",true],["updated_at","timestamp with time zone",true]],"price_list_items":[["price_list_id","uuid",true],["variant_id","uuid",true],["product_unit_id","uuid",true],["price","numeric(18,4)",true],["updated_at","timestamp with time zone",true]],"reorder_levels":[["variant_id","uuid",true],["warehouse_id","uuid",true],["minimum_quantity","numeric(18,6)",true]]};
const MIGRATIONS=["0001","0002","0003","0004","0005","0006","0007"];
async function withClient(fn){const c=new Client({connectionString:databaseUrl});await c.connect();try{return await fn(c);}finally{await c.end();}}
async function cleanup(){await withClient(async(c)=>{await c.query("DROP VIEW IF EXISTS public.purchase_returnable_quantities_v");await c.query("DROP VIEW IF EXISTS public.sales_returnable_quantities_v");await c.query("DROP TABLE IF EXISTS public.purchase_return_lines, public.purchase_returns, public.purchase_invoice_lines, public.purchase_invoices, public.tax_codes");for(const t of [...SALES_TABLES].reverse())await c.query(`DROP TABLE IF EXISTS public.${t}`);for(const t of [...INVENTORY_TABLES].reverse())await c.query(`DROP TABLE IF EXISTS public.${t}`);for(const t of [...PRODUCT_TABLES].reverse())await c.query(`DROP TABLE IF EXISTS public.${t}`);for(const t of [...COUNTERPARTY_TABLES].reverse())await c.query(`DROP TABLE IF EXISTS public.${t}`);for(const t of [...CORE_TABLES].reverse())await c.query(`DROP TABLE IF EXISTS public.${t}`);await c.query("DROP TABLE IF EXISTS public.schema_migrations");await c.query("DROP EXTENSION IF EXISTS pg_trgm");});}
test("03.C Product Catalog schema remains canonical after later schema migrations",async(t)=>{if(!databaseUrl)return t.skip("ERP_TEST_DATABASE_URL is not configured");await cleanup();try{const first=await runMigrations({databaseUrl});assert.deepEqual(first.applied,MIGRATIONS);await withClient(async(c)=>{const tables=await c.query(`SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname='public' AND tablename=ANY($1::text[]) ORDER BY tablename`,[TARGET_TABLES]);assert.deepEqual(tables.rows.map(r=>r.tablename),[...TARGET_TABLES].sort());const cols=await c.query(`SELECT c.relname AS table_name,a.attname AS column_name,pg_catalog.format_type(a.atttypid,a.atttypmod) AS data_type,a.attnotnull AS not_null FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid WHERE n.nspname='public' AND c.relkind='r' AND c.relname=ANY($1::text[]) AND a.attnum>0 AND NOT a.attisdropped ORDER BY c.relname,a.attnum`,[TARGET_TABLES]);const actual=Object.fromEntries(TARGET_TABLES.map(x=>[x,[]]));for(const r of cols.rows)actual[r.table_name].push([r.column_name,r.data_type,r.not_null]);assert.deepEqual(actual,EXPECTED_COLUMNS);const constraints=await c.query(`SELECT count(*)::int AS count FROM pg_catalog.pg_constraint con JOIN pg_catalog.pg_class c ON c.oid=con.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=ANY($1::text[])`,[TARGET_TABLES]);assert.equal(constraints.rows[0].count,0);const indexes=await c.query(`SELECT count(*)::int AS count FROM pg_catalog.pg_index i JOIN pg_catalog.pg_class c ON c.oid=i.indrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=ANY($1::text[])`,[TARGET_TABLES]);assert.equal(indexes.rows[0].count,0);const baseUnit=await c.query(`SELECT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='product_units' AND column_name='is_base') AS has_is_base,EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='products' AND column_name='base_unit_id') AS has_base_unit_id`);assert.equal(baseUnit.rows[0].has_is_base,false);assert.equal(baseUnit.rows[0].has_base_unit_id,true);const future=await c.query("SELECT to_regclass('public.treasuries') IS NULL AS absent");assert.equal(future.rows[0].absent,true);const history=await c.query("SELECT version,name,checksum FROM schema_migrations ORDER BY version");assert.equal(history.rowCount,7);const target=history.rows.find(r=>r.version==="0004");assert.equal(target?.name,"product_catalog");assert.match(target?.checksum??"",/^[0-9a-f]{64}$/);});const second=await runMigrations({databaseUrl});assert.deepEqual(second.applied,[]);assert.deepEqual(second.skipped,MIGRATIONS);const verification=await runMigrations({databaseUrl,verifyOnly:true});assert.deepEqual(verification.applied,[]);assert.deepEqual(verification.skipped,MIGRATIONS);}finally{await cleanup();}});
